apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.appscode.com
    k8s.io/kind: ClickHouseBinding
    k8s.io/resource: clickhousebindings
    k8s.io/version: v1alpha1
  name: catalog.appscode.com-v1alpha1-clickhousebindings
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.appscode.com/clickhousebindings.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.appscode.com/clickhousebindings.png
    type: image/png
  resource:
    group: catalog.appscode.com
    kind: ClickHouseBinding
    name: clickhousebindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogappscodecom-clickhousebinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:fd63e1dcccad89484784016db80e9e83defd323ac73e48630c53d3c274cef5f4
    enforceQuota: false
