apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.appscode.com
    k8s.io/kind: ElasticsearchBinding
    k8s.io/resource: elasticsearchbindings
    k8s.io/version: v1alpha1
  name: catalog.appscode.com-v1alpha1-elasticsearchbindings
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.appscode.com/elasticsearchbindings.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.appscode.com/elasticsearchbindings.png
    type: image/png
  resource:
    group: catalog.appscode.com
    kind: ElasticsearchBinding
    name: elasticsearchbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogappscodecom-elasticsearchbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4b85c4525874d293a82d0ec1f8028c74c5619cd8412e011b6c97740c672cb61f
    enforceQuota: false
