apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: ProviderConfig
    k8s.io/resource: providerconfigs
    k8s.io/version: v1beta1
  name: aws.kubedb.com-v1beta1-providerconfigs
spec:
  resource:
    group: aws.kubedb.com
    kind: ProviderConfig
    name: providerconfigs
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: awskubedbcom-providerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b0847abb01a0d960dfd12597996d3236fcf7defe6d1d06eeeec19a4f84a4faf7
    enforceQuota: false
