apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: ProviderConfig
    k8s.io/resource: providerconfigs
    k8s.io/version: v1beta1
  name: aws.kubedb.com-v1beta1-providerconfigs
spec:
  resource:
    group: aws.kubedb.com
    kind: ProviderConfig
    name: providerconfigs
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: awskubedbcom-providerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:a31d03bd8f03b9b00c37826545ed38234d10acb86442e3b2d277121121a49d5f
    enforceQuota: false
