apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: ProviderConfigUsage
    k8s.io/resource: providerconfigusages
    k8s.io/version: v1beta1
  name: aws.kubedb.com-v1beta1-providerconfigusages
spec:
  resource:
    group: aws.kubedb.com
    kind: ProviderConfigUsage
    name: providerconfigusages
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: awskubedbcom-providerconfigusage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:46237f30b2f1d2d7b6af0c6a49c24e2c55c19a020f783d8bcd47775562f1ec6e
    enforceQuota: false
