apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: ClickHouse
    k8s.io/resource: clickhouses
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-clickhouses
spec:
  resource:
    group: gitops.kubedb.com
    kind: ClickHouse
    name: clickhouses
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-clickhouse-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:7ca7dce3fccb7514f1e833f4f77892878cd5e7419a4b2beba3c77290a3f70884
    enforceQuota: false
