apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: FerretDB
    k8s.io/resource: ferretdbs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-ferretdbs
spec:
  resource:
    group: gitops.kubedb.com
    kind: FerretDB
    name: ferretdbs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-ferretdb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f1fa7c9d44ed239fc22a7ece44eeb5ff88ced5140db728d09919e645a653e5a7
    enforceQuota: false
