apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Kafka
    k8s.io/resource: kafkas
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-kafkas
spec:
  resource:
    group: gitops.kubedb.com
    kind: Kafka
    name: kafkas
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-kafka-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2d73e293e7dfec5d11ffab04d3962a6f8fc567e9f572323c55cb866296fe4481
    enforceQuota: false
