apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Kafka
    k8s.io/resource: kafkas
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-kafkas
spec:
  resource:
    group: gitops.kubedb.com
    kind: Kafka
    name: kafkas
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-kafka-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d1baffeacc91f466b0daeee7164bcec5467a58e8b76d8b5a3895ba87114d4efc
    enforceQuota: false
