apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Memcached
    k8s.io/resource: memcacheds
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-memcacheds
spec:
  resource:
    group: gitops.kubedb.com
    kind: Memcached
    name: memcacheds
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-memcached-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:bbdc550aa0d859d0fd97a326b5baf9b1b9dfaee866944f58f9e31a5433abf61e
    enforceQuota: false
