apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Memcached
    k8s.io/resource: memcacheds
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-memcacheds
spec:
  resource:
    group: gitops.kubedb.com
    kind: Memcached
    name: memcacheds
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-memcached-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:6ad74dd77bc4c78094ba26577ca23ac26fff2534d94db3955bc049e56d60e3c2
    enforceQuota: false
