apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Memcached
    k8s.io/resource: memcacheds
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-memcacheds
spec:
  resource:
    group: gitops.kubedb.com
    kind: Memcached
    name: memcacheds
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-memcached-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c0526e0e96e043cf5c4bfc86579e2729b705a5d778b6d86e5ebaec20a29431e3
    enforceQuota: false
