apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: MongoDB
    k8s.io/resource: mongodbs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-mongodbs
spec:
  resource:
    group: gitops.kubedb.com
    kind: MongoDB
    name: mongodbs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-mongodb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:3c056c1507190b4907b9602bb078067bd72b785565ecd8ae9b83b34260214f3b
    enforceQuota: false
