apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: PerconaXtraDB
    k8s.io/resource: perconaxtradbs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-perconaxtradbs
spec:
  resource:
    group: gitops.kubedb.com
    kind: PerconaXtraDB
    name: perconaxtradbs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-perconaxtradb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ff508d4a3ed95a0b279425f18872616e46b33912590d38f0422106e93c9cb136
    enforceQuota: false
