apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: PerconaXtraDB
    k8s.io/resource: perconaxtradbs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-perconaxtradbs
spec:
  resource:
    group: gitops.kubedb.com
    kind: PerconaXtraDB
    name: perconaxtradbs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-perconaxtradb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:928f1b877d7c2c476af2a6d41c051928ac2e709507fba1ab916b98328113e818
    enforceQuota: false
