apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Postgres
    k8s.io/resource: postgreses
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-postgreses
spec:
  resource:
    group: gitops.kubedb.com
    kind: Postgres
    name: postgreses
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-postgres-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3a4114da8aaa9b066a032044a064635f652c790af6aa03fa90942b53052a55cc
    enforceQuota: false
