apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Qdrant
    k8s.io/resource: qdrants
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-qdrants
spec:
  resource:
    group: gitops.kubedb.com
    kind: Qdrant
    name: qdrants
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-qdrant-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2cd22be3c236b041172b3e094224f0f13f7e265465dc92b39ecd9f5e478c9865
    enforceQuota: false
