apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: RabbitMQ
    k8s.io/resource: rabbitmqs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-rabbitmqs
spec:
  resource:
    group: gitops.kubedb.com
    kind: RabbitMQ
    name: rabbitmqs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-rabbitmq-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:6493033773f83a0ab9d8055bf4cb59d17c5b9aa054388a866fc0b55a4fc793cc
    enforceQuota: false
