apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: RedisSentinel
    k8s.io/resource: redissentinels
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-redissentinels
spec:
  resource:
    group: gitops.kubedb.com
    kind: RedisSentinel
    name: redissentinels
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-redissentinel-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3ff0e029355e406b84b9fac959c3ca6c3599fa294af16be2662e23b39719631a
    enforceQuota: false
