apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: RedisSentinel
    k8s.io/resource: redissentinels
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-redissentinels
spec:
  resource:
    group: gitops.kubedb.com
    kind: RedisSentinel
    name: redissentinels
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-redissentinel-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:91abe88920f6d79630d1c09699d8936002d7e43a4b40f5e6aa8f80a0546b7894
    enforceQuota: false
