apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Redis
    k8s.io/resource: redises
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-redises
spec:
  resource:
    group: gitops.kubedb.com
    kind: Redis
    name: redises
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-redis-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f90e08caa7f20e08f38235b7873227f3ef82626bf52b3f1d72dccd4b1586b218
    enforceQuota: false
