apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: RedisSentinel
    k8s.io/resource: redissentinels
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-redissentinels
spec:
  resource:
    group: gitops.kubedb.com
    kind: RedisSentinel
    name: redissentinels
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-redissentinel-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:d336b92bac1d3d2afa7ae4ba1fc1c56d7177317cd09db508cd4c7dab6bad3297
    enforceQuota: false
