apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Solr
    k8s.io/resource: solrs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-solrs
spec:
  resource:
    group: gitops.kubedb.com
    kind: Solr
    name: solrs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-solr-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:103bd4fdda26a84f516da0d44ce472ac5dc2cdf56a04b03988b7a73357f37087
    enforceQuota: false
