apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gitops.kubedb.com
    k8s.io/kind: Solr
    k8s.io/resource: solrs
    k8s.io/version: v1alpha1
  name: gitops.kubedb.com-v1alpha1-solrs
spec:
  resource:
    group: gitops.kubedb.com
    kind: Solr
    name: solrs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gitopskubedbcom-solr-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4fe1875f8fd49b98dc275cdb7057bb17f19bb5ef171e2d56ade705b6228d2601
    enforceQuota: false
