apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: ManagedCluster
    k8s.io/resource: managedclusters
    k8s.io/version: v1
  name: cluster.open-cluster-management.io-v1-managedclusters
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: ManagedCluster
    name: managedclusters
    scope: Cluster
    version: v1
  ui:
    editor:
      name: clusteropenclustermanagementio-managedcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:238e1d38b10aa73bb6c3a385c01cdc9896451e8dfc164585187507eb017f49e3
    enforceQuota: false
