apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: azure.kubedb.com
    k8s.io/kind: ProviderConfig
    k8s.io/resource: providerconfigs
    k8s.io/version: v1beta1
  name: azure.kubedb.com-v1beta1-providerconfigs
spec:
  resource:
    group: azure.kubedb.com
    kind: ProviderConfig
    name: providerconfigs
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: azurekubedbcom-providerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:24eaeef6231831682abf64bd73c88232b22af13637d14c7cf5d963a3f3f79a27
    enforceQuota: false
