apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: azure.kubedb.com
    k8s.io/kind: ProviderConfigUsage
    k8s.io/resource: providerconfigusages
    k8s.io/version: v1beta1
  name: azure.kubedb.com-v1beta1-providerconfigusages
spec:
  resource:
    group: azure.kubedb.com
    kind: ProviderConfigUsage
    name: providerconfigusages
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: azurekubedbcom-providerconfigusage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0eac9574729a3025479414c88d4160025e6d95b65bee475012879dc0839eab72
    enforceQuota: false
