apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: Cluster
    k8s.io/resource: clusters
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-clusters
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: Cluster
    name: clusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-cluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:958698c623785808c2e56c3bdb7910d9f9283251518ad7b6c99a21c2170261eb
    enforceQuota: false
