apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: ReplicationGroup
    k8s.io/resource: replicationgroups
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-replicationgroups
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: ReplicationGroup
    name: replicationgroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-replicationgroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b7528d798d6e2969ec06ffe52b322c1a6ae1272b0dec9d4736ffb1fb750efbda
    enforceQuota: false
