apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: SubnetGroup
    k8s.io/resource: subnetgroups
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-subnetgroups
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: SubnetGroup
    name: subnetgroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-subnetgroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7d9e70e5cd33f59f16760a3564778879a0318a1071a42a244f723e06ee300383
    enforceQuota: false
