apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: User
    k8s.io/resource: users
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-users
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: User
    name: users
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-user-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:00d1e0add3eb9a9eb05a8cb54a3e5e269ebd9b5004b7fa15402a3af4be7f5d9d
    enforceQuota: false
