apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: User
    k8s.io/resource: users
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-users
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: User
    name: users
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-user-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:d631590dafa240626fd9c5815da84f46fadb94bc35fbd57da7a4c142b75bc855
    enforceQuota: false
