apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: UserGroup
    k8s.io/resource: usergroups
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-usergroups
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: UserGroup
    name: usergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-usergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:11b77a7dced9315edb51496502fd7c6e912d40c65a55d2dfecbbbc1be742956c
    enforceQuota: false
