apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: elasticache.aws.kubedb.com
    k8s.io/kind: User
    k8s.io/resource: users
    k8s.io/version: v1alpha1
  name: elasticache.aws.kubedb.com-v1alpha1-users
spec:
  resource:
    group: elasticache.aws.kubedb.com
    kind: User
    name: users
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticacheawskubedbcom-user-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3e5abe126f1492a108aa31353026a013251ea88fb87dd65685deb39513f29545
    enforceQuota: false
