apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImagePolicy
    k8s.io/resource: imagepolicies
    k8s.io/version: v1beta2
  name: image.toolkit.fluxcd.io-v1beta2-imagepolicies
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImagePolicy
    name: imagepolicies
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: imagetoolkitfluxcdio-imagepolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1a3098fb6c8bdbd3e05d89c54b4fb62419e2491de813136f0767048e64f15030
    enforceQuota: false
