apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImageRepository
    k8s.io/resource: imagerepositories
    k8s.io/version: v1beta2
  name: image.toolkit.fluxcd.io-v1beta2-imagerepositories
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImageRepository
    name: imagerepositories
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: imagetoolkitfluxcdio-imagerepository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e66f3d10cc370a3ac48f45362581b3a270b0a5cbe0d4a4d8fe0a7d6c9b3fb3d2
    enforceQuota: false
