apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: source.toolkit.fluxcd.io
    k8s.io/kind: HelmRepository
    k8s.io/resource: helmrepositories
    k8s.io/version: v1
  name: source.toolkit.fluxcd.io-v1-helmrepositories
spec:
  resource:
    group: source.toolkit.fluxcd.io
    kind: HelmRepository
    name: helmrepositories
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: sourcetoolkitfluxcdio-helmrepository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2e9cb7dd4d6aa3b4617a952cb2cd320f7d0a04d7fccff06358fd8767ebb98166
    enforceQuota: false
