apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.k8s.appscode.com
    k8s.io/kind: ClusterProfile
    k8s.io/resource: clusterprofiles
    k8s.io/version: v1alpha1
  name: ui.k8s.appscode.com-v1alpha1-clusterprofiles
spec:
  resource:
    group: ui.k8s.appscode.com
    kind: ClusterProfile
    name: clusterprofiles
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: uik8sappscodecom-clusterprofile-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:b289814e65b7fa9816ae54079a7baaf868a3ddbfa05b15fa9e63cdce118e6d5d
    enforceQuota: false
