apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.k8s.appscode.com
    k8s.io/kind: ResourceEditor
    k8s.io/resource: resourceeditors
    k8s.io/version: v1alpha1
  name: ui.k8s.appscode.com-v1alpha1-resourceeditors
spec:
  resource:
    group: ui.k8s.appscode.com
    kind: ResourceEditor
    name: resourceeditors
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: uik8sappscodecom-resourceeditor-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:aab10b27eb992d6343ab6f549e6676274f0bd73f54f14335f48d8e81c8adba41
    enforceQuota: false
