apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: BackupStorage
    k8s.io/resource: backupstorages
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-backupstorages
spec:
  resource:
    group: storage.kubestash.com
    kind: BackupStorage
    name: backupstorages
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-backupstorage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f844b96caa86fb9e8bff226e40cc0ec90170123e73844cbdabd08720deb0b318
    enforceQuota: false
    options:
      name: storagekubestashcom-backupstorage-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c8811e4d029d3c5d1f4a4cfe4be73c826d1beeb31bbf16fc9ae6c9bffa09042e
