apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: BackupStorage
    k8s.io/resource: backupstorages
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-backupstorages
spec:
  resource:
    group: storage.kubestash.com
    kind: BackupStorage
    name: backupstorages
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-backupstorage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e9c8ff27382218c2bd928b11979e21832c3a91adfd86e184e5c2d3956859390f
    enforceQuota: false
    options:
      name: storagekubestashcom-backupstorage-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:55953a518ede4a1c48142f247eb33b1e1c6cc60b942b03d40452c8b56ff5a996
