apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: BackupStorage
    k8s.io/resource: backupstorages
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-backupstorages
spec:
  resource:
    group: storage.kubestash.com
    kind: BackupStorage
    name: backupstorages
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-backupstorage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:97a69364613836c1daf452b46e3e749f72d40727a1efade1df6e8e6e5ae7277d
    enforceQuota: false
    options:
      name: storagekubestashcom-backupstorage-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:c411630369dd5b500c01ab7b4aa55774266d028c0de44cbb0b09b4451f4788ea
