apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: Repository
    k8s.io/resource: repositories
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-repositories
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/storage.kubestash.com/repositories.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/storage.kubestash.com/repositories.png
    type: image/png
  resource:
    group: storage.kubestash.com
    kind: Repository
    name: repositories
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-repository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ea02982bdec9dbfce241124a2fe8fef09bb3355f6da28951941c8238dc392cbb
    enforceQuota: false
    options:
      name: storagekubestashcom-repository-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:83d82bc2be9ac7fc17043877f3e9051fe4bf71a60bbe22f8fb7c357985932bfc
