apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: Repository
    k8s.io/resource: repositories
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-repositories
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/storage.kubestash.com/repositories.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/storage.kubestash.com/repositories.png
    type: image/png
  resource:
    group: storage.kubestash.com
    kind: Repository
    name: repositories
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-repository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9e83b5b0f2a9245db1d8ab6b7bb75ac453fea4351daaff62c96b208731a0360e
    enforceQuota: false
    options:
      name: storagekubestashcom-repository-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6a4a20d98ae7c742c8a9ec974bda0139d2f04aebb30c3f2098c29d5123ced5bb
