apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: Repository
    k8s.io/resource: repositories
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-repositories
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/storage.kubestash.com/repositories.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/storage.kubestash.com/repositories.png
    type: image/png
  resource:
    group: storage.kubestash.com
    kind: Repository
    name: repositories
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-repository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:bbe313ffdf534946d5dab7a06d6d685c89e85ee1188a93c54d8f8e4592a38131
    enforceQuota: false
    options:
      name: storagekubestashcom-repository-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:336d91807b0ffabf350b620203590d999959b105949dec3e7752679ca30d8518
