apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: RetentionPolicy
    k8s.io/resource: retentionpolicies
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-retentionpolicies
spec:
  resource:
    group: storage.kubestash.com
    kind: RetentionPolicy
    name: retentionpolicies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-retentionpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6752837241a33aedb2c0c3c9e3380107432f4300398a20eca233cbb971eff362
    enforceQuota: false
