apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.kubestash.com
    k8s.io/kind: Snapshot
    k8s.io/resource: snapshots
    k8s.io/version: v1alpha1
  name: storage.kubestash.com-v1alpha1-snapshots
spec:
  resource:
    group: storage.kubestash.com
    kind: Snapshot
    name: snapshots
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: storagekubestashcom-snapshot-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:961b890c27aaa9f01132a61906c95da4e3b33bd3d3f89d80c753cd38b6a15d0f
    enforceQuota: false
