apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gcp.kubedb.com
    k8s.io/kind: StoreConfig
    k8s.io/resource: storeconfigs
    k8s.io/version: v1alpha1
  name: gcp.kubedb.com-v1alpha1-storeconfigs
spec:
  resource:
    group: gcp.kubedb.com
    kind: StoreConfig
    name: storeconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: gcpkubedbcom-storeconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4eeb9455790b13b398a3a8d2664c4230256b2a4cfe0396fca544103e314c2c41
    enforceQuota: false
