apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureASOManagedClusterTemplate
    k8s.io/resource: azureasomanagedclustertemplates
    k8s.io/version: v1alpha1
  name: infrastructure.cluster.x-k8s.io-v1alpha1-azureasomanagedclustertemplates
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureASOManagedClusterTemplate
    name: azureasomanagedclustertemplates
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: infrastructureclusterxk8sio-azureasomanagedclustertemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b722abb7449d0c4caad8dd9c416ddc80a306afb96dfd7a9c8062ca7dbc3824c3
    enforceQuota: false
