apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: ReferenceGrant
    k8s.io/resource: referencegrants
    k8s.io/version: v1beta1
  name: gateway.networking.k8s.io-v1beta1-referencegrants
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: ReferenceGrant
    name: referencegrants
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: gatewaynetworkingk8sio-referencegrant-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:84975d0da04a5e7af48188180551e3df9d582614b5ab158ca958600de230d220
    enforceQuota: false
