apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: ReferenceGrant
    k8s.io/resource: referencegrants
    k8s.io/version: v1beta1
  name: gateway.networking.k8s.io-v1beta1-referencegrants
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: ReferenceGrant
    name: referencegrants
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: gatewaynetworkingk8sio-referencegrant-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6f12e31c14443657a480c044a0e486f8288b4e44dbb4292ba1f979c991bd8404
    enforceQuota: false
