apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: CassandraVersion
    k8s.io/resource: cassandraversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-cassandraversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/cassandraversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/cassandraversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: CassandraVersion
    name: cassandraversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-cassandraversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:fd15953be4d9b52b558d33434e2b5eaac756a48a6d4b0258a624c7c51e70e9fd
    enforceQuota: false
