apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: HanaDBVersion
    k8s.io/resource: hanadbversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-hanadbversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: HanaDBVersion
    name: hanadbversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-hanadbversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:946dfadcef5d17d0af6d45b4f2e774d0ac1b3b86c7afec5211a9c1d8f68ff5b4
    enforceQuota: false
