apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: HanaDBVersion
    k8s.io/resource: hanadbversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-hanadbversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: HanaDBVersion
    name: hanadbversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-hanadbversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4476d72505ce28a09d34792dba3121a33dec889f22a2e7228da3e6057ec48d97
    enforceQuota: false
