apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: IgniteVersion
    k8s.io/resource: igniteversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-igniteversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/igniteversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/igniteversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: IgniteVersion
    name: igniteversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-igniteversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:530741b33c8b408e6e3fb57d88384f61c60a0d3c9239980cade2b43e41d1a8eb
    enforceQuota: false
