apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: KafkaConnectorVersion
    k8s.io/resource: kafkaconnectorversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-kafkaconnectorversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: KafkaConnectorVersion
    name: kafkaconnectorversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-kafkaconnectorversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1f6898e735b62eeff209da97b681282c2f63b4d147e3c5e9c79fd91fb2311a96
    enforceQuota: false
