apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: KafkaConnectorVersion
    k8s.io/resource: kafkaconnectorversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-kafkaconnectorversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: KafkaConnectorVersion
    name: kafkaconnectorversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-kafkaconnectorversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:580cf697a72731a79a77a0a2f6db5bb7656e8fdc38160a1b472818f6e0a5a4c0
    enforceQuota: false
