apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: Neo4jVersion
    k8s.io/resource: neo4jversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-neo4jversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: Neo4jVersion
    name: neo4jversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubedbcom-neo4jversion-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a9ea95289d9a40b664d4dfcb6fb81f346e3e7d9eef77a760b72b287851215fcc
    enforceQuota: false
