apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kube-bind.appscode.com
    k8s.io/kind: APIServiceExport
    k8s.io/resource: apiserviceexports
    k8s.io/version: v1alpha1
  name: kube-bind.appscode.com-v1alpha1-apiserviceexports
spec:
  resource:
    group: kube-bind.appscode.com
    kind: APIServiceExport
    name: apiserviceexports
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kubebindappscodecom-apiserviceexport-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:a564d5e755ed84a2490529771c93ea740abd81469b52d22eaa8685e4cfb74d20
    enforceQuota: false
