apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kube-bind.appscode.com
    k8s.io/kind: APIServiceExport
    k8s.io/resource: apiserviceexports
    k8s.io/version: v1alpha1
  name: kube-bind.appscode.com-v1alpha1-apiserviceexports
spec:
  resource:
    group: kube-bind.appscode.com
    kind: APIServiceExport
    name: apiserviceexports
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kubebindappscodecom-apiserviceexport-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:caf09ab76e23e5d579ac5412ada91ee58e39304a5c02ff4c8929bb929ac2447f
    enforceQuota: false
