apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kube-bind.appscode.com
    k8s.io/kind: APIServiceExportRequest
    k8s.io/resource: apiserviceexportrequests
    k8s.io/version: v1alpha1
  name: kube-bind.appscode.com-v1alpha1-apiserviceexportrequests
spec:
  resource:
    group: kube-bind.appscode.com
    kind: APIServiceExportRequest
    name: apiserviceexportrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kubebindappscodecom-apiserviceexportrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e1762d8102101fbc1ab04f02d335407e0ff9b5786951753194f021afd3840111
    enforceQuota: false
