apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kube-bind.appscode.com
    k8s.io/kind: ClusterBinding
    k8s.io/resource: clusterbindings
    k8s.io/version: v1alpha1
  name: kube-bind.appscode.com-v1alpha1-clusterbindings
spec:
  resource:
    group: kube-bind.appscode.com
    kind: ClusterBinding
    name: clusterbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kubebindappscodecom-clusterbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9cf9ce1e769bbba899f0a99f0c2c8a44971445a5bbe4f088c5f5f15ece3fe4cd
    enforceQuota: false
