apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: spanner.gcp.kubedb.com
    k8s.io/kind: Instance
    k8s.io/resource: instances
    k8s.io/version: v1alpha1
  name: spanner.gcp.kubedb.com-v1alpha1-instances
spec:
  resource:
    group: spanner.gcp.kubedb.com
    kind: Instance
    name: instances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: spannergcpkubedbcom-instance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:450b80f4dd138cd88b29042093efbe87b7bf7faf98eb07116f04a51a868cc781
    enforceQuota: false
