apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: spanner.gcp.kubedb.com
    k8s.io/kind: Instance
    k8s.io/resource: instances
    k8s.io/version: v1alpha1
  name: spanner.gcp.kubedb.com-v1alpha1-instances
spec:
  resource:
    group: spanner.gcp.kubedb.com
    kind: Instance
    name: instances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: spannergcpkubedbcom-instance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:995f76b99ef0f7674f446109072500339808a8b0d49c5e7138ae0c53be15d329
    enforceQuota: false
