apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: spanner.gcp.kubedb.com
    k8s.io/kind: Instance
    k8s.io/resource: instances
    k8s.io/version: v1alpha1
  name: spanner.gcp.kubedb.com-v1alpha1-instances
spec:
  resource:
    group: spanner.gcp.kubedb.com
    kind: Instance
    name: instances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: spannergcpkubedbcom-instance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:06ba083b32a393236294f2ea67b17034c7abdb881a096645618f1401f0fbfcb1
    enforceQuota: false
