/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by set-gen. DO NOT EDIT.

package sets

import (
	"reflect"
	"sort"

	"kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
)

// sets.EdgeLabel is a set of v1alpha1.EdgeLabels, implemented via map[v1alpha1.EdgeLabel]struct{} for minimal memory consumption.
type EdgeLabel map[v1alpha1.EdgeLabel]Empty

// NewEdgeLabel creates a EdgeLabel from a list of values.
func NewEdgeLabel(items ...v1alpha1.EdgeLabel) EdgeLabel {
	ss := make(EdgeLabel, len(items))
	ss.Insert(items...)
	return ss
}

// EdgeLabelKeySet creates a EdgeLabel from a keys of a map[v1alpha1.EdgeLabel](? extends interface{}).
// If the value passed in is not actually a map, this will panic.
func EdgeLabelKeySet(theMap interface{}) EdgeLabel {
	v := reflect.ValueOf(theMap)
	ret := EdgeLabel{}

	for _, keyValue := range v.MapKeys() {
		ret.Insert(keyValue.Interface().(v1alpha1.EdgeLabel))
	}
	return ret
}

// Insert adds items to the set.
func (s EdgeLabel) Insert(items ...v1alpha1.EdgeLabel) EdgeLabel {
	for _, item := range items {
		s[item] = Empty{}
	}
	return s
}

// Delete removes all items from the set.
func (s EdgeLabel) Delete(items ...v1alpha1.EdgeLabel) EdgeLabel {
	for _, item := range items {
		delete(s, item)
	}
	return s
}

// Has returns true if and only if item is contained in the set.
func (s EdgeLabel) Has(item v1alpha1.EdgeLabel) bool {
	_, contained := s[item]
	return contained
}

// HasAll returns true if and only if all items are contained in the set.
func (s EdgeLabel) HasAll(items ...v1alpha1.EdgeLabel) bool {
	for _, item := range items {
		if !s.Has(item) {
			return false
		}
	}
	return true
}

// HasAny returns true if any items are contained in the set.
func (s EdgeLabel) HasAny(items ...v1alpha1.EdgeLabel) bool {
	for _, item := range items {
		if s.Has(item) {
			return true
		}
	}
	return false
}

// Difference returns a set of objects that are not in s2
// For example:
// s1 = {a1, a2, a3}
// s2 = {a1, a2, a4, a5}
// s1.Difference(s2) = {a3}
// s2.Difference(s1) = {a4, a5}
func (s EdgeLabel) Difference(s2 EdgeLabel) EdgeLabel {
	result := NewEdgeLabel()
	for key := range s {
		if !s2.Has(key) {
			result.Insert(key)
		}
	}
	return result
}

// Union returns a new set which includes items in either s1 or s2.
// For example:
// s1 = {a1, a2}
// s2 = {a3, a4}
// s1.Union(s2) = {a1, a2, a3, a4}
// s2.Union(s1) = {a1, a2, a3, a4}
func (s1 EdgeLabel) Union(s2 EdgeLabel) EdgeLabel {
	result := NewEdgeLabel()
	for key := range s1 {
		result.Insert(key)
	}
	for key := range s2 {
		result.Insert(key)
	}
	return result
}

// Intersection returns a new set which includes the item in BOTH s1 and s2
// For example:
// s1 = {a1, a2}
// s2 = {a2, a3}
// s1.Intersection(s2) = {a2}
func (s1 EdgeLabel) Intersection(s2 EdgeLabel) EdgeLabel {
	var walk, other EdgeLabel
	result := NewEdgeLabel()
	if s1.Len() < s2.Len() {
		walk = s1
		other = s2
	} else {
		walk = s2
		other = s1
	}
	for key := range walk {
		if other.Has(key) {
			result.Insert(key)
		}
	}
	return result
}

// IsSuperset returns true if and only if s1 is a superset of s2.
func (s1 EdgeLabel) IsSuperset(s2 EdgeLabel) bool {
	for item := range s2 {
		if !s1.Has(item) {
			return false
		}
	}
	return true
}

// Equal returns true if and only if s1 is equal (as a set) to s2.
// Two sets are equal if their membership is identical.
// (In practice, this means same elements, order doesn't matter)
func (s1 EdgeLabel) Equal(s2 EdgeLabel) bool {
	return len(s1) == len(s2) && s1.IsSuperset(s2)
}

type sortableSliceOfEdgeLabel []v1alpha1.EdgeLabel

func (s sortableSliceOfEdgeLabel) Len() int           { return len(s) }
func (s sortableSliceOfEdgeLabel) Less(i, j int) bool { return lessEdgeLabel(s[i], s[j]) }
func (s sortableSliceOfEdgeLabel) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }

// List returns the contents as a sorted v1alpha1.EdgeLabel slice.
func (s EdgeLabel) List() []v1alpha1.EdgeLabel {
	res := make(sortableSliceOfEdgeLabel, 0, len(s))
	for key := range s {
		res = append(res, key)
	}
	sort.Sort(res)
	return []v1alpha1.EdgeLabel(res)
}

// UnsortedList returns the slice with contents in random order.
func (s EdgeLabel) UnsortedList() []v1alpha1.EdgeLabel {
	res := make([]v1alpha1.EdgeLabel, 0, len(s))
	for key := range s {
		res = append(res, key)
	}
	return res
}

// Returns a single element from the set.
func (s EdgeLabel) PopAny() (v1alpha1.EdgeLabel, bool) {
	for key := range s {
		s.Delete(key)
		return key, true
	}
	var zeroValue v1alpha1.EdgeLabel
	return zeroValue, false
}

// Len returns the size of the set.
func (s EdgeLabel) Len() int {
	return len(s)
}

func lessEdgeLabel(lhs, rhs v1alpha1.EdgeLabel) bool {
	return lhs < rhs
}
