apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: work.open-cluster-management.io
    k8s.io/kind: ManifestWorkReplicaSet
    k8s.io/resource: manifestworkreplicasets
    k8s.io/version: v1alpha1
  name: work.open-cluster-management.io-v1alpha1-manifestworkreplicasets
spec:
  resource:
    group: work.open-cluster-management.io
    kind: ManifestWorkReplicaSet
    name: manifestworkreplicasets
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: workopenclustermanagementio-manifestworkreplicaset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e2eda89c5beb2cc194bf5f6eda111ab0aa2d3dd6818fb94d17ed9ef34d376117
    enforceQuota: false
