/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/identity/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// NatsCredentialRequestsGetter has a method to return a NatsCredentialRequestInterface.
// A group's client should implement this interface.
type NatsCredentialRequestsGetter interface {
	NatsCredentialRequests() NatsCredentialRequestInterface
}

// NatsCredentialRequestInterface has methods to work with NatsCredentialRequest resources.
type NatsCredentialRequestInterface interface {
	Create(ctx context.Context, natsCredentialRequest *v1alpha1.NatsCredentialRequest, opts v1.CreateOptions) (*v1alpha1.NatsCredentialRequest, error)
	NatsCredentialRequestExpansion
}

// natsCredentialRequests implements NatsCredentialRequestInterface
type natsCredentialRequests struct {
	client rest.Interface
}

// newNatsCredentialRequests returns a NatsCredentialRequests
func newNatsCredentialRequests(c *IdentityV1alpha1Client) *natsCredentialRequests {
	return &natsCredentialRequests{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a natsCredentialRequest and creates it.  Returns the server's representation of the natsCredentialRequest, and an error, if there is any.
func (c *natsCredentialRequests) Create(ctx context.Context, natsCredentialRequest *v1alpha1.NatsCredentialRequest, opts v1.CreateOptions) (result *v1alpha1.NatsCredentialRequest, err error) {
	result = &v1alpha1.NatsCredentialRequest{}
	err = c.client.Post().
		Resource("natscredentialrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(natsCredentialRequest).
		Do(ctx).
		Into(result)
	return
}
