apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: catalog.appscode.com
    k8s.io/kind: OracleBinding
    k8s.io/resource: oraclebindings
    k8s.io/version: v1alpha1
  name: catalog.appscode.com-v1alpha1-oraclebindings
spec:
  defaultView: true
  resource:
    group: catalog.appscode.com
    kind: OracleBinding
    name: oraclebindings
    scope: Namespaced
    version: v1alpha1
