apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: BackupBlueprint
    k8s.io/resource: backupblueprints
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-backupblueprints
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/backupblueprints.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/backupblueprints.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: BackupBlueprint
    name: backupblueprints
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: stashappscodecom-backupblueprint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6bb75b5bc97c36ac19a04920b28249faa6ac4f3bb92fc19778d25991395f540b
    enforceQuota: false
