apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-restoresessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: stashappscodecom-restoresession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0a98c274239b44d0eb1266ba3cc69e723370aff58e342c63447d0889b41adfb7
    enforceQuota: false
    options:
      name: stashappscodecom-restoresession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:81a29f4821e892589840db48bbcdcf99daeb2a1a30ea670c19ff0dfdcd52f819
