apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-restoresessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: stashappscodecom-restoresession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b63513e3e3152d7d7d706bf69a782819a7360d234d5a7aed0a68e1902e4b458e
    enforceQuota: false
    options:
      name: stashappscodecom-restoresession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:91b6633dd54a85a6e818cf5261dd43b723c81cd38681cf2166e9e695295e12d2
