apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-restoresessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: stashappscodecom-restoresession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:cba733d686b5915101badfdaf6380fb80eb2c642411d99631cde25c034951f31
    enforceQuota: false
    options:
      name: stashappscodecom-restoresession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:3ee328236922c0fb14f0c421bff5d3010f3d26ce2428718deaccbffc79008aa0
