apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: falco.appscode.com
    k8s.io/kind: FalcoEvent
    k8s.io/resource: falcoevents
    k8s.io/version: v1alpha1
  name: falco.appscode.com-v1alpha1-falcoevents
spec:
  resource:
    group: falco.appscode.com
    kind: FalcoEvent
    name: falcoevents
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: falcoappscodecom-falcoevent-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2d98b0bb7e32e44d14837139b6bba7ed59e416f318d72df01005758e73e08bc9
    enforceQuota: false
