apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: ApprovalPolicy
    k8s.io/resource: approvalpolicies
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-approvalpolicies
spec:
  resource:
    group: supervisor.appscode.com
    kind: ApprovalPolicy
    name: approvalpolicies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-approvalpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:36514a82fb9d9fe80b7409f62f476f92c3a39b81d8c7eddd4b2f3217413ecde8
    enforceQuota: false
