apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: ClusterMaintenanceWindow
    k8s.io/resource: clustermaintenancewindows
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-clustermaintenancewindows
spec:
  resource:
    group: supervisor.appscode.com
    kind: ClusterMaintenanceWindow
    name: clustermaintenancewindows
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-clustermaintenancewindow-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:f6e1769b24e878baf0ef7b005b59019eb20862638ec84757c86d02162e71199b
    enforceQuota: false
