apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: ClusterMaintenanceWindow
    k8s.io/resource: clustermaintenancewindows
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-clustermaintenancewindows
spec:
  resource:
    group: supervisor.appscode.com
    kind: ClusterMaintenanceWindow
    name: clustermaintenancewindows
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-clustermaintenancewindow-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:fe872231cbbc368f03a890b70e7e1eae86d3ee62d6dfb7f6d45d4c14faa0fdd0
    enforceQuota: false
