apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: MaintenanceWindow
    k8s.io/resource: maintenancewindows
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-maintenancewindows
spec:
  resource:
    group: supervisor.appscode.com
    kind: MaintenanceWindow
    name: maintenancewindows
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-maintenancewindow-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:ce91fc94dc208d9fae164062098ec3fd985604af2854c717948ab100afad9dc0
    enforceQuota: false
