apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: MaintenanceWindow
    k8s.io/resource: maintenancewindows
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-maintenancewindows
spec:
  resource:
    group: supervisor.appscode.com
    kind: MaintenanceWindow
    name: maintenancewindows
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-maintenancewindow-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:439b0cf9637b5a2ae344351addb7a5b94154bb2d668463b7fd9537f4277a1580
    enforceQuota: false
