apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: MaintenanceWindow
    k8s.io/resource: maintenancewindows
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-maintenancewindows
spec:
  resource:
    group: supervisor.appscode.com
    kind: MaintenanceWindow
    name: maintenancewindows
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-maintenancewindow-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d3d8456c257fefd9b593afe49ad6c9fbbfb48cb383749406581e5e5476784dcc
    enforceQuota: false
