apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: supervisor.appscode.com
    k8s.io/kind: Recommendation
    k8s.io/resource: recommendations
    k8s.io/version: v1alpha1
  name: supervisor.appscode.com-v1alpha1-recommendations
spec:
  resource:
    group: supervisor.appscode.com
    kind: Recommendation
    name: recommendations
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: supervisorappscodecom-recommendation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:853f05317187d0187683013bf1fb494146912d0bb2c4046dedc630a5d3cda2b7
    enforceQuota: false
