apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbforpostgresql.azure.kubedb.com
    k8s.io/kind: FirewallRule
    k8s.io/resource: firewallrules
    k8s.io/version: v1alpha1
  name: dbforpostgresql.azure.kubedb.com-v1alpha1-firewallrules
spec:
  resource:
    group: dbforpostgresql.azure.kubedb.com
    kind: FirewallRule
    name: firewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbforpostgresqlazurekubedbcom-firewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2233c1cb39b5f7e68dd5c4de62df155c9e6ee69791cb1b640f072e17dc77b313
    enforceQuota: false
