apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbforpostgresql.azure.kubedb.com
    k8s.io/kind: FirewallRule
    k8s.io/resource: firewallrules
    k8s.io/version: v1alpha1
  name: dbforpostgresql.azure.kubedb.com-v1alpha1-firewallrules
spec:
  resource:
    group: dbforpostgresql.azure.kubedb.com
    kind: FirewallRule
    name: firewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbforpostgresqlazurekubedbcom-firewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b696b6fd5b08ac98c8ffc3e1919e1ced84b7b42e2011f3a6da90c25088758f91
    enforceQuota: false
