apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbforpostgresql.azure.kubedb.com
    k8s.io/kind: FlexibleServerFirewallRule
    k8s.io/resource: flexibleserverfirewallrules
    k8s.io/version: v1alpha1
  name: dbforpostgresql.azure.kubedb.com-v1alpha1-flexibleserverfirewallrules
spec:
  resource:
    group: dbforpostgresql.azure.kubedb.com
    kind: FlexibleServerFirewallRule
    name: flexibleserverfirewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbforpostgresqlazurekubedbcom-flexibleserverfirewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d586ae97a61d9bac1838526e048f03e886dcb3e2e1a9dd5f4737e1aadc0a53e5
    enforceQuota: false
