apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbforpostgresql.azure.kubedb.com
    k8s.io/kind: Server
    k8s.io/resource: servers
    k8s.io/version: v1alpha1
  name: dbforpostgresql.azure.kubedb.com-v1alpha1-servers
spec:
  resource:
    group: dbforpostgresql.azure.kubedb.com
    kind: Server
    name: servers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbforpostgresqlazurekubedbcom-server-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0748232c84ec5d19970e313414bc5cff3f0c267eb51adbed65419bdaab254bf8
    enforceQuota: false
