apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gcp.kubedb.com
    k8s.io/kind: ProviderConfig
    k8s.io/resource: providerconfigs
    k8s.io/version: v1beta1
  name: gcp.kubedb.com-v1beta1-providerconfigs
spec:
  resource:
    group: gcp.kubedb.com
    kind: ProviderConfig
    name: providerconfigs
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: gcpkubedbcom-providerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:606f51754afd9154e5cd1510beb2c4a2acb8519a4c7a1d25f114f0625ffe1fc3
    enforceQuota: false
