apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: ConnectCluster
    k8s.io/resource: connectclusters
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-connectclusters
spec:
  resource:
    group: kafka.kubedb.com
    kind: ConnectCluster
    name: connectclusters
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-connectcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a52786128a8a3c869fc3708da9f4974e2adfb774b2ea1c75fe43cff04400f042
    enforceQuota: false
