apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: ConnectCluster
    k8s.io/resource: connectclusters
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-connectclusters
spec:
  resource:
    group: kafka.kubedb.com
    kind: ConnectCluster
    name: connectclusters
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-connectcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:b61f9d2706f7d13f02e99177f85f7399d2b438dc7897f628ff926d4359983bda
    enforceQuota: false
