apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: RestProxy
    k8s.io/resource: restproxies
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-restproxies
spec:
  resource:
    group: kafka.kubedb.com
    kind: RestProxy
    name: restproxies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-restproxy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:df51128bd8e1e173ab00f1d84a42eb6b55ae914ad44747eebde33b5bb55f91c9
    enforceQuota: false
