apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: RestProxy
    k8s.io/resource: restproxies
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-restproxies
spec:
  resource:
    group: kafka.kubedb.com
    kind: RestProxy
    name: restproxies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-restproxy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:088404bb7b92b2340d0a4d48ae2532ec9e2583ed04bc3a7d739e913c11c1c60b
    enforceQuota: false
