apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: SchemaRegistry
    k8s.io/resource: schemaregistries
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-schemaregistries
spec:
  resource:
    group: kafka.kubedb.com
    kind: SchemaRegistry
    name: schemaregistries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-schemaregistry-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0f7e2073f7ecd78f1d21faa40e5264f4795ba97944086b42f4bc5bd5594d96d0
    enforceQuota: false
