apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: SchemaRegistry
    k8s.io/resource: schemaregistries
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-schemaregistries
spec:
  resource:
    group: kafka.kubedb.com
    kind: SchemaRegistry
    name: schemaregistries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-schemaregistry-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d8e0b8aadb839fd9600b445b6510ec75521d11d1b7b04641f5cf7c2db342d186
    enforceQuota: false
