apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kafka.kubedb.com
    k8s.io/kind: SchemaRegistry
    k8s.io/resource: schemaregistries
    k8s.io/version: v1alpha1
  name: kafka.kubedb.com-v1alpha1-schemaregistries
spec:
  resource:
    group: kafka.kubedb.com
    kind: SchemaRegistry
    name: schemaregistries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: kafkakubedbcom-schemaregistry-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d306e9a96d84204d3e1e416ef2a17a83f61286d126e395a7028f21f71123bbbc
    enforceQuota: false
