/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/editor/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// EditorRendersGetter has a method to return a EditorRenderInterface.
// A group's client should implement this interface.
type EditorRendersGetter interface {
	EditorRenders() EditorRenderInterface
}

// EditorRenderInterface has methods to work with EditorRender resources.
type EditorRenderInterface interface {
	Create(ctx context.Context, editorRender *v1alpha1.EditorRender, opts v1.CreateOptions) (*v1alpha1.EditorRender, error)
	EditorRenderExpansion
}

// editorRenders implements EditorRenderInterface
type editorRenders struct {
	client rest.Interface
}

// newEditorRenders returns a EditorRenders
func newEditorRenders(c *EditorV1alpha1Client) *editorRenders {
	return &editorRenders{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a editorRender and creates it.  Returns the server's representation of the editorRender, and an error, if there is any.
func (c *editorRenders) Create(ctx context.Context, editorRender *v1alpha1.EditorRender, opts v1.CreateOptions) (result *v1alpha1.EditorRender, err error) {
	result = &v1alpha1.EditorRender{}
	err = c.client.Post().
		Resource("editorrenders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(editorRender).
		Do(ctx).
		Into(result)
	return
}
