/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	editorv1alpha1 "kmodules.xyz/resource-metadata/apis/editor/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "kmodules.xyz/client-go/gentype"
)

// EditorModelsGetter has a method to return a EditorModelInterface.
// A group's client should implement this interface.
type EditorModelsGetter interface {
	EditorModels() EditorModelInterface
}

// EditorModelInterface has methods to work with EditorModel resources.
type EditorModelInterface interface {
	Create(ctx context.Context, editorModel *editorv1alpha1.EditorModel, opts v1.CreateOptions) (*editorv1alpha1.EditorModel, error)
	EditorModelExpansion
}

// editorModels implements EditorModelInterface
type editorModels struct {
	*gentype.Client[*editorv1alpha1.EditorModel]
}

// newEditorModels returns a EditorModels
func newEditorModels(c *EditorV1alpha1Client) *editorModels {
	return &editorModels{
		gentype.NewClient[*editorv1alpha1.EditorModel](
			"editormodels",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *editorv1alpha1.EditorModel { return &editorv1alpha1.EditorModel{} },
		),
	}
}
