/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/editor/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// EditorTemplatesGetter has a method to return a EditorTemplateInterface.
// A group's client should implement this interface.
type EditorTemplatesGetter interface {
	EditorTemplates() EditorTemplateInterface
}

// EditorTemplateInterface has methods to work with EditorTemplate resources.
type EditorTemplateInterface interface {
	Create(ctx context.Context, editorTemplate *v1alpha1.EditorTemplate, opts v1.CreateOptions) (*v1alpha1.EditorTemplate, error)
	EditorTemplateExpansion
}

// editorTemplates implements EditorTemplateInterface
type editorTemplates struct {
	client rest.Interface
}

// newEditorTemplates returns a EditorTemplates
func newEditorTemplates(c *EditorV1alpha1Client) *editorTemplates {
	return &editorTemplates{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a editorTemplate and creates it.  Returns the server's representation of the editorTemplate, and an error, if there is any.
func (c *editorTemplates) Create(ctx context.Context, editorTemplate *v1alpha1.EditorTemplate, opts v1.CreateOptions) (result *v1alpha1.EditorTemplate, err error) {
	result = &v1alpha1.EditorTemplate{}
	err = c.client.Post().
		Resource("editortemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(editorTemplate).
		Do(ctx).
		Into(result)
	return
}
