/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/management/v1alpha1"
)

// FakeProjectQuotas implements ProjectQuotaInterface
type FakeProjectQuotas struct {
	Fake *FakeManagementV1alpha1
}

var projectquotasResource = schema.GroupVersionResource{Group: "management.k8s.appscode.com", Version: "v1alpha1", Resource: "projectquotas"}

var projectquotasKind = schema.GroupVersionKind{Group: "management.k8s.appscode.com", Version: "v1alpha1", Kind: "ProjectQuota"}

// Get takes name of the projectQuota, and returns the corresponding projectQuota object, and an error if there is any.
func (c *FakeProjectQuotas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(projectquotasResource, name), &v1alpha1.ProjectQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectQuota), err
}

// List takes label and field selectors, and returns the list of ProjectQuotas that match those selectors.
func (c *FakeProjectQuotas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectQuotaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(projectquotasResource, projectquotasKind, opts), &v1alpha1.ProjectQuotaList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectQuotaList{ListMeta: obj.(*v1alpha1.ProjectQuotaList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectQuotaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectQuotas.
func (c *FakeProjectQuotas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(projectquotasResource, opts))
}

// Create takes the representation of a projectQuota and creates it.  Returns the server's representation of the projectQuota, and an error, if there is any.
func (c *FakeProjectQuotas) Create(ctx context.Context, projectQuota *v1alpha1.ProjectQuota, opts v1.CreateOptions) (result *v1alpha1.ProjectQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(projectquotasResource, projectQuota), &v1alpha1.ProjectQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectQuota), err
}

// Update takes the representation of a projectQuota and updates it. Returns the server's representation of the projectQuota, and an error, if there is any.
func (c *FakeProjectQuotas) Update(ctx context.Context, projectQuota *v1alpha1.ProjectQuota, opts v1.UpdateOptions) (result *v1alpha1.ProjectQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(projectquotasResource, projectQuota), &v1alpha1.ProjectQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectQuota), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectQuotas) UpdateStatus(ctx context.Context, projectQuota *v1alpha1.ProjectQuota, opts v1.UpdateOptions) (*v1alpha1.ProjectQuota, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(projectquotasResource, "status", projectQuota), &v1alpha1.ProjectQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectQuota), err
}

// Delete takes name of the projectQuota and deletes it. Returns an error if one occurs.
func (c *FakeProjectQuotas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(projectquotasResource, name, opts), &v1alpha1.ProjectQuota{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectQuotas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(projectquotasResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectQuotaList{})
	return err
}

// Patch applies the patch and returns the patched projectQuota.
func (c *FakeProjectQuotas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(projectquotasResource, name, pt, data, subresources...), &v1alpha1.ProjectQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectQuota), err
}
