apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureSystemAssignedIdentity
    k8s.io/resource: azuresystemassignedidentites
    k8s.io/version: v1alpha3
  name: infrastructure.cluster.x-k8s.io-v1alpha3-azuresystemassignedidentites
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureSystemAssignedIdentity
    name: azuresystemassignedidentites
    scope: Namespaced
    version: v1alpha3
  ui:
    editor:
      name: infrastructureclusterxk8sio-azuresystemassignedidentity-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:d9c4469274a5b6af0acfbbaa9c0fc1397f491bc0d66c31e1783128e133c93ae4
    enforceQuota: false
