apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureServicePrincipal
    k8s.io/resource: azureserviceprincipals
    k8s.io/version: v1alpha3
  name: infrastructure.cluster.x-k8s.io-v1alpha3-azureserviceprincipals
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureServicePrincipal
    name: azureserviceprincipals
    scope: Namespaced
    version: v1alpha3
  ui:
    editor:
      name: infrastructureclusterxk8sio-azureserviceprincipal-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:266ef5e274f16c78f97d60d64f9e01d4864eb023ebe92c3f302a12a2a81487c2
    enforceQuota: false
