apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureSystemAssignedIdentity
    k8s.io/resource: azuresystemassignedidentites
    k8s.io/version: v1alpha3
  name: infrastructure.cluster.x-k8s.io-v1alpha3-azuresystemassignedidentites
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureSystemAssignedIdentity
    name: azuresystemassignedidentites
    scope: Namespaced
    version: v1alpha3
  ui:
    editor:
      name: infrastructureclusterxk8sio-azuresystemassignedidentity-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:079b01e9e4c35d797e2883ce53704e6ce9d99e2d11a953e9daa40a195a5698d1
    enforceQuota: false
