apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: status.gatekeeper.sh
    k8s.io/kind: ConstraintPodStatus
    k8s.io/resource: constraintpodstatuses
    k8s.io/version: v1beta1
  name: status.gatekeeper.sh-v1beta1-constraintpodstatuses
spec:
  resource:
    group: status.gatekeeper.sh
    kind: ConstraintPodStatus
    name: constraintpodstatuses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: statusgatekeepersh-constraintpodstatus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cc0eb5cdfe9882e3e9bf21137c3cd9893acca8537df64fd8bffc94f00d2c94a4
    enforceQuota: false
