apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: status.gatekeeper.sh
    k8s.io/kind: ExpansionTemplatePodStatus
    k8s.io/resource: expansiontemplatepodstatuses
    k8s.io/version: v1beta1
  name: status.gatekeeper.sh-v1beta1-expansiontemplatepodstatuses
spec:
  resource:
    group: status.gatekeeper.sh
    kind: ExpansionTemplatePodStatus
    name: expansiontemplatepodstatuses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: statusgatekeepersh-expansiontemplatepodstatus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2798d775f36b85d5301159faf782ad56c4c5c8b4136f2e63cfc05d8ee360d5b3
    enforceQuota: false
