apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: Probe
    k8s.io/resource: probes
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-probes
spec:
  resource:
    group: monitoring.coreos.com
    kind: Probe
    name: probes
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: monitoringcoreoscom-probe-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:840036a5db8890e3324e7e33b5fcb93674bfacccf442e9fa05c2a9f670a5f5e5
    enforceQuota: false
