apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: ThanosRuler
    k8s.io/resource: thanosrulers
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-thanosrulers
spec:
  resource:
    group: monitoring.coreos.com
    kind: ThanosRuler
    name: thanosrulers
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: monitoringcoreoscom-thanosruler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3ef68ae9b79d14f7248a205b069f3659a2027825c7ebd11cefd9a361e47273d1
    enforceQuota: false
