/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
)

// FakeResourceTableDefinitions implements ResourceTableDefinitionInterface
type FakeResourceTableDefinitions struct {
	Fake *FakeMetaV1alpha1
}

var resourcetabledefinitionsResource = schema.GroupVersionResource{Group: "meta.k8s.appscode.com", Version: "v1alpha1", Resource: "resourcetabledefinitions"}

var resourcetabledefinitionsKind = schema.GroupVersionKind{Group: "meta.k8s.appscode.com", Version: "v1alpha1", Kind: "ResourceTableDefinition"}

// Get takes name of the resourceTableDefinition, and returns the corresponding resourceTableDefinition object, and an error if there is any.
func (c *FakeResourceTableDefinitions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceTableDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(resourcetabledefinitionsResource, name), &v1alpha1.ResourceTableDefinition{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceTableDefinition), err
}
