/*
Copyright The Kmodules Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
)

// FakeGraphFinders implements GraphFinderInterface
type FakeGraphFinders struct {
	Fake *FakeMetaV1alpha1
}

var graphfindersResource = schema.GroupVersionResource{Group: "meta.appscode.com", Version: "v1alpha1", Resource: "graphfinders"}

var graphfindersKind = schema.GroupVersionKind{Group: "meta.appscode.com", Version: "v1alpha1", Kind: "GraphFinder"}

// Create takes the representation of a graphFinder and creates it.  Returns the server's representation of the graphFinder, and an error, if there is any.
func (c *FakeGraphFinders) Create(graphFinder *v1alpha1.GraphFinder) (result *v1alpha1.GraphFinder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(graphfindersResource, graphFinder), &v1alpha1.GraphFinder{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GraphFinder), err
}
