apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: ElasticsearchRole
    k8s.io/resource: elasticsearchroles
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-elasticsearchroles
spec:
  resource:
    group: engine.kubevault.com
    kind: ElasticsearchRole
    name: elasticsearchroles
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-elasticsearchrole-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ddb622d8a1bad6ccf1c29cbd90905afd1d388be015bae5c0339e2167993cb526
    enforceQuota: false
