apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: ElasticsearchRole
    k8s.io/resource: elasticsearchroles
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-elasticsearchroles
spec:
  resource:
    group: engine.kubevault.com
    kind: ElasticsearchRole
    name: elasticsearchroles
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-elasticsearchrole-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:341edabb9dc1a8a29ecca6cb611652ac7c96a77636d9956994dd8b681aa0594e
    enforceQuota: false
