apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: MariaDBRole
    k8s.io/resource: mariadbroles
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-mariadbroles
spec:
  resource:
    group: engine.kubevault.com
    kind: MariaDBRole
    name: mariadbroles
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-mariadbrole-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:13295022166d875db3a6c141c84032c2c3ad3589e86bfa149eda4e13cd9b22bd
    enforceQuota: false
