apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: MariaDBRole
    k8s.io/resource: mariadbroles
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-mariadbroles
spec:
  resource:
    group: engine.kubevault.com
    kind: MariaDBRole
    name: mariadbroles
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-mariadbrole-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:255976bac8fec7499b723c02f366bec6340e6f8828cbdbadd70755dba75b3a61
    enforceQuota: false
