apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: SecretEngine
    k8s.io/resource: secretengines
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-secretengines
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/engine.kubevault.com/secretengines.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/engine.kubevault.com/secretengines.png
    type: image/png
  resource:
    group: engine.kubevault.com
    kind: SecretEngine
    name: secretengines
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-secretengine-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:28f0ae4a7397a91f3cb1e28aaaf19c5d5ea0734c923b6116f6e3ed2a7c385f12
    enforceQuota: false
