apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: SecretAccessRequest
    k8s.io/resource: secretaccessrequests
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-secretaccessrequests
spec:
  resource:
    group: engine.kubevault.com
    kind: SecretAccessRequest
    name: secretaccessrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-secretaccessrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ebb3787c736fb769e348b12dd2ff9b47561788886117e45cfc54a851001cbf84
    enforceQuota: false
