apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: SecretEngine
    k8s.io/resource: secretengines
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-secretengines
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/engine.kubevault.com/secretengines.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/engine.kubevault.com/secretengines.png
    type: image/png
  resource:
    group: engine.kubevault.com
    kind: SecretEngine
    name: secretengines
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: enginekubevaultcom-secretengine-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b7b6e1b52e78607b03ea63ad99b6f3d69a0ec8d74bb6c283964b909cb24da58f
    enforceQuota: false
