apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLOutboundFirewallRule
    k8s.io/resource: mssqloutboundfirewallrules
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqloutboundfirewallrules
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLOutboundFirewallRule
    name: mssqloutboundfirewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqloutboundfirewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e68b9826afe6b521ced59050d50f4071bc0b10f3cd59ec8dc19fdc16b6c6f6ed
    enforceQuota: false
