apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLOutboundFirewallRule
    k8s.io/resource: mssqloutboundfirewallrules
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqloutboundfirewallrules
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLOutboundFirewallRule
    name: mssqloutboundfirewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqloutboundfirewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:328c9e35882503922eaa4516aa20a3c312425a4e2cc93476c951d873a6184710
    enforceQuota: false
