apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLManagedInstanceActiveDirectoryAdministrator
    k8s.io/resource: mssqlmanagedinstanceactivedirectoryadministrators
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlmanagedinstanceactivedirectoryadministrators
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLManagedInstanceActiveDirectoryAdministrator
    name: mssqlmanagedinstanceactivedirectoryadministrators
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlmanagedinstanceactivedirectoryadministrator-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:99d7f4b6f02cb1a422e8fe19de900f9565ab90df04140f7f02dfd49cdf74e7bf
    enforceQuota: false
