apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLManagedInstance
    k8s.io/resource: mssqlmanagedinstances
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlmanagedinstances
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLManagedInstance
    name: mssqlmanagedinstances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlmanagedinstance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f86b9a3ee3efea331f8f0151b0cc4d5f085db4a71376e272a37fbb6f4a57be40
    enforceQuota: false
