apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLJobCredential
    k8s.io/resource: mssqljobcredentials
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqljobcredentials
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLJobCredential
    name: mssqljobcredentials
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqljobcredential-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:4237a1c7522ddd6ed6ffe0c956a517efed32255527ea01ee409a894b2949cb86
    enforceQuota: false
