apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLManagedDatabase
    k8s.io/resource: mssqlmanageddatabases
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlmanageddatabases
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLManagedDatabase
    name: mssqlmanageddatabases
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlmanageddatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b5efffdb0f25761d6960e76e0e82d41253f92d06b94ff0b2936251f103399897
    enforceQuota: false
