apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLFailoverGroup
    k8s.io/resource: mssqlfailovergroups
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlfailovergroups
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLFailoverGroup
    name: mssqlfailovergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlfailovergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:bf5ea3fc28af30c8bfbdb96ced80d98648f2d5d5eb3ab2b7dafecfc1a9dcbbac
    enforceQuota: false
