apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLVirtualNetworkRule
    k8s.io/resource: mssqlvirtualnetworkrules
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlvirtualnetworkrules
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLVirtualNetworkRule
    name: mssqlvirtualnetworkrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlvirtualnetworkrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e4746cd3dbc196373e98aa70de8211a7938d6f1fff458707ac792fac97d7d2dd
    enforceQuota: false
