apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLServerMicrosoftSupportAuditingPolicy
    k8s.io/resource: mssqlservermicrosoftsupportauditingpolicies
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlservermicrosoftsupportauditingpolicies
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLServerMicrosoftSupportAuditingPolicy
    name: mssqlservermicrosoftsupportauditingpolicies
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlservermicrosoftsupportauditingpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b5038a4b242be1b2f3437bac934994b51ed222e40a513223016ef162d9859f80
    enforceQuota: false
