apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.azure.kubedb.com
    k8s.io/kind: MSSQLManagedInstanceFailoverGroup
    k8s.io/resource: mssqlmanagedinstancefailovergroups
    k8s.io/version: v1alpha1
  name: sql.azure.kubedb.com-v1alpha1-mssqlmanagedinstancefailovergroups
spec:
  resource:
    group: sql.azure.kubedb.com
    kind: MSSQLManagedInstanceFailoverGroup
    name: mssqlmanagedinstancefailovergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlazurekubedbcom-mssqlmanagedinstancefailovergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ddb5168b54cc736454d18a606a1621db5f16746610e7cb1d00f265547d36fdf9
    enforceQuota: false
