apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kinesis.aws.kubedb.com
    k8s.io/kind: Stream
    k8s.io/resource: streams
    k8s.io/version: v1alpha1
  name: kinesis.aws.kubedb.com-v1alpha1-streams
spec:
  resource:
    group: kinesis.aws.kubedb.com
    kind: Stream
    name: streams
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: kinesisawskubedbcom-stream-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:095d8b82417c27d2401d9c0dc87b6ae2b6f44fe04b58684e5e1160edc3b0b9cc
    enforceQuota: false
