apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: apiextensions.crossplane.io
    k8s.io/kind: Composition
    k8s.io/resource: compositions
    k8s.io/version: v1
  name: apiextensions.crossplane.io-v1-compositions
spec:
  resource:
    group: apiextensions.crossplane.io
    kind: Composition
    name: compositions
    scope: Cluster
    version: v1
  ui:
    editor:
      name: apiextensionscrossplaneio-composition-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3c5ba125ea5b1dca80d2b0178f43fb4d6f7b5986847ab269c74429db97bd2146
    enforceQuota: false
