apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apiextensions.crossplane.io
    k8s.io/kind: CompositionRevision
    k8s.io/resource: compositionrevisions
    k8s.io/version: v1
  name: apiextensions.crossplane.io-v1-compositionrevisions
spec:
  resource:
    group: apiextensions.crossplane.io
    kind: CompositionRevision
    name: compositionrevisions
    scope: Cluster
    version: v1
  ui:
    editor:
      name: apiextensionscrossplaneio-compositionrevision-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:5c3818583ab325f7471e97dd4c0100a09d3bf6f0d19853885fce75d02e99be6d
    enforceQuota: false
