apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apiextensions.crossplane.io
    k8s.io/kind: Composition
    k8s.io/resource: compositions
    k8s.io/version: v1
  name: apiextensions.crossplane.io-v1-compositions
spec:
  resource:
    group: apiextensions.crossplane.io
    kind: Composition
    name: compositions
    scope: Cluster
    version: v1
  ui:
    editor:
      name: apiextensionscrossplaneio-composition-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:0fd4c02596c75a2ab23c1fe9f512ddf7c3dfe9808f4f1ba7996bc5e605842e0a
    enforceQuota: false
