apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apiextensions.crossplane.io
    k8s.io/kind: CompositeResourceDefinition
    k8s.io/resource: compositeresourcedefinitions
    k8s.io/version: v1
  name: apiextensions.crossplane.io-v1-compositeresourcedefinitions
spec:
  resource:
    group: apiextensions.crossplane.io
    kind: CompositeResourceDefinition
    name: compositeresourcedefinitions
    scope: Cluster
    version: v1
  ui:
    editor:
      name: apiextensionscrossplaneio-compositeresourcedefinition-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:90f825c89810add7a6bb0f88713c3187b07f6af670a10be13d46b1f3824b820c
    enforceQuota: false
