apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: BackendLBPolicy
    k8s.io/resource: backendlbpolicies
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-backendlbpolicies
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: BackendLBPolicy
    name: backendlbpolicies
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-backendlbpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a0f2950b27b574211c4cbc282af989c5b9dbb607de93d393eed1d4deaf66f829
    enforceQuota: false
