apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: TCPRoute
    k8s.io/resource: tcproutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-tcproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: TCPRoute
    name: tcproutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-tcproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:861c92cced000f08c6f02c1c926c9c59aee1a8e8a2f2cbba9b58becd9933b76b
    enforceQuota: false
