apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: TCPRoute
    k8s.io/resource: tcproutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-tcproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: TCPRoute
    name: tcproutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-tcproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:38571ba21bf29e6b0dc963e03aad84d2e1d628322cf6532999f106a738e7352b
    enforceQuota: false
