apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: TCPRoute
    k8s.io/resource: tcproutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-tcproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: TCPRoute
    name: tcproutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-tcproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:77191e53d6643458cd16a82327ca616af93822e2c7fa20e4b8d56914092f9b61
    enforceQuota: false
