apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: UDPRoute
    k8s.io/resource: udproutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-udproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: UDPRoute
    name: udproutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-udproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:49764454442087087598dd1ae859a5e04294b52fff5dde11ae91d2dc4aea2517
    enforceQuota: false
