apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: UDPRoute
    k8s.io/resource: udproutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-udproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: UDPRoute
    name: udproutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-udproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:577ee07e12dc8cc984a60fe2b95f1fa2acb424e72ac0df53023bd334f297cc65
    enforceQuota: false
