apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: UDPRoute
    k8s.io/resource: udproutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-udproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: UDPRoute
    name: udproutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-udproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:19cdfcac55d59cdaab64d31159c8860e1cc243c11d068f5547acf0056d53b076
    enforceQuota: false
