apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: schema.kubedb.com
    k8s.io/kind: MariaDBDatabase
    k8s.io/resource: mariadbdatabases
    k8s.io/version: v1alpha1
  name: schema.kubedb.com-v1alpha1-mariadbdatabases
spec:
  resource:
    group: schema.kubedb.com
    kind: MariaDBDatabase
    name: mariadbdatabases
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: schemakubedbcom-mariadbdatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:47beef10c1da714f617dab82e65ebfd7580ab4c7e9bab648d85f10749639851f
    enforceQuota: false
