apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: schema.kubedb.com
    k8s.io/kind: MongoDBDatabase
    k8s.io/resource: mongodbdatabases
    k8s.io/version: v1alpha1
  name: schema.kubedb.com-v1alpha1-mongodbdatabases
spec:
  resource:
    group: schema.kubedb.com
    kind: MongoDBDatabase
    name: mongodbdatabases
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: schemakubedbcom-mongodbdatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:3cd756635b03225c51128e019c12cbcab0dacb9fd88e507531fa5958f4e56674
    enforceQuota: false
