apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: schema.kubedb.com
    k8s.io/kind: MongoDBDatabase
    k8s.io/resource: mongodbdatabases
    k8s.io/version: v1alpha1
  name: schema.kubedb.com-v1alpha1-mongodbdatabases
spec:
  resource:
    group: schema.kubedb.com
    kind: MongoDBDatabase
    name: mongodbdatabases
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: schemakubedbcom-mongodbdatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d7cd3d5d4b20841c70e12b65dce40e6fa4d234dea5e2da4a086602d2d5f6c3d7
    enforceQuota: false
