apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: schema.kubedb.com
    k8s.io/kind: PostgresDatabase
    k8s.io/resource: postgresdatabases
    k8s.io/version: v1alpha1
  name: schema.kubedb.com-v1alpha1-postgresdatabases
spec:
  resource:
    group: schema.kubedb.com
    kind: PostgresDatabase
    name: postgresdatabases
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: schemakubedbcom-postgresdatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:16804f838f159ce57a5b0c2f8b588b8ce2efeb77b5b40dad2524f3ccae1a698e
    enforceQuota: false
