apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: schema.kubedb.com
    k8s.io/kind: PostgresDatabase
    k8s.io/resource: postgresdatabases
    k8s.io/version: v1alpha1
  name: schema.kubedb.com-v1alpha1-postgresdatabases
spec:
  resource:
    group: schema.kubedb.com
    kind: PostgresDatabase
    name: postgresdatabases
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: schemakubedbcom-postgresdatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:bb94b3543181419275d9847306fcbf42b8391fd3f6ae009b59a5fb0665bd2926
    enforceQuota: false
