apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: pkg.crossplane.io
    k8s.io/kind: ControllerConfig
    k8s.io/resource: controllerconfigs
    k8s.io/version: v1alpha1
  name: pkg.crossplane.io-v1alpha1-controllerconfigs
spec:
  resource:
    group: pkg.crossplane.io
    kind: ControllerConfig
    name: controllerconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: pkgcrossplaneio-controllerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:07cad4373cc2383283b354837f2801fabd68fab28ef7bb3c98387a68846b5360
    enforceQuota: false
