apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: mutations.gatekeeper.sh
    k8s.io/kind: AssignMetadata
    k8s.io/resource: assignmetadata
    k8s.io/version: v1
  name: mutations.gatekeeper.sh-v1-assignmetadata
spec:
  resource:
    group: mutations.gatekeeper.sh
    kind: AssignMetadata
    name: assignmetadata
    scope: Cluster
    version: v1
  ui:
    editor:
      name: mutationsgatekeepersh-assignmetadata-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c982c0ae1b164bc356943e114f20a06214fe60814637bce2a28e9646f877c6fb
    enforceQuota: false
