apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: AlertmanagerConfig
    k8s.io/resource: alertmanagerconfigs
    k8s.io/version: v1alpha1
  name: monitoring.coreos.com-v1alpha1-alertmanagerconfigs
spec:
  resource:
    group: monitoring.coreos.com
    kind: AlertmanagerConfig
    name: alertmanagerconfigs
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: monitoringcoreoscom-alertmanagerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1f7dda3459f27f2ea6595eeab8fc123f5bc603cc3ab68b5357bd3cce61f9a2fe
    enforceQuota: false
