/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	managementv1alpha1 "kmodules.xyz/resource-metadata/apis/management/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProjectQuotasGetter has a method to return a ProjectQuotaInterface.
// A group's client should implement this interface.
type ProjectQuotasGetter interface {
	ProjectQuotas() ProjectQuotaInterface
}

// ProjectQuotaInterface has methods to work with ProjectQuota resources.
type ProjectQuotaInterface interface {
	Create(ctx context.Context, projectQuota *managementv1alpha1.ProjectQuota, opts v1.CreateOptions) (*managementv1alpha1.ProjectQuota, error)
	Update(ctx context.Context, projectQuota *managementv1alpha1.ProjectQuota, opts v1.UpdateOptions) (*managementv1alpha1.ProjectQuota, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, projectQuota *managementv1alpha1.ProjectQuota, opts v1.UpdateOptions) (*managementv1alpha1.ProjectQuota, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementv1alpha1.ProjectQuota, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementv1alpha1.ProjectQuotaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementv1alpha1.ProjectQuota, err error)
	ProjectQuotaExpansion
}

// projectQuotas implements ProjectQuotaInterface
type projectQuotas struct {
	*gentype.ClientWithList[*managementv1alpha1.ProjectQuota, *managementv1alpha1.ProjectQuotaList]
}

// newProjectQuotas returns a ProjectQuotas
func newProjectQuotas(c *ManagementV1alpha1Client) *projectQuotas {
	return &projectQuotas{
		gentype.NewClientWithList[*managementv1alpha1.ProjectQuota, *managementv1alpha1.ProjectQuotaList](
			"projectquotas",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementv1alpha1.ProjectQuota { return &managementv1alpha1.ProjectQuota{} },
			func() *managementv1alpha1.ProjectQuotaList { return &managementv1alpha1.ProjectQuotaList{} },
		),
	}
}
