apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: ActiveDirectoryAdministrator
    k8s.io/resource: activedirectoryadministrators
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-activedirectoryadministrators
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: ActiveDirectoryAdministrator
    name: activedirectoryadministrators
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-activedirectoryadministrator-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ff49ae84ae00b427afc2f38039bbe0282c9748d5f235c8d085ebd837309e74b0
    enforceQuota: false
