apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-configurations
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:afa2b68d6c188dbf9c2574fd5e148fb7c495c4dd87dde249e3ebe7ed7c5f7f7c
    enforceQuota: false
