apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-configurations
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0f677ef1fc45dd0b7bd8809e101882a1d996703ff90e376adada021c68da6e70
    enforceQuota: false
