apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: Database
    k8s.io/resource: databases
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-databases
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: Database
    name: databases
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-database-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7a962f2495ec82915e43ee33664850c956011031ec376e8c7a0be9ee60df9ba4
    enforceQuota: false
