apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: Database
    k8s.io/resource: databases
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-databases
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: Database
    name: databases
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-database-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c93829db81c5e3719f75e0ec8fa629f75337b1a39a27795e5fe9807d88f21fd4
    enforceQuota: false
