apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: FirewallRule
    k8s.io/resource: firewallrules
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-firewallrules
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: FirewallRule
    name: firewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-firewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ca40ed22084de4ff02c3ba74d397893587e20ed21c5cf5535b28c9d3bac6c3ea
    enforceQuota: false
