apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: Server
    k8s.io/resource: servers
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-servers
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: Server
    name: servers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-server-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:80fd18b4d8f2c9a6e21fa6ad9cdc4e3b45dfb2e536b8cd505a4e70c54edd68d8
    enforceQuota: false
