apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: VirtualNetworkRule
    k8s.io/resource: virtualnetworkrules
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-virtualnetworkrules
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: VirtualNetworkRule
    name: virtualnetworkrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-virtualnetworkrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4af3e187cb2db734f89e4a877ffd46816ca4fa32d1a91afd3f9e49c63af9958f
    enforceQuota: false
