apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.azure.kubedb.com
    k8s.io/kind: Account
    k8s.io/resource: accounts
    k8s.io/version: v1alpha1
  name: storage.azure.kubedb.com-v1alpha1-accounts
spec:
  resource:
    group: storage.azure.kubedb.com
    kind: Account
    name: accounts
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: storageazurekubedbcom-account-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:fa1d1292c9d62a0e3f507666784f72d561fe7fc357df1d026a6247b757e124b8
    enforceQuota: false
