apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.azure.kubedb.com
    k8s.io/kind: Container
    k8s.io/resource: containers
    k8s.io/version: v1alpha1
  name: storage.azure.kubedb.com-v1alpha1-containers
spec:
  resource:
    group: storage.azure.kubedb.com
    kind: Container
    name: containers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: storageazurekubedbcom-container-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a32bc0085a73500616cc9a78706bb9fee4f274f29609ceebe5afcb47f601e613
    enforceQuota: false
