apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.azure.kubedb.com
    k8s.io/kind: Container
    k8s.io/resource: containers
    k8s.io/version: v1alpha1
  name: storage.azure.kubedb.com-v1alpha1-containers
spec:
  resource:
    group: storage.azure.kubedb.com
    kind: Container
    name: containers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: storageazurekubedbcom-container-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e249e4868c9e97d50043d4c41c1fd216b59d98cbdcf496a7f427b8b7f051aa9a
    enforceQuota: false
