apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: storage.azure.kubedb.com
    k8s.io/kind: Container
    k8s.io/resource: containers
    k8s.io/version: v1alpha1
  name: storage.azure.kubedb.com-v1alpha1-containers
spec:
  resource:
    group: storage.azure.kubedb.com
    kind: Container
    name: containers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: storageazurekubedbcom-container-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e9e99e04e394207d804f8cd303e0efb75ad2aaaca620f6433e649ebf16802da3
    enforceQuota: false
