apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: archiver.kubedb.com
    k8s.io/kind: MariaDBArchiver
    k8s.io/resource: mariadbarchivers
    k8s.io/version: v1alpha1
  name: archiver.kubedb.com-v1alpha1-mariadbarchivers
spec:
  resource:
    group: archiver.kubedb.com
    kind: MariaDBArchiver
    name: mariadbarchivers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: archiverkubedbcom-mariadbarchiver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9b2b49f60836070497fd1c944835f07030c5713d0570d4cc59d0701539744018
    enforceQuota: false
