apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: archiver.kubedb.com
    k8s.io/kind: MSSQLServerArchiver
    k8s.io/resource: mssqlserverarchivers
    k8s.io/version: v1alpha1
  name: archiver.kubedb.com-v1alpha1-mssqlserverarchivers
spec:
  resource:
    group: archiver.kubedb.com
    kind: MSSQLServerArchiver
    name: mssqlserverarchivers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: archiverkubedbcom-mssqlserverarchiver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:913b85101534131b1dd33687bb201f4d0a1ebdb7c4e9d0fad0d814b36ec2e785
    enforceQuota: false
