apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: archiver.kubedb.com
    k8s.io/kind: MySQLArchiver
    k8s.io/resource: mysqlarchivers
    k8s.io/version: v1alpha1
  name: archiver.kubedb.com-v1alpha1-mysqlarchivers
spec:
  resource:
    group: archiver.kubedb.com
    kind: MySQLArchiver
    name: mysqlarchivers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: archiverkubedbcom-mysqlarchiver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:40f0feee2caab17c057e95b4d4ce8b5513dbe5e21a6d0d0e44955523c98a57c4
    enforceQuota: false
