apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: archiver.kubedb.com
    k8s.io/kind: MySQLArchiver
    k8s.io/resource: mysqlarchivers
    k8s.io/version: v1alpha1
  name: archiver.kubedb.com-v1alpha1-mysqlarchivers
spec:
  resource:
    group: archiver.kubedb.com
    kind: MySQLArchiver
    name: mysqlarchivers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: archiverkubedbcom-mysqlarchiver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b51372b3454db97f60fe7737d608a5502db63d9456f5f6ed61ba0d5bd4174405
    enforceQuota: false
