apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: archiver.kubedb.com
    k8s.io/kind: PostgresArchiver
    k8s.io/resource: postgresarchivers
    k8s.io/version: v1alpha1
  name: archiver.kubedb.com-v1alpha1-postgresarchivers
spec:
  resource:
    group: archiver.kubedb.com
    kind: PostgresArchiver
    name: postgresarchivers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: archiverkubedbcom-postgresarchiver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:320129dee8c356863de282b21328ea515cb4233e8b37fc172b00bf7d665d1e1c
    enforceQuota: false
