apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: GlobalTable
    k8s.io/resource: globaltables
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-globaltables
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: GlobalTable
    name: globaltables
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-globaltable-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f9c535c79462c944038cf681dff5562640435acd5d1614076501eb3cc4abfa93
    enforceQuota: false
