apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: KinesisStreamingDestination
    k8s.io/resource: kinesisstreamingdestinations
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-kinesisstreamingdestinations
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: KinesisStreamingDestination
    name: kinesisstreamingdestinations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-kinesisstreamingdestination-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:153762836e1259d58d52b58e2e80ae3c1f30ba52d6914b12416213753ef083ba
    enforceQuota: false
