apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: TableReplica
    k8s.io/resource: tablereplicas
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-tablereplicas
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: TableReplica
    name: tablereplicas
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-tablereplica-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:d60b0305662f9c1f5b3ac62207d428d0f310de34e065bd770f4b54b2b376274a
    enforceQuota: false
