apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: TableReplica
    k8s.io/resource: tablereplicas
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-tablereplicas
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: TableReplica
    name: tablereplicas
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-tablereplica-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e17205b6f5d8b8d2a7de9c062150bcaf04cb9c0fd031691ba20eb9ec71a7e31b
    enforceQuota: false
