apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: Table
    k8s.io/resource: tables
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-tables
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: Table
    name: tables
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-table-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f6e261c6c514c9f1bc779dded73dd249f1d62f265ab369b69e47df0ca62e27a8
    enforceQuota: false
