apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: TableItem
    k8s.io/resource: tableitems
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-tableitems
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: TableItem
    name: tableitems
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-tableitem-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4f23c9ad11373cd1f41e9ee147b04be15d99404ba9474cd02c516593b6ef69db
    enforceQuota: false
