apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: TableItem
    k8s.io/resource: tableitems
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-tableitems
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: TableItem
    name: tableitems
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-tableitem-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:84260f304f91d65272501a3da86aaaf6bcd24171a933be8eb2d72a4b22a2eddb
    enforceQuota: false
