apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dynamodb.aws.kubedb.com
    k8s.io/kind: Tag
    k8s.io/resource: tags
    k8s.io/version: v1alpha1
  name: dynamodb.aws.kubedb.com-v1alpha1-tags
spec:
  resource:
    group: dynamodb.aws.kubedb.com
    kind: Tag
    name: tags
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dynamodbawskubedbcom-tag-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:907d52876b3092db9a851a2ede122f162797a3ae8d4a339eeb48032611100793
    enforceQuota: false
