apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureMachine
    k8s.io/resource: azuremachines
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-azuremachines
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureMachine
    name: azuremachines
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-azuremachine-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:60046a1e6fca19041c6c0fec495549fa14372c76e9b929b38a505a68cf85710b
    enforceQuota: false
