apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureClusterTemplate
    k8s.io/resource: azureclustertemplates
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-azureclustertemplates
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureClusterTemplate
    name: azureclustertemplates
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-azureclustertemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:59a5b4f9a5351e4f7b4c80f0f6eaf80fbef27b1031c8b5c8dd4b6c9583abf1a8
    enforceQuota: false
