apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureManagedMachinePool
    k8s.io/resource: azuremanagedmachinepools
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-azuremanagedmachinepools
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureManagedMachinePool
    name: azuremanagedmachinepools
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-azuremanagedmachinepool-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b6d0e4197cd8696686e6d6a9f20da02ce0c64c5627e3dc6a3135482cd17570f9
    enforceQuota: false
