apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AzureMachineTemplate
    k8s.io/resource: azuremachinetemplates
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-azuremachinetemplates
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureMachineTemplate
    name: azuremachinetemplates
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-azuremachinetemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c47ab3bc00e779fe1cc39b606a4871d8f9f5e6410c071438afcf4e3d1296a323
    enforceQuota: false
