apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: GCPManagedControlPlane
    k8s.io/resource: gcpmanagedcontrolplanes
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-gcpmanagedcontrolplanes
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: GCPManagedControlPlane
    name: gcpmanagedcontrolplanes
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-gcpmanagedcontrolplane-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9b93101086716e25321d15f7c9cd8f35cceb2e6abe3f1e758a619683f1c3881f
    enforceQuota: false
