apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: GCPManagedCluster
    k8s.io/resource: gcpmanagedclusters
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-gcpmanagedclusters
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: GCPManagedCluster
    name: gcpmanagedclusters
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-gcpmanagedcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:130bded4d88ea9f6a96440f4a621eeb2026f4feb42ae733d7b90fc0af58cd866
    enforceQuota: false
