apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: GCPManagedMachinePool
    k8s.io/resource: gcpmanagedmachinepools
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-gcpmanagedmachinepools
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: GCPManagedMachinePool
    name: gcpmanagedmachinepools
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-gcpmanagedmachinepool-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1858017cbb85c86053dfc36938797849c376c6c4b53ebb0f3c6069663bc21272
    enforceQuota: false
