apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: GCPManagedCluster
    k8s.io/resource: gcpmanagedclusters
    k8s.io/version: v1beta1
  name: infrastructure.cluster.x-k8s.io-v1beta1-gcpmanagedclusters
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: GCPManagedCluster
    name: gcpmanagedclusters
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: infrastructureclusterxk8sio-gcpmanagedcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5d6fe0d378d2b82af2a618c10d1c2614274152aad2ee3f9dbeb3cd797a335d73
    enforceQuota: false
