apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: Binding
    k8s.io/resource: bindings
    k8s.io/version: v1
  name: core-v1-bindings
spec:
  resource:
    group: ""
    kind: Binding
    name: bindings
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-binding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:70306475ab2ad5e01c00f2334d56df457eb84610fcdbc4b5ff6ea22016ddd6f7
    enforceQuota: false
