apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: Binding
    k8s.io/resource: bindings
    k8s.io/version: v1
  name: core-v1-bindings
spec:
  resource:
    group: ""
    kind: Binding
    name: bindings
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-binding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9b56cbd604222d303d6febeb6d2972d31072134a6339769b892fe06573b6aa99
    enforceQuota: false
