apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Binding
    k8s.io/resource: bindings
    k8s.io/version: v1
  name: core-v1-bindings
spec:
  resource:
    group: ""
    kind: Binding
    name: bindings
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-binding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f6cb5815e420e6d6c16d405ca9c30e0b28445b55b7a2880ccdae8d9dd28a9b58
    enforceQuota: false
