apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: ComponentStatus
    k8s.io/resource: componentstatuses
    k8s.io/version: v1
  name: core-v1-componentstatuses
spec:
  resource:
    group: ""
    kind: ComponentStatus
    name: componentstatuses
    scope: Cluster
    version: v1
  ui:
    editor:
      name: core-componentstatus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:972e1c811128fe39e5bbebaefe8479f5cc29a762be8990e4f713dfe735cde97f
    enforceQuota: false
