apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: ComponentStatus
    k8s.io/resource: componentstatuses
    k8s.io/version: v1
  name: core-v1-componentstatuses
spec:
  resource:
    group: ""
    kind: ComponentStatus
    name: componentstatuses
    scope: Cluster
    version: v1
  ui:
    editor:
      name: core-componentstatus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9f0078264226a9b899d2c6f61eec4cdbfc192db281924955753578a2f795e85d
    enforceQuota: false
