apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: ConfigMap
    k8s.io/resource: configmaps
    k8s.io/version: v1
  name: core-v1-configmaps
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/configmaps.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/configmaps.png
    type: image/png
  resource:
    group: ""
    kind: ConfigMap
    name: configmaps
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-configmap-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:23933deff68409355ab0b8d07ea86f9e7db6a523d1d3583291b5f39697f4142c
    enforceQuota: false
