apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: Endpoints
    k8s.io/resource: endpoints
    k8s.io/version: v1
  name: core-v1-endpoints
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/endpoints.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/endpoints.png
    type: image/png
  resource:
    group: ""
    kind: Endpoints
    name: endpoints
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-endpoints-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9c64691477d0b3fde2801a0f3d1378a71a5692ef214d15e93877e1b66012a5f9
    enforceQuota: false
