apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: Endpoints
    k8s.io/resource: endpoints
    k8s.io/version: v1
  name: core-v1-endpoints
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/endpoints.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/endpoints.png
    type: image/png
  resource:
    group: ""
    kind: Endpoints
    name: endpoints
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-endpoints-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ce58397c829ec8c11f993df2a43c464b1b8a8d4041b01127c5782f24c2fcf102
    enforceQuota: false
