apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: EphemeralContainers
    k8s.io/resource: ephemeralcontainers
    k8s.io/version: v1
  name: core-v1-ephemeralcontainers
spec:
  resource:
    group: ""
    kind: EphemeralContainers
    name: ephemeralcontainers
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-ephemeralcontainers-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:fad89577e9abf4bf7f6a8012336eaefd2dc4ef6fd6e88c17fb579d8b9429a1e9
    enforceQuota: false
