apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: EphemeralContainers
    k8s.io/resource: ephemeralcontainers
    k8s.io/version: v1
  name: core-v1-ephemeralcontainers
spec:
  resource:
    group: ""
    kind: EphemeralContainers
    name: ephemeralcontainers
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-ephemeralcontainers-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:15bf01b011d73cc80d6c1c7802fc2c745197f1fe88d1c168f1f0fb8d9217c6c8
    enforceQuota: false
