apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: EphemeralContainers
    k8s.io/resource: ephemeralcontainers
    k8s.io/version: v1
  name: core-v1-ephemeralcontainers
spec:
  resource:
    group: ""
    kind: EphemeralContainers
    name: ephemeralcontainers
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-ephemeralcontainers-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:473bd18b7efc400c57bc9e83f3918e82b294f06ea08efceebdf2a5ed59219b40
    enforceQuota: false
