apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: Event
    k8s.io/resource: events
    k8s.io/version: v1
  name: core-v1-events
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/events.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/events.png
    type: image/png
  resource:
    group: ""
    kind: Event
    name: events
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-event-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f041baa6d7dd86fca2627c1f64a4dd6215276ffe72c943e25774cb9280ab27b4
    enforceQuota: false
