apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: PersistentVolumeClaim
    k8s.io/resource: persistentvolumeclaims
    k8s.io/version: v1
  name: core-v1-persistentvolumeclaims
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/persistentvolumeclaims.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/persistentvolumeclaims.png
    type: image/png
  resource:
    group: ""
    kind: PersistentVolumeClaim
    name: persistentvolumeclaims
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-persistentvolumeclaim-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:dad07f4dc728e8d650a4ae5f3422da5759b84f5c0086d66dcffd052367d00953
    enforceQuota: false
