apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: PersistentVolume
    k8s.io/resource: persistentvolumes
    k8s.io/version: v1
  name: core-v1-persistentvolumes
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/persistentvolumes.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/persistentvolumes.png
    type: image/png
  resource:
    group: ""
    kind: PersistentVolume
    name: persistentvolumes
    scope: Cluster
    version: v1
  ui:
    editor:
      name: core-persistentvolume-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:44d9a8a042a24d8eee05f021d3f9e69b1abef15b22b78066836f4ff3d7e57c3c
    enforceQuota: false
