apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: Pod
    k8s.io/resource: pods
    k8s.io/version: v1
  name: core-v1-pods
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/pods.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/pods.png
    type: image/png
  resource:
    group: ""
    kind: Pod
    name: pods
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-pod-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8f90e6b27c8215f0922020f948dbd68a4c635f96b6b678d62fed527509188e24
    enforceQuota: false
