apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: PodStatusResult
    k8s.io/resource: podstatusresults
    k8s.io/version: v1
  name: core-v1-podstatusresults
spec:
  resource:
    group: ""
    kind: PodStatusResult
    name: podstatusresults
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-podstatusresult-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0fb5f4d15942d527ea1bd8eb6ba5b3b3b5f6226e57a77d7210b7c4ab5953b5e3
    enforceQuota: false
