apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: RangeAllocation
    k8s.io/resource: rangeallocations
    k8s.io/version: v1
  name: core-v1-rangeallocations
spec:
  resource:
    group: ""
    kind: RangeAllocation
    name: rangeallocations
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-rangeallocation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0a1b22856db0de0e046b3a724881f0db30993c93e21eac4acaf5b0058545ccf8
    enforceQuota: false
