apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: RangeAllocation
    k8s.io/resource: rangeallocations
    k8s.io/version: v1
  name: core-v1-rangeallocations
spec:
  resource:
    group: ""
    kind: RangeAllocation
    name: rangeallocations
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-rangeallocation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:39ee1b9fdeb0d79aebee1d397931ce13e47ead85638a210a1f821e810b3c7365
    enforceQuota: false
