apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: RangeAllocation
    k8s.io/resource: rangeallocations
    k8s.io/version: v1
  name: core-v1-rangeallocations
spec:
  resource:
    group: ""
    kind: RangeAllocation
    name: rangeallocations
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-rangeallocation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3a085072e2b5d6159df31953625f70ca0b6c5361d288bb41d201146638b7e762
    enforceQuota: false
