apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: ResourceQuota
    k8s.io/resource: resourcequotas
    k8s.io/version: v1
  name: core-v1-resourcequotas
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/resourcequotas.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/resourcequotas.png
    type: image/png
  resource:
    group: ""
    kind: ResourceQuota
    name: resourcequotas
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-resourcequota-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7d02c405ac803e7a214b25465ea800040bb2cc4c871daa8aef4fe3bc3d69ff32
    enforceQuota: false
