apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: ResourceQuota
    k8s.io/resource: resourcequotas
    k8s.io/version: v1
  name: core-v1-resourcequotas
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/resourcequotas.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/resourcequotas.png
    type: image/png
  resource:
    group: ""
    kind: ResourceQuota
    name: resourcequotas
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: core-resourcequota-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:413be37065a8aeaca7c5b2b8021d4b4f2546348f8ae0121f90917291d29455ab
    enforceQuota: false
