//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	releasesv1alpha1 "x-helm.dev/apimachinery/apis/releases/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EditorTemplate) DeepCopyInto(out *EditorTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(EditorTemplateRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(EditorTemplateResponse)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EditorTemplate.
func (in *EditorTemplate) DeepCopy() *EditorTemplate {
	if in == nil {
		return nil
	}
	out := new(EditorTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EditorTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EditorTemplateRequest) DeepCopyInto(out *EditorTemplateRequest) {
	*out = *in
	out.ModelMetadata = in.ModelMetadata
	if in.ChartRef != nil {
		in, out := &in.ChartRef, &out.ChartRef
		*out = new(releasesv1alpha1.ChartSourceFlatRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EditorTemplateRequest.
func (in *EditorTemplateRequest) DeepCopy() *EditorTemplateRequest {
	if in == nil {
		return nil
	}
	out := new(EditorTemplateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EditorTemplateResource) DeepCopyInto(out *EditorTemplateResource) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EditorTemplateResource.
func (in *EditorTemplateResource) DeepCopy() *EditorTemplateResource {
	if in == nil {
		return nil
	}
	out := new(EditorTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EditorTemplateResponse) DeepCopyInto(out *EditorTemplateResponse) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]EditorTemplateResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EditorTemplateResponse.
func (in *EditorTemplateResponse) DeepCopy() *EditorTemplateResponse {
	if in == nil {
		return nil
	}
	out := new(EditorTemplateResponse)
	in.DeepCopyInto(out)
	return out
}
