apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AWSClusterStaticIdentity
    k8s.io/resource: awsclusterstaticidentities
    k8s.io/version: v1beta2
  name: infrastructure.cluster.x-k8s.io-v1beta2-awsclusterstaticidentities
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AWSClusterStaticIdentity
    name: awsclusterstaticidentities
    scope: Cluster
    version: v1beta2
  ui:
    editor:
      name: infrastructureclusterxk8sio-awsclusterstaticidentity-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6769a2668f29ef1eb0c41f41f014e15f8eb2d0f5576c14616fa89a440af5ca70
    enforceQuota: false
