apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AWSClusterTemplate
    k8s.io/resource: awsclustertemplates
    k8s.io/version: v1beta2
  name: infrastructure.cluster.x-k8s.io-v1beta2-awsclustertemplates
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AWSClusterTemplate
    name: awsclustertemplates
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: infrastructureclusterxk8sio-awsclustertemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:138b543db4072f9f4628e050876cefd3c36509bac54f514f084e85c974b8d839
    enforceQuota: false
