apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AWSClusterRoleIdentity
    k8s.io/resource: awsclusterroleidentities
    k8s.io/version: v1beta2
  name: infrastructure.cluster.x-k8s.io-v1beta2-awsclusterroleidentities
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AWSClusterRoleIdentity
    name: awsclusterroleidentities
    scope: Cluster
    version: v1beta2
  ui:
    editor:
      name: infrastructureclusterxk8sio-awsclusterroleidentity-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:284b3d182f63cdfcc2f18eea6bfae2b4ea712616ae615cf8c5c5b0ce7f73cbc2
    enforceQuota: false
