apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: infrastructure.cluster.x-k8s.io
    k8s.io/kind: AWSFargateProfile
    k8s.io/resource: awsfargateprofiles
    k8s.io/version: v1beta2
  name: infrastructure.cluster.x-k8s.io-v1beta2-awsfargateprofiles
spec:
  resource:
    group: infrastructure.cluster.x-k8s.io
    kind: AWSFargateProfile
    name: awsfargateprofiles
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: infrastructureclusterxk8sio-awsfargateprofile-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d540164d1b228dce75c0a75f2c48b645f012fd5cb3784a01dc3e584b5442c503
    enforceQuota: false
