apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: Deployment
    k8s.io/resource: deployments
    k8s.io/version: v1beta1
  name: extensions-v1beta1-deployments
spec:
  resource:
    group: extensions
    kind: Deployment
    name: deployments
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-deployment-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d3eff41666a293c9f5e9d284b8b0969c49e2c808fb0337d99765fa5f68ec1024
    enforceQuota: false
