apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: extensions
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1beta1
  name: extensions-v1beta1-ingresses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/extensions/ingresses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/extensions/ingresses.png
    type: image/png
  resource:
    group: extensions
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-ingress-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c1c9b8b39a0dd9917bda6969b4d02576df0e6b66fa7049582a5d71d745f6925f
    enforceQuota: false
