apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: NetworkPolicy
    k8s.io/resource: networkpolicies
    k8s.io/version: v1beta1
  name: extensions-v1beta1-networkpolicies
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/extensions/networkpolicies.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/extensions/networkpolicies.png
    type: image/png
  resource:
    group: extensions
    kind: NetworkPolicy
    name: networkpolicies
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-networkpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:10a5921235f8224711cdcbbf4c97b1ed24c515c2b5f44824cd91d498514cc1b2
    enforceQuota: false
