apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: extensions
    k8s.io/kind: NetworkPolicy
    k8s.io/resource: networkpolicies
    k8s.io/version: v1beta1
  name: extensions-v1beta1-networkpolicies
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/extensions/networkpolicies.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/extensions/networkpolicies.png
    type: image/png
  resource:
    group: extensions
    kind: NetworkPolicy
    name: networkpolicies
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-networkpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:facec1ade4fd041db229bc220673bace4b5b3f6e2702d43f2b24ced284874a64
    enforceQuota: false
