apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: extensions
    k8s.io/kind: ReplicaSet
    k8s.io/resource: replicasets
    k8s.io/version: v1beta1
  name: extensions-v1beta1-replicasets
spec:
  resource:
    group: extensions
    kind: ReplicaSet
    name: replicasets
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-replicaset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:c8977a151ef0346bb83cbf28d3023b3f09287dd945b94ff69ac78daf20bce0e2
    enforceQuota: false
