apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: extensions
    k8s.io/kind: ReplicaSet
    k8s.io/resource: replicasets
    k8s.io/version: v1beta1
  name: extensions-v1beta1-replicasets
spec:
  resource:
    group: extensions
    kind: ReplicaSet
    name: replicasets
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-replicaset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:14343b6ba456336e167048dc9258fd033d2a1e0d29465ef4fc451f1c26238cea
    enforceQuota: false
