apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.k8s.io
    k8s.io/kind: VerticalPodAutoscalerCheckpoint
    k8s.io/resource: verticalpodautoscalercheckpoints
    k8s.io/version: v1
  name: autoscaling.k8s.io-v1-verticalpodautoscalercheckpoints
spec:
  resource:
    group: autoscaling.k8s.io
    kind: VerticalPodAutoscalerCheckpoint
    name: verticalpodautoscalercheckpoints
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: autoscalingk8sio-verticalpodautoscalercheckpoint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:0910ccf41b494b8d150c92e80d4d24804d628cf6384fe5400faf3685d847b85f
    enforceQuota: false
