apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: helm.toolkit.fluxcd.io
    k8s.io/kind: HelmRelease
    k8s.io/resource: helmreleases
    k8s.io/version: v2
  name: helm.toolkit.fluxcd.io-v2-helmreleases
spec:
  resource:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: helmreleases
    scope: Namespaced
    version: v2
  ui:
    editor:
      name: helmtoolkitfluxcdio-helmrelease-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:78817aaed71b5bb6b11413bc78150a5e1ade99efc3a34994c0763334dc8147d7
    enforceQuota: false
