apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: authentication.k8s.appscode.com
    k8s.io/kind: User
    k8s.io/resource: users
    k8s.io/version: v1alpha1
  name: authentication.k8s.appscode.com-v1alpha1-users
spec:
  resource:
    group: authentication.k8s.appscode.com
    kind: User
    name: users
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: authenticationk8sappscodecom-user-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:d1545e4b0167fd75fdf90494e1fdfa56e81ae2edbb8a8dcf2729b2067f3aded4
    enforceQuota: false
