apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: authentication.k8s.appscode.com
    k8s.io/kind: User
    k8s.io/resource: users
    k8s.io/version: v1alpha1
  name: authentication.k8s.appscode.com-v1alpha1-users
spec:
  resource:
    group: authentication.k8s.appscode.com
    kind: User
    name: users
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: authenticationk8sappscodecom-user-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1f9946b45ed08ae94f832fd1daf1c56d49a1a6a0a759555ca9265dd97e7d8d23
    enforceQuota: false
