apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ops.kubevault.com
    k8s.io/kind: VaultOpsRequest
    k8s.io/resource: vaultopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubevault.com-v1alpha1-vaultopsrequests
spec:
  resource:
    group: ops.kubevault.com
    kind: VaultOpsRequest
    name: vaultopsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubevaultcom-vaultopsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:70d4eefac652d43e5ca67f95d294f644a60bc60a915b758c4fa311651a3443e8
    enforceQuota: false
