apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ops.kubevault.com
    k8s.io/kind: VaultOpsRequest
    k8s.io/resource: vaultopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubevault.com-v1alpha1-vaultopsrequests
spec:
  resource:
    group: ops.kubevault.com
    kind: VaultOpsRequest
    name: vaultopsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubevaultcom-vaultopsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:eec5f9ac3243239e86974cd3b4f2d7802734b8025ca97ddc7e8ad91704ba14b2
    enforceQuota: false
