apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: pkg.crossplane.io
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1
  name: pkg.crossplane.io-v1-configurations
spec:
  resource:
    group: pkg.crossplane.io
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1
  ui:
    editor:
      name: pkgcrossplaneio-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5531a3d21782db7dfc488b2debd84b0f272a28f49b309210b59d187d5617d457
    enforceQuota: false
