apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: pkg.crossplane.io
    k8s.io/kind: Provider
    k8s.io/resource: providers
    k8s.io/version: v1
  name: pkg.crossplane.io-v1-providers
spec:
  resource:
    group: pkg.crossplane.io
    kind: Provider
    name: providers
    scope: Cluster
    version: v1
  ui:
    editor:
      name: pkgcrossplaneio-provider-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1b2f241d4d856466d5be0da2edafa75036545404b990cd15bc3c52b9d96b9026
    enforceQuota: false
