apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: pkg.crossplane.io
    k8s.io/kind: ProviderRevision
    k8s.io/resource: providerrevisions
    k8s.io/version: v1
  name: pkg.crossplane.io-v1-providerrevisions
spec:
  resource:
    group: pkg.crossplane.io
    kind: ProviderRevision
    name: providerrevisions
    scope: Cluster
    version: v1
  ui:
    editor:
      name: pkgcrossplaneio-providerrevision-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:c46b8d8c074dc08dffe5bbdf3d12b35d82dd51f2a458ea67edcc464cbc52e6c7
    enforceQuota: false
