apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterParameterGroup
    k8s.io/resource: clusterparametergroups
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusterparametergroups
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterParameterGroup
    name: clusterparametergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusterparametergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:353df1bca8ae79665910134ed8383cf66ac43346054aa2a52ae6ca806cfb8935
    enforceQuota: false
