apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterParameterGroup
    k8s.io/resource: clusterparametergroups
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusterparametergroups
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterParameterGroup
    name: clusterparametergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusterparametergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9d16f0e9f1161b319d773e47de75b5ca3cbc62a6fa9186ce48381e5ad18e4cd7
    enforceQuota: false
