apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterEndpoint
    k8s.io/resource: clusterendpoints
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusterendpoints
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterEndpoint
    name: clusterendpoints
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusterendpoint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4139d7459d61539d4dc53bdf067f34e99b74f7289687eef4fa1401d189850480
    enforceQuota: false
