apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterEndpoint
    k8s.io/resource: clusterendpoints
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusterendpoints
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterEndpoint
    name: clusterendpoints
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusterendpoint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d5dabc5c913533027630a79cc89d7e07b1e64169723193b14951463d6ada5d12
    enforceQuota: false
