apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterActivityStream
    k8s.io/resource: clusteractivitystreams
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusteractivitystreams
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterActivityStream
    name: clusteractivitystreams
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusteractivitystream-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ba5ddc1b7b14c2c1c0d1d7f7f3c894120a7390899b44de6c371d43d0ccd6d574
    enforceQuota: false
