apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterInstance
    k8s.io/resource: clusterinstances
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusterinstances
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterInstance
    name: clusterinstances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusterinstance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8dc4f3b2e5922040b3b99b2dbbbafb70d669a6763ba79deff89431a76050e3c5
    enforceQuota: false
