apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ClusterEndpoint
    k8s.io/resource: clusterendpoints
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-clusterendpoints
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ClusterEndpoint
    name: clusterendpoints
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-clusterendpoint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0dde38f1811a18f9b954eeb7d3447b47f5640dd7fabb7b7a98fcf1fb6d9e1c28
    enforceQuota: false
