apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: EventSubscription
    k8s.io/resource: eventsubscriptions
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-eventsubscriptions
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: EventSubscription
    name: eventsubscriptions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-eventsubscription-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ab316f347b1c3ab0f8d74245e32bc4964c93a4b196040a3e66bcb8259f71bf0e
    enforceQuota: false
