apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: GlobalCluster
    k8s.io/resource: globalclusters
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-globalclusters
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: GlobalCluster
    name: globalclusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-globalcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:518dba6aab3e3ffa848f3abd78a665971e3aab53a57836345e9347eb2f203231
    enforceQuota: false
