apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: GlobalCluster
    k8s.io/resource: globalclusters
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-globalclusters
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: GlobalCluster
    name: globalclusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-globalcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:68f6f1fbe7075ede1c3ceb28db701f1aaa18195992edf8c70278f0f5831babcc
    enforceQuota: false
