apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: ParameterGroup
    k8s.io/resource: parametergroups
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-parametergroups
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: ParameterGroup
    name: parametergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-parametergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9bca4b0b985db82bc1c342ddad79b98cbe83e5e34d4640e57d6a01b0ca3da7f3
    enforceQuota: false
