apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: Proxy
    k8s.io/resource: proxies
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-proxies
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: Proxy
    name: proxies
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-proxy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8ee78cd5be87fd360ad16c9cde97c2a66e54382b37ac0527b179906e5fd9186c
    enforceQuota: false
