apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: Proxy
    k8s.io/resource: proxies
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-proxies
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: Proxy
    name: proxies
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-proxy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:31766b11c74c2f3234c8e7257da7585a18f149627a68f5cef31e48e74001ae4e
    enforceQuota: false
