apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: rds.aws.kubedb.com
    k8s.io/kind: Snapshot
    k8s.io/resource: snapshots
    k8s.io/version: v1alpha1
  name: rds.aws.kubedb.com-v1alpha1-snapshots
spec:
  resource:
    group: rds.aws.kubedb.com
    kind: Snapshot
    name: snapshots
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: rdsawskubedbcom-snapshot-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:4dc6e576efc2d46a4dae1153b47535d56ae8e7e5d66a313a9aa1ddf7111fd079
    enforceQuota: false
