apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: helm.toolkit.fluxcd.io
    k8s.io/kind: HelmRelease
    k8s.io/resource: helmreleases
    k8s.io/version: v2beta2
  name: helm.toolkit.fluxcd.io-v2beta2-helmreleases
spec:
  resource:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: helmreleases
    scope: Namespaced
    version: v2beta2
  ui:
    editor:
      name: helmtoolkitfluxcdio-helmrelease-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c9decc038e0ec396029a1e705704d851f4789e53c0a3a48fd8ad5aa57c15b914
    enforceQuota: false
