apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: DB2
    k8s.io/resource: db2s
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-db2s
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/db2s.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/db2s.png
    type: image/png
  resource:
    group: kubedb.com
    kind: DB2
    name: db2s
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-db2-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:22fd5290b851c89592cb337197100f03772445b089db40f58a45333d317bee2c
    enforceQuota: true
    options:
      name: kubedbcom-db2-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:5332794ef2a0a664c655d634a9cb610934f4911de3339dc1c55a69d0efa5ae20
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
