apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: HanaDB
    k8s.io/resource: hanadbs
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-hanadbs
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/hanadbs.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/hanadbs.png
    type: image/png
  resource:
    group: kubedb.com
    kind: HanaDB
    name: hanadbs
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-hanadb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5e1155eb9ea04c753fa6a8c3ca2c3d6a73ecd2f2bd6ae1e6ef8782bd6c31078b
    enforceQuota: true
    options:
      name: kubedbcom-hanadb-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:92d07c65153c6e6519e0993b8bd9b50dc08d58f967deb5bc23c43e1c37ab889a
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
