apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Kafka
    k8s.io/resource: kafkas
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-kafkas
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/kafkas.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/kafkas.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Kafka
    name: kafkas
    scope: Namespaced
    version: v1alpha2
  ui:
    actions:
    - items:
      - editor:
          name: kubedbcom-kafka-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:64d9413cde9417a4c3343064b870676285208b8d598bb66a513d50a88c245ce0
        enforceQuota: false
        flow: standalone-edit
        icon: hugeicons:presentation-line-chart-01
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/monitor.svg
          type: image/svg+xml
        name: Monitoring
        operationId: edit-self-monitoring
      name: Security & Monitoring
    editor:
      name: kubedbcom-kafka-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:64d9413cde9417a4c3343064b870676285208b8d598bb66a513d50a88c245ce0
    enforceQuota: true
    options:
      name: kubedbcom-kafka-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5a060c21e3e7359c399f81884ded6df6ad7427bf9d7d8f80467dd9d41c6b9cac
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
