apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Kafka
    k8s.io/resource: kafkas
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-kafkas
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/kafkas.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/kafkas.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Kafka
    name: kafkas
    scope: Namespaced
    version: v1alpha2
  ui:
    actions:
    - items:
      - editor:
          name: kubedbcom-kafka-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:a0f1053b6800e6b298bea2439d149e85f307492c4a9d3af586668726e6d6f841
        enforceQuota: false
        flow: standalone-edit
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/monitor.svg
          type: image/svg+xml
        name: Monitoring
        operationId: edit-self-monitoring
      name: Security & Monitoring
    editor:
      name: kubedbcom-kafka-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a0f1053b6800e6b298bea2439d149e85f307492c4a9d3af586668726e6d6f841
    enforceQuota: true
    options:
      name: kubedbcom-kafka-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6aacbb558be9fe650dd5df15db106618d31d9cf87253b87e3994085474c2b83c
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
