apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Milvus
    k8s.io/resource: milvuses
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-milvuses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/milvus.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/milvus.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Milvus
    name: milvuses
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-milvus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a6f810f38737f72ad3b192990a6e955062e710dcdcebfaf058b5f8ff4ca98e47
    enforceQuota: true
    options:
      name: kubedbcom-milvus-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:56ebe41110be881b632057a12291771cac4669ed4a9b49efd3bb2009624db92f
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
