apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Milvus
    k8s.io/resource: milvuses
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-milvuses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/milvus.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/milvus.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Milvus
    name: milvuses
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-milvus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6e7caa5666130eb8cea1f7bb92957f009ecb4e4b493dc3864e3900c7cac7e96c
    enforceQuota: true
    options:
      name: kubedbcom-milvus-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:42e1558f11958258e2b9818dae6a879752a9b1d656132f3d2e3855bcfd3a0e3c
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
