apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Neo4j
    k8s.io/resource: neo4js
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-neo4js
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/neo4js.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/neo4js.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Neo4j
    name: neo4js
    scope: Namespaced
    version: v1alpha2
  ui:
    actions:
    - items:
      - editor:
          name: opskubedbcom-neo4jopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:c61ae107558e3692bdbeb6b26c406a9dab9cedc5ad8dbd97fbe3b41e0dbeb463
        enforceQuota: false
        flow: standalone-create
        icon: hugeicons:security-check
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/configure.svg
          type: image/svg+xml
        name: TLS Configure
        operationId: create-opsrequest-reconfiguretls
      - editor:
          name: kubedbcom-neo4j-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:82ac000d3a74d7e5e75e9c2c54b0957c44a5edb3f26375221581c082b74b6e4c
        enforceQuota: false
        flow: standalone-edit
        icon: hugeicons:presentation-line-chart-01
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/monitor.svg
          type: image/svg+xml
        name: Monitoring
        operationId: edit-self-monitoring
      name: Security & Monitoring
    editor:
      name: kubedbcom-neo4j-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:82ac000d3a74d7e5e75e9c2c54b0957c44a5edb3f26375221581c082b74b6e4c
    enforceQuota: true
    options:
      name: kubedbcom-neo4j-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:56ebe41110be881b632057a12291771cac4669ed4a9b49efd3bb2009624db92f
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
