apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: PerconaXtraDB
    k8s.io/resource: perconaxtradbs
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-perconaxtradbs
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/perconaxtradbs.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/perconaxtradbs.png
    type: image/png
  resource:
    group: kubedb.com
    kind: PerconaXtraDB
    name: perconaxtradbs
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-perconaxtradb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9580b902e953b6aa6ae0766198c4782d5ffbc7244b2d40d4532036f2806678e4
    enforceQuota: true
    options:
      name: kubedbcom-perconaxtradb-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:cf4be19005a3ca6a3245b96c78b2ceae377e254f77a6c1d36e81f468135a01fa
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
