apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: PerconaXtraDB
    k8s.io/resource: perconaxtradbs
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-perconaxtradbs
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/perconaxtradbs.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/perconaxtradbs.png
    type: image/png
  resource:
    group: kubedb.com
    kind: PerconaXtraDB
    name: perconaxtradbs
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-perconaxtradb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:fde165ba505114024a13adacc06cfa205b7059a30d8ce573dceb5b90d8b65590
    enforceQuota: true
    options:
      name: kubedbcom-perconaxtradb-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:8bc95d4632078efd32966b21212a0c358980f5854a98178008d58236a8691011
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
