apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: PerconaXtraDB
    k8s.io/resource: perconaxtradbs
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-perconaxtradbs
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/perconaxtradbs.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/perconaxtradbs.png
    type: image/png
  resource:
    group: kubedb.com
    kind: PerconaXtraDB
    name: perconaxtradbs
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-perconaxtradb-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9d55d2df206e13dce0978ca073ccc8b190f20c51461430ca63938ca0f44b21bb
    enforceQuota: true
    options:
      name: kubedbcom-perconaxtradb-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:03a353e9e707af218fe8f318faf0fd7da87955b4d80ebf4f36b8e01adb659724
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
