apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: PgBouncer
    k8s.io/resource: pgbouncers
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-pgbouncers
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/pgbouncers.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/pgbouncers.png
    type: image/png
  resource:
    group: kubedb.com
    kind: PgBouncer
    name: pgbouncers
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubedbcom-pgbouncer-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:380064a86fc395760bcfbb075f83af5bb8f6dd4e753adcb1ed3439102cfc4e9a
    enforceQuota: false
    options:
      name: kubedbcom-pgbouncer-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:90cb092e9a7305cbfe0f2daf4d2703557dcc6b1279aea79f0c5976ff5a65976b
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
