apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Qdrant
    k8s.io/resource: qdrants
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-qdrants
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/qdrants.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/qdrants.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Qdrant
    name: qdrants
    scope: Namespaced
    version: v1alpha2
  ui:
    actions:
    - items:
      - editor:
          name: opskubedbcom-qdrantopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:3bedb122157f5837b965319394a9e20bce452943b28ffc63da06ac919c187ddf
        enforceQuota: false
        flow: standalone-create
        icon: hugeicons:security-check
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/configure.svg
          type: image/svg+xml
        name: TLS Configure
        operationId: create-opsrequest-reconfiguretls
      - editor:
          name: kubedbcom-qdrant-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:29c7c9e366dee8e50c63f06e70dbf95611b74780f2025e88f13191c2619f6e13
        enforceQuota: false
        flow: standalone-edit
        icon: hugeicons:presentation-line-chart-01
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/monitor.svg
          type: image/svg+xml
        name: Monitoring
        operationId: edit-self-monitoring
      name: Security & Monitoring
    editor:
      name: kubedbcom-qdrant-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:29c7c9e366dee8e50c63f06e70dbf95611b74780f2025e88f13191c2619f6e13
    enforceQuota: true
    options:
      name: kubedbcom-qdrant-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:69d1434b48f1e5a48fadc45b6fce14ad5b85f27ed6100a74427b209be41420b2
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
