apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Qdrant
    k8s.io/resource: qdrants
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-qdrants
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/qdrants.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/qdrants.png
    type: image/png
  resource:
    group: kubedb.com
    kind: Qdrant
    name: qdrants
    scope: Namespaced
    version: v1alpha2
  ui:
    actions:
    - items:
      - editor:
          name: opskubedbcom-qdrantopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:457248a5d7263b6416e56765934374e275bb6e4eee093af6a84f4684c59085b0
        enforceQuota: false
        flow: standalone-create
        icon: hugeicons:security-check
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/configure.svg
          type: image/svg+xml
        name: TLS Configure
        operationId: create-opsrequest-reconfiguretls
      - editor:
          name: kubedbcom-qdrant-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:70b873e2e1867fe10855806992f334d1dba8a824f707cf19978e2f9901228b60
        enforceQuota: false
        flow: standalone-edit
        icon: hugeicons:presentation-line-chart-01
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/monitor.svg
          type: image/svg+xml
        name: Monitoring
        operationId: edit-self-monitoring
      name: Security & Monitoring
    editor:
      name: kubedbcom-qdrant-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:70b873e2e1867fe10855806992f334d1dba8a824f707cf19978e2f9901228b60
    enforceQuota: true
    options:
      name: kubedbcom-qdrant-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0ffb4d654d9d85a629888adfb8a8de4373d063e229daae523607dc987b74d40c
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
