apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: ZooKeeper
    k8s.io/resource: zookeepers
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-zookeepers
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/zookeepers.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/zookeepers.png
    type: image/png
  resource:
    group: kubedb.com
    kind: ZooKeeper
    name: zookeepers
    scope: Namespaced
    version: v1alpha2
  ui:
    actions:
    - items:
      - editor:
          name: kubedbcom-zookeeper-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:9bb57be5fef0cb6fb5a956597e7c815d1838db6322ac3a1a855d0483fa94b677
        enforceQuota: false
        flow: standalone-edit
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/configure-backup.svg
          type: image/svg+xml
        name: Configure Backup
        operationId: edit-self-backupconfiguration
      - editor:
          name: corekubestashcom-backupsession-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:af5d0e797a2ea2233f7c73fe281bb877b4129164bacdb3ee7e3df53640461dc9
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/instant-backup.svg
          type: image/svg+xml
        name: Instant Backup
        operationId: create-instant-backup
      - editor:
          name: corekubestashcom-restoresession-editor-options
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:57f242fff6b37d36df6d26d3c30e9e658554f7f388a112d463f7b268216f8479
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/restore.svg
          type: image/svg+xml
        name: Restore
        operationId: create-restoresession
      name: Backups
    - items:
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/version.svg
          type: image/svg+xml
        name: Update Version
        operationId: create-opsrequest-upgrade
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/restart.svg
          type: image/svg+xml
        name: Restart
        operationId: create-opsrequest-restart
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/reconfigure.svg
          type: image/svg+xml
        name: Reconfigure
        operationId: create-opsrequest-reconfigure
      name: Operations
    - items:
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/horizontal_scale.svg
          type: image/svg+xml
        name: Horizontal Scale
        operationId: create-opsrequest-horizontalscaling
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/vertical_scale.svg
          type: image/svg+xml
        name: Vertical Scale
        operationId: create-opsrequest-verticalscaling
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: true
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/expand.svg
          type: image/svg+xml
        name: Expand Volume
        operationId: create-opsrequest-volumeexpansion
      name: Scaling
    - items:
      - editor:
          name: opskubedbcom-zookeeperopsrequest-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:de74a59bf41220e9a0225da37c2f70f78ff6c2bc4990e61e005c017731fe996a
        enforceQuota: false
        flow: standalone-create
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/configure.svg
          type: image/svg+xml
        name: TLS Configure
        operationId: create-opsrequest-reconfiguretls
      - editor:
          name: kubedbcom-zookeeper-editor
          sourceRef:
            apiGroup: source.toolkit.fluxcd.io
            kind: HelmRepository
            name: appscode-charts-oci
          version: sha256:9bb57be5fef0cb6fb5a956597e7c815d1838db6322ac3a1a855d0483fa94b677
        enforceQuota: false
        flow: standalone-edit
        icons:
        - src: https://cdn.appscode.com/k8s/icons/action-icons/monitor.svg
          type: image/svg+xml
        name: Monitoring
        operationId: edit-self-monitoring
      name: Security & Monitoring
    editor:
      name: kubedbcom-zookeeper-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9bb57be5fef0cb6fb5a956597e7c815d1838db6322ac3a1a855d0483fa94b677
    enforceQuota: true
    options:
      name: kubedbcom-zookeeper-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:633798b8fc1ddd0f201e858a14de695f83ca736bfc8e7ee162dbb81bf0e67d75
  variants:
  - name: default
    selector:
      matchExpressions:
      - key: charts.x-helm.dev/is-default-preset
        operator: In
        values:
        - "true"
        - kubedb
