apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apiextensions.crossplane.io
    k8s.io/kind: EnvironmentConfig
    k8s.io/resource: environmentconfigs
    k8s.io/version: v1alpha1
  name: apiextensions.crossplane.io-v1alpha1-environmentconfigs
spec:
  resource:
    group: apiextensions.crossplane.io
    kind: EnvironmentConfig
    name: environmentconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: apiextensionscrossplaneio-environmentconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d23092ae2e3bf84a1e357ce432662c3f5ef763529c7b866f79aab7be8a79ebc9
    enforceQuota: false
