apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apiextensions.crossplane.io
    k8s.io/kind: EnvironmentConfig
    k8s.io/resource: environmentconfigs
    k8s.io/version: v1alpha1
  name: apiextensions.crossplane.io-v1alpha1-environmentconfigs
spec:
  resource:
    group: apiextensions.crossplane.io
    kind: EnvironmentConfig
    name: environmentconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: apiextensionscrossplaneio-environmentconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:f661a42db84bec04a2e03d69cda1cf2e445e4be266b981ed30ff15ad5b8e3569
    enforceQuota: false
