apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kafka.aws.kubedb.com
    k8s.io/kind: Cluster
    k8s.io/resource: clusters
    k8s.io/version: v1alpha1
  name: kafka.aws.kubedb.com-v1alpha1-clusters
spec:
  resource:
    group: kafka.aws.kubedb.com
    kind: Cluster
    name: clusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: kafkaawskubedbcom-cluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a260a5d0cf50fe66965be4f0058be0d10a477f3bf61d9af35997da4a6f252264
    enforceQuota: false
