apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kafka.aws.kubedb.com
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1alpha1
  name: kafka.aws.kubedb.com-v1alpha1-configurations
spec:
  resource:
    group: kafka.aws.kubedb.com
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: kafkaawskubedbcom-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:64d2f42f90e7aba709c13ea0cc8ca33a5a092cc53498f8b8aa4eded2be08da88
    enforceQuota: false
