apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cache.azure.kubedb.com
    k8s.io/kind: RedisFirewallRule
    k8s.io/resource: redisfirewallrules
    k8s.io/version: v1alpha1
  name: cache.azure.kubedb.com-v1alpha1-redisfirewallrules
spec:
  resource:
    group: cache.azure.kubedb.com
    kind: RedisFirewallRule
    name: redisfirewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cacheazurekubedbcom-redisfirewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:740e3afb10c0adb5bcd1dd9eb2be22f37f19364cfc8a811b87c46213564636e5
    enforceQuota: false
