apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.k8s.appscode.com
    k8s.io/kind: GenericResource
    k8s.io/resource: genericresources
    k8s.io/version: v1alpha1
  name: core.k8s.appscode.com-v1alpha1-genericresources
spec:
  resource:
    group: core.k8s.appscode.com
    kind: GenericResource
    name: genericresources
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corek8sappscodecom-genericresource-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:b681135a0c2620d0bc45a0a33df56515f3349b3c3b1fa9fc9dba36af7ceefdbb
    enforceQuota: false
