apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.k8s.appscode.com
    k8s.io/kind: GenericResource
    k8s.io/resource: genericresources
    k8s.io/version: v1alpha1
  name: core.k8s.appscode.com-v1alpha1-genericresources
spec:
  resource:
    group: core.k8s.appscode.com
    kind: GenericResource
    name: genericresources
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corek8sappscodecom-genericresource-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:80f96c49bcfe7d8e0e8354a36b0e8069c7dca41f327e980be705c575c6557179
    enforceQuota: false
