apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.k8s.appscode.com
    k8s.io/kind: Project
    k8s.io/resource: projects
    k8s.io/version: v1alpha1
  name: core.k8s.appscode.com-v1alpha1-projects
spec:
  resource:
    group: core.k8s.appscode.com
    kind: Project
    name: projects
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: corek8sappscodecom-project-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3b591a692c2a1a50e7f2f0206c583855584c4d9026e367ab81005aa37e98db70
    enforceQuota: false
