apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.k8s.appscode.com
    k8s.io/kind: ResourceSummary
    k8s.io/resource: resourcesummaries
    k8s.io/version: v1alpha1
  name: core.k8s.appscode.com-v1alpha1-resourcesummaries
spec:
  resource:
    group: core.k8s.appscode.com
    kind: ResourceSummary
    name: resourcesummaries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corek8sappscodecom-resourcesummary-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:7f9b152e2940f158c87e42e487f3822d730370ebf7e2db5cddf74889269b555e
    enforceQuota: false
