apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: products.x-helm.dev
    k8s.io/kind: Plan
    k8s.io/resource: plans
    k8s.io/version: v1alpha1
  name: products.x-helm.dev-v1alpha1-plans
spec:
  resource:
    group: products.x-helm.dev
    kind: Plan
    name: plans
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: productsxhelmdev-plan-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c1e321aca8dec3a5d3753e897400f25c225b79348757c0e6bf6cfa4a387b9f7d
    enforceQuota: false
