apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: products.x-helm.dev
    k8s.io/kind: Product
    k8s.io/resource: products
    k8s.io/version: v1alpha1
  name: products.x-helm.dev-v1alpha1-products
spec:
  resource:
    group: products.x-helm.dev
    kind: Product
    name: products
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: productsxhelmdev-product-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b8a364d1a480f763eaf9431f1e3421629043cc4bee3c6c6d8708f7ee1a1ab4ff
    enforceQuota: false
