apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: CassandraAutoscaler
    k8s.io/resource: cassandraautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-cassandraautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: CassandraAutoscaler
    name: cassandraautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-cassandraautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:cf4c518c31b3cf7323172489142e55baa8e68fd5556d0aeb84827bdc75e25c80
    enforceQuota: false
