apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: ClickHouseAutoscaler
    k8s.io/resource: clickhouseautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-clickhouseautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: ClickHouseAutoscaler
    name: clickhouseautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-clickhouseautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e76f843827a10a62e494b2c2d93f8b65214cd47fb72c884dd0fcbe049349db32
    enforceQuota: false
