apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: ElasticsearchAutoscaler
    k8s.io/resource: elasticsearchautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-elasticsearchautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: ElasticsearchAutoscaler
    name: elasticsearchautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-elasticsearchautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c9f04d779af945ca3123148222b66bec566fbd17fdeeb55071077cf9e87b8f57
    enforceQuota: false
