apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: ElasticsearchAutoscaler
    k8s.io/resource: elasticsearchautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-elasticsearchautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: ElasticsearchAutoscaler
    name: elasticsearchautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-elasticsearchautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:73a1ef8ed3e1e30ff26db8ad7055e7923ad9c1aee0790b84f0df0f66b8187828
    enforceQuota: false
