apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: ElasticsearchAutoscaler
    k8s.io/resource: elasticsearchautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-elasticsearchautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: ElasticsearchAutoscaler
    name: elasticsearchautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-elasticsearchautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0b84685267e77daa2fa83625a79b5e15c2cfee5b9b800996f9345b0c4703f518
    enforceQuota: false
