apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: EtcdAutoscaler
    k8s.io/resource: etcdautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-etcdautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: EtcdAutoscaler
    name: etcdautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-etcdautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0b4f399e3ae661e13c76be9aded316ab821e0c98a9242c9f56d5c73a5a0738db
    enforceQuota: false
