apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: FerretDBAutoscaler
    k8s.io/resource: ferretdbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-ferretdbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: FerretDBAutoscaler
    name: ferretdbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-ferretdbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:db46e8846e5e138cf7af2d4ef3c3316fd2350b8aee8a28dd604cde19402daf19
    enforceQuota: false
