apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: HanaDBAutoscaler
    k8s.io/resource: hanadbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-hanadbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: HanaDBAutoscaler
    name: hanadbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-hanadbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:7e749102b493ec150b2646077ee6d71ce431662588d1bc12b3519d9a4dd8582d
    enforceQuota: false
