apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: HanaDBAutoscaler
    k8s.io/resource: hanadbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-hanadbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: HanaDBAutoscaler
    name: hanadbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-hanadbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:93c28304b094f0e378f1dcb9de441a029349089d6bd4653affb721c0cf883ba9
    enforceQuota: false
