apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: HazelcastAutoscaler
    k8s.io/resource: hazelcastautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-hazelcastautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: HazelcastAutoscaler
    name: hazelcastautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-hazelcastautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:f66369187ce85e54bb1fef7e45270d207b1f068b67d16d0fc439fb558831d805
    enforceQuota: false
