apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: IgniteAutoscaler
    k8s.io/resource: igniteautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-igniteautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: IgniteAutoscaler
    name: igniteautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-igniteautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9a58b1879877f1b11eaf99795c6f3259bc96935c13c67a71d40c1ea19f4bf4ec
    enforceQuota: false
