apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: IgniteAutoscaler
    k8s.io/resource: igniteautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-igniteautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: IgniteAutoscaler
    name: igniteautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-igniteautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b500eac135f857f14b343805f12556e98ff350c85b0ed7dcd5c1ff69c559d88a
    enforceQuota: false
