apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MariaDBAutoscaler
    k8s.io/resource: mariadbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mariadbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MariaDBAutoscaler
    name: mariadbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mariadbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d43d8d78b4334f7eea6a5f54f9e9a9b349a9cd103edd4e913b747b03476a1805
    enforceQuota: false
