apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MariaDBAutoscaler
    k8s.io/resource: mariadbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mariadbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MariaDBAutoscaler
    name: mariadbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mariadbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:beeaed00e2cf2bc75a8e860506a360f85e95802ec84e0c24fd484ccedf53a2fc
    enforceQuota: false
