apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MariaDBAutoscaler
    k8s.io/resource: mariadbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mariadbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MariaDBAutoscaler
    name: mariadbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mariadbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:923781f8f76f46aac4173dbf46cebfd18fafc428d347af01f65de7d8a6271a67
    enforceQuota: false
