apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MemcachedAutoscaler
    k8s.io/resource: memcachedautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-memcachedautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MemcachedAutoscaler
    name: memcachedautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-memcachedautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6329e3e8f9036fecf014b4057128cab9e71fb3d4ec1ebef4574fc1350c322811
    enforceQuota: false
