apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MemcachedAutoscaler
    k8s.io/resource: memcachedautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-memcachedautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MemcachedAutoscaler
    name: memcachedautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-memcachedautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:8ce5a9a0ed3c9632be5dbff23a6132ee9ff3b50ecaaf478f7395f4b063033db2
    enforceQuota: false
