apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MongoDBAutoscaler
    k8s.io/resource: mongodbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mongodbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MongoDBAutoscaler
    name: mongodbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mongodbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:4e50546f25f9fc1df92081d7232e39ca5fd4fcf920cc9ba9a4efeb677aae9dfc
    enforceQuota: false
