apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MongoDBAutoscaler
    k8s.io/resource: mongodbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mongodbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MongoDBAutoscaler
    name: mongodbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mongodbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b6b2be1a88179e80b0377a77ad9f121423930754c2ee15f72bc030a5c385a39f
    enforceQuota: false
