apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MSSQLServerAutoscaler
    k8s.io/resource: mssqlserverautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mssqlserverautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MSSQLServerAutoscaler
    name: mssqlserverautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mssqlserverautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d23a7858f5cc05e9f7683e2cd37e6fad5232053df9b375542f84fb62dd5c821e
    enforceQuota: false
