apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MSSQLServerAutoscaler
    k8s.io/resource: mssqlserverautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mssqlserverautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MSSQLServerAutoscaler
    name: mssqlserverautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mssqlserverautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f3a078829c3dad89e69ce285c30a4052f3a211488064bb45c1896b8e1f7c86fa
    enforceQuota: false
