apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MSSQLServerAutoscaler
    k8s.io/resource: mssqlserverautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mssqlserverautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MSSQLServerAutoscaler
    name: mssqlserverautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mssqlserverautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f0c172d109d364f4cc34f015a2341e3044a255e0ef2e6f31fbfa747d6b7233ef
    enforceQuota: false
