apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: MySQLAutoscaler
    k8s.io/resource: mysqlautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-mysqlautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: MySQLAutoscaler
    name: mysqlautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-mysqlautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:65b18a95ce0c63c8d0fcdd5345d01c73c8ff11ae75a9b9a537384d6ff6bcb09e
    enforceQuota: false
