apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: Neo4jAutoscaler
    k8s.io/resource: neo4jautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-neo4jautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: Neo4jAutoscaler
    name: neo4jautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-neo4jautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:08cb4fa8351697d94c5f4d9f66e3356a9cdc1c31b7bcabc82952af89bc1568f3
    enforceQuota: false
