apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: PerconaXtraDBAutoscaler
    k8s.io/resource: perconaxtradbautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-perconaxtradbautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: PerconaXtraDBAutoscaler
    name: perconaxtradbautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-perconaxtradbautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7c82ff29e41a3d66e4ffda412dca4d93e6605cc0ade09557926935a152b6f5a8
    enforceQuota: false
