apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: PgpoolAutoscaler
    k8s.io/resource: pgpoolautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-pgpoolautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: PgpoolAutoscaler
    name: pgpoolautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-pgpoolautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a63b66e30f3d7b6edd9a37176d0bc4aa5eb53afddc6027713a0a10dbfa74331d
    enforceQuota: false
