apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: PgpoolAutoscaler
    k8s.io/resource: pgpoolautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-pgpoolautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: PgpoolAutoscaler
    name: pgpoolautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-pgpoolautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:759680b7ddd72a20b9c1d4fa04e016db4a25ec6d217ab185e1c356c5c49e0d19
    enforceQuota: false
