apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: PgpoolAutoscaler
    k8s.io/resource: pgpoolautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-pgpoolautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: PgpoolAutoscaler
    name: pgpoolautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-pgpoolautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:5043c716c1c6b34b8621cad7825832d8489ec1154fc5587be203d83a007e6787
    enforceQuota: false
