apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: ProxySQLAutoscaler
    k8s.io/resource: proxysqlautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-proxysqlautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: ProxySQLAutoscaler
    name: proxysqlautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-proxysqlautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:51e93b1ef8d6f7b516f96262280ee6e6c8b7dbf71ca8f16d535191a6e49d73af
    enforceQuota: false
