apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: WeaviateAutoscaler
    k8s.io/resource: weaviateautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-weaviateautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: WeaviateAutoscaler
    name: weaviateautoscalers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: autoscalingkubedbcom-weaviateautoscaler-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:74a717b1849d9a09c2e0cf5ec0a89dade58e5a8b0537bff8defc1388d57fbd30
    enforceQuota: false
