apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: redis.gcp.kubedb.com
    k8s.io/kind: Instance
    k8s.io/resource: instances
    k8s.io/version: v1alpha1
  name: redis.gcp.kubedb.com-v1alpha1-instances
spec:
  resource:
    group: redis.gcp.kubedb.com
    kind: Instance
    name: instances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: redisgcpkubedbcom-instance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ebe29997506fe7771577f7d32235e99ea20535d4c10e353950b792b713fa5148
    enforceQuota: false
