apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: addon.open-cluster-management.io
    k8s.io/kind: AddOnTemplate
    k8s.io/resource: addontemplates
    k8s.io/version: v1alpha1
  name: addon.open-cluster-management.io-v1alpha1-addontemplates
spec:
  resource:
    group: addon.open-cluster-management.io
    kind: AddOnTemplate
    name: addontemplates
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: addonopenclustermanagementio-addontemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8e3b4f0d76c4288f26405d6051a25ca6dc1a0d26a4f721dc626c302c1bddbd94
    enforceQuota: false
