apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: identity.k8s.appscode.com
    k8s.io/kind: ClusterIdentity
    k8s.io/resource: clusteridentitys
    k8s.io/version: v1alpha1
  name: identity.k8s.appscode.com-v1alpha1-clusteridentitys
spec:
  resource:
    group: identity.k8s.appscode.com
    kind: ClusterIdentity
    name: clusteridentitys
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: identityk8sappscodecom-clusteridentity-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1f9f6f6edaac53658d18caab21b4f5ab4d72a8fe2b094aaea37f708a176a4529
    enforceQuota: false
