apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: identity.k8s.appscode.com
    k8s.io/kind: SiteInfo
    k8s.io/resource: siteinfos
    k8s.io/version: v1alpha1
  name: identity.k8s.appscode.com-v1alpha1-siteinfos
spec:
  resource:
    group: identity.k8s.appscode.com
    kind: SiteInfo
    name: siteinfos
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: identityk8sappscodecom-siteinfo-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c76fe9afcc80ebaa7803e71746c91b33a152624109413b7fb0a71eef35318010
    enforceQuota: false
