apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: Route
    k8s.io/resource: routes
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-routes
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: Route
    name: routes
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-route-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:55c0151245917a8423fac75f60ad9079976c10ebd0a842a64ae41e33c7e0139c
    enforceQuota: false
