apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: Subnet
    k8s.io/resource: subnets
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-subnets
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: Subnet
    name: subnets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-subnet-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1f62bf2d6a05b3f9d0357bd480e575c72964c4f0d0ce3fe35333e59aaf2b2ac3
    enforceQuota: false
