apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: Subnet
    k8s.io/resource: subnets
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-subnets
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: Subnet
    name: subnets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-subnet-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ac2911550b1cda8018948dbfb8bfe3a9da78a5afb77161f65b8f6f9529802644
    enforceQuota: false
