apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: VPCEndpoint
    k8s.io/resource: vpcendpoints
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-vpcendpoints
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: VPCEndpoint
    name: vpcendpoints
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-vpcendpoint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6e4daeea11ecb411c6efdec42af72a1838aa93882b028ee0554162e0bf5e21be
    enforceQuota: false
