apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: VPCEndpoint
    k8s.io/resource: vpcendpoints
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-vpcendpoints
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: VPCEndpoint
    name: vpcendpoints
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-vpcendpoint-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:69aadbcb1ca431e5e5ec7e2c55c69eae7e7c5e4290b3a3a07a4564411fe976c6
    enforceQuota: false
