apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: VPC
    k8s.io/resource: vpcs
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-vpcs
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: VPC
    name: vpcs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-vpc-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:aba5ff12a1a2f75ae8cec3ecc3889ca9bbfe19a7ce9bf1b2a102b07e87ec297e
    enforceQuota: false
