apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: VPC
    k8s.io/resource: vpcs
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-vpcs
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: VPC
    name: vpcs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-vpc-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:408b4cea6182e7ceff3971b7194091ec366d2fa5f374066891e31c7d91d2b1f2
    enforceQuota: false
