apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: karpenter.azure.com
    k8s.io/kind: AKSNodeClass
    k8s.io/resource: aksnodeclasses
    k8s.io/version: v1alpha2
  name: karpenter.azure.com-v1alpha2-aksnodeclasses
spec:
  resource:
    group: karpenter.azure.com
    kind: AKSNodeClass
    name: aksnodeclasses
    scope: Cluster
    version: v1alpha2
  ui:
    editor:
      name: karpenterazurecom-aksnodeclass-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4baee10d3648293e1e9f862ba960fe123ed4213d6d0f63fd8412ca53f485488e
    enforceQuota: false
