apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: proxy.open-cluster-management.io
    k8s.io/kind: ManagedProxyConfiguration
    k8s.io/resource: managedproxyconfigurations
    k8s.io/version: v1alpha1
  name: proxy.open-cluster-management.io-v1alpha1-managedproxyconfigurations
spec:
  resource:
    group: proxy.open-cluster-management.io
    kind: ManagedProxyConfiguration
    name: managedproxyconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: proxyopenclustermanagementio-managedproxyconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cd75854fe5fd0810d2348b6dba89d16b7f9f6bc7183e710ad2dc3ed87b9ea228
    enforceQuota: false
