apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: AddOnPlacementScore
    k8s.io/resource: addonplacementscores
    k8s.io/version: v1alpha1
  name: cluster.open-cluster-management.io-v1alpha1-addonplacementscores
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: AddOnPlacementScore
    name: addonplacementscores
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: clusteropenclustermanagementio-addonplacementscore-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:98d5fb861e4bd6a0fc43aaa08b1603fed6c835670fcf909825ded27dbf02e9c4
    enforceQuota: false
