apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: AddOnPlacementScore
    k8s.io/resource: addonplacementscores
    k8s.io/version: v1alpha1
  name: cluster.open-cluster-management.io-v1alpha1-addonplacementscores
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: AddOnPlacementScore
    name: addonplacementscores
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: clusteropenclustermanagementio-addonplacementscore-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d7649aea9c3249e0b1a9688bc5b5d3be2e007263b335ebab542738106d7b6536
    enforceQuota: false
