apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: StoreConfig
    k8s.io/resource: storeconfigs
    k8s.io/version: v1alpha1
  name: aws.kubedb.com-v1alpha1-storeconfigs
spec:
  resource:
    group: aws.kubedb.com
    kind: StoreConfig
    name: storeconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: awskubedbcom-storeconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:994fa9afe2f0f86d74c2eab2c07b520f766b9b9377981852ba16b5fe6a890956
    enforceQuota: false
