apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: postgres.kubedb.com
    k8s.io/kind: Publisher
    k8s.io/resource: publishers
    k8s.io/version: v1alpha1
  name: postgres.kubedb.com-v1alpha1-publishers
spec:
  resource:
    group: postgres.kubedb.com
    kind: Publisher
    name: publishers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: postgreskubedbcom-publisher-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:7c7c4dae8c5f96e0378316aaaceaded4dc94adf84e3db4951c7cb4ac5372a305
    enforceQuota: false
