apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: postgres.kubedb.com
    k8s.io/kind: Subscriber
    k8s.io/resource: subscribers
    k8s.io/version: v1alpha1
  name: postgres.kubedb.com-v1alpha1-subscribers
spec:
  resource:
    group: postgres.kubedb.com
    kind: Subscriber
    name: subscribers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: postgreskubedbcom-subscriber-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:15ad6da2c563d842bdcc58a7c5e9398e9c90686a2a306d96cde8c5d3f42a5b7d
    enforceQuota: false
