apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: postgres.kubedb.com
    k8s.io/kind: Subscriber
    k8s.io/resource: subscribers
    k8s.io/version: v1alpha1
  name: postgres.kubedb.com-v1alpha1-subscribers
spec:
  resource:
    group: postgres.kubedb.com
    kind: Subscriber
    name: subscribers
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: postgreskubedbcom-subscriber-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e877792f6239bafd8ad84761c1d3b01d51927f6250d10f72e692d27396a9b12c
    enforceQuota: false
