apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: addons.cluster.x-k8s.io
    k8s.io/kind: ClusterResourceSet
    k8s.io/resource: clusterresourcesets
    k8s.io/version: v1beta1
  name: addons.cluster.x-k8s.io-v1beta1-clusterresourcesets
spec:
  resource:
    group: addons.cluster.x-k8s.io
    kind: ClusterResourceSet
    name: clusterresourcesets
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: addonsclusterxk8sio-clusterresourceset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:11dd164f83c47bc6a52f969af3c0fc8e13de18fac3bb58ed86f026d6015862b5
    enforceQuota: false
