apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: addons.cluster.x-k8s.io
    k8s.io/kind: ClusterResourceSet
    k8s.io/resource: clusterresourcesets
    k8s.io/version: v1beta1
  name: addons.cluster.x-k8s.io-v1beta1-clusterresourcesets
spec:
  resource:
    group: addons.cluster.x-k8s.io
    kind: ClusterResourceSet
    name: clusterresourcesets
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: addonsclusterxk8sio-clusterresourceset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:128c01b5f76a0e383e8d06e7fe0ff8cb4853754b929c63de3881861932ad4d82
    enforceQuota: false
