apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: memorydb.aws.kubedb.com
    k8s.io/kind: Snapshot
    k8s.io/resource: snapshots
    k8s.io/version: v1alpha1
  name: memorydb.aws.kubedb.com-v1alpha1-snapshots
spec:
  resource:
    group: memorydb.aws.kubedb.com
    kind: Snapshot
    name: snapshots
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: memorydbawskubedbcom-snapshot-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b273dc62ec24ea69e0789ca7f5af995425e81d11698f88ef95b90ad5979e5bf8
    enforceQuota: false
