apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: memorydb.aws.kubedb.com
    k8s.io/kind: SubnetGroup
    k8s.io/resource: subnetgroups
    k8s.io/version: v1alpha1
  name: memorydb.aws.kubedb.com-v1alpha1-subnetgroups
spec:
  resource:
    group: memorydb.aws.kubedb.com
    kind: SubnetGroup
    name: subnetgroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: memorydbawskubedbcom-subnetgroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0c1d5f1c1f0992f0a25a8cf00d16753d01a151d7a4c1e3f092e5f8b211e2138a
    enforceQuota: false
