apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: operator.open-cluster-management.io
    k8s.io/kind: ClusterManager
    k8s.io/resource: clustermanagers
    k8s.io/version: v1
  name: operator.open-cluster-management.io-v1-clustermanagers
spec:
  resource:
    group: operator.open-cluster-management.io
    kind: ClusterManager
    name: clustermanagers
    scope: Cluster
    version: v1
  ui:
    editor:
      name: operatoropenclustermanagementio-clustermanager-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:a43692a80cd979c72f90d088681d6f05408d0c35d10fa961f370e2ff146d81bf
    enforceQuota: false
