apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: operator.open-cluster-management.io
    k8s.io/kind: Klusterlet
    k8s.io/resource: klusterlets
    k8s.io/version: v1
  name: operator.open-cluster-management.io-v1-klusterlets
spec:
  resource:
    group: operator.open-cluster-management.io
    kind: Klusterlet
    name: klusterlets
    scope: Cluster
    version: v1
  ui:
    editor:
      name: operatoropenclustermanagementio-klusterlet-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:51515182478c618f12afe46df7ae8d00600a40544cf15eac913024af21cbad9e
    enforceQuota: false
