apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: Placement
    k8s.io/resource: placements
    k8s.io/version: v1beta1
  name: cluster.open-cluster-management.io-v1beta1-placements
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: Placement
    name: placements
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: clusteropenclustermanagementio-placement-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:57705cf559feda71c495f209fa4d7eb204081c5ce8a3c4c2242a7ebd566a22a6
    enforceQuota: false
