apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: Placement
    k8s.io/resource: placements
    k8s.io/version: v1beta1
  name: cluster.open-cluster-management.io-v1beta1-placements
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: Placement
    name: placements
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: clusteropenclustermanagementio-placement-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:32c1712da72f88b5e9f0863ac9f4d7f9a8c7681b202bd61fc1f6a8f5f7f2f93a
    enforceQuota: false
