apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: authorization.k8s.appscode.com
    k8s.io/kind: ManagedClusterSetRoleBinding
    k8s.io/resource: managedclustersetrolebindings
    k8s.io/version: v1alpha1
  name: authorization.k8s.appscode.com-v1alpha1-managedclustersetrolebindings
spec:
  resource:
    group: authorization.k8s.appscode.com
    kind: ManagedClusterSetRoleBinding
    name: managedclustersetrolebindings
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: authorizationk8sappscodecom-managedclustersetrolebinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7bc16d76e820396350eb573d50cc88054487974d7c010b1200614acb8fcd9937
    enforceQuota: false
