apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: authorization.k8s.appscode.com
    k8s.io/kind: ManagedClusterRoleBinding
    k8s.io/resource: managedclusterrolebindings
    k8s.io/version: v1alpha1
  name: authorization.k8s.appscode.com-v1alpha1-managedclusterrolebindings
spec:
  resource:
    group: authorization.k8s.appscode.com
    kind: ManagedClusterRoleBinding
    name: managedclusterrolebindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: authorizationk8sappscodecom-managedclusterrolebinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:28555e7ee81cc2631c1a2e87706637458a0ce03cd6f9f30a29ca5f84f4e6306a
    enforceQuota: false
