apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.gcp.kubedb.com
    k8s.io/kind: DatabaseInstance
    k8s.io/resource: databaseinstances
    k8s.io/version: v1alpha1
  name: sql.gcp.kubedb.com-v1alpha1-databaseinstances
spec:
  resource:
    group: sql.gcp.kubedb.com
    kind: DatabaseInstance
    name: databaseinstances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlgcpkubedbcom-databaseinstance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:23e4067b96d97d01003ad460494477781c834ea6cd2174fb03bdaa41c46530d5
    enforceQuota: false
