apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: sql.gcp.kubedb.com
    k8s.io/kind: SourceRepresentationInstance
    k8s.io/resource: sourcerepresentationinstances
    k8s.io/version: v1alpha1
  name: sql.gcp.kubedb.com-v1alpha1-sourcerepresentationinstances
spec:
  resource:
    group: sql.gcp.kubedb.com
    kind: SourceRepresentationInstance
    name: sourcerepresentationinstances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: sqlgcpkubedbcom-sourcerepresentationinstance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:75ec4aa6f15932d4590c4c29163d4ea738dae6eccdd43bb3cdc46087d2bb0d7d
    enforceQuota: false
