apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: KafkaRoute
    k8s.io/resource: kafkaroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-kafkaroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: KafkaRoute
    name: kafkaroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-kafkaroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4d78f9d6f502fb4758497146583e631a7007bd3438962b7352a5afb1d8e2470d
    enforceQuota: false
