apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MongoDBRoute
    k8s.io/resource: mongodbroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mongodbroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MongoDBRoute
    name: mongodbroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mongodbroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d3ea1ac3b8cc51925d81f2524028650d4e2c6c30d37a11a6fa4d5012d31d4af6
    enforceQuota: false
