apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MSSQLServerRoute
    k8s.io/resource: mssqlserverroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mssqlserverroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MSSQLServerRoute
    name: mssqlserverroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mssqlserverroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e547270a543fef586fdf44eb96d29cd4e4a19b56828af9d5ef6f097db4c2976d
    enforceQuota: false
