apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MySQLRoute
    k8s.io/resource: mysqlroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mysqlroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MySQLRoute
    name: mysqlroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mysqlroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:77141eed34e5a8ef7918402b8b6fd81392cc2ef8815542a3b7d19060c509b97d
    enforceQuota: false
