apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MySQLRoute
    k8s.io/resource: mysqlroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mysqlroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MySQLRoute
    name: mysqlroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mysqlroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1221b5f0ef44a56f0b4a26241d4410ee2c0aba1aa9dd4fcd5883629b49bad57e
    enforceQuota: false
