apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MySQLRoute
    k8s.io/resource: mysqlroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mysqlroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MySQLRoute
    name: mysqlroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mysqlroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6dd1506a69a261b05aa1d70eceb2db85a4bbad1d1e6515d58104e8397da0ed7d
    enforceQuota: false
