apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: RedisRoute
    k8s.io/resource: redisroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-redisroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: RedisRoute
    name: redisroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-redisroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2e6e8222446c93d3d063ab8423ea8c05219ad986eeba491272105dd3be4d9adf
    enforceQuota: false
