/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	nodev1alpha1 "kmodules.xyz/resource-metadata/apis/node/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NodeTopologiesGetter has a method to return a NodeTopologyInterface.
// A group's client should implement this interface.
type NodeTopologiesGetter interface {
	NodeTopologies() NodeTopologyInterface
}

// NodeTopologyInterface has methods to work with NodeTopology resources.
type NodeTopologyInterface interface {
	Create(ctx context.Context, nodeTopology *nodev1alpha1.NodeTopology, opts v1.CreateOptions) (*nodev1alpha1.NodeTopology, error)
	Update(ctx context.Context, nodeTopology *nodev1alpha1.NodeTopology, opts v1.UpdateOptions) (*nodev1alpha1.NodeTopology, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*nodev1alpha1.NodeTopology, error)
	List(ctx context.Context, opts v1.ListOptions) (*nodev1alpha1.NodeTopologyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nodev1alpha1.NodeTopology, err error)
	NodeTopologyExpansion
}

// nodeTopologies implements NodeTopologyInterface
type nodeTopologies struct {
	*gentype.ClientWithList[*nodev1alpha1.NodeTopology, *nodev1alpha1.NodeTopologyList]
}

// newNodeTopologies returns a NodeTopologies
func newNodeTopologies(c *NodeV1alpha1Client) *nodeTopologies {
	return &nodeTopologies{
		gentype.NewClientWithList[*nodev1alpha1.NodeTopology, *nodev1alpha1.NodeTopologyList](
			"nodetopologies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *nodev1alpha1.NodeTopology { return &nodev1alpha1.NodeTopology{} },
			func() *nodev1alpha1.NodeTopologyList { return &nodev1alpha1.NodeTopologyList{} },
		),
	}
}
