/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/profile/v1alpha1"
)

// FakeManagedClusterProfileBindings implements ManagedClusterProfileBindingInterface
type FakeManagedClusterProfileBindings struct {
	Fake *FakeProfileV1alpha1
	ns   string
}

var managedclusterprofilebindingsResource = v1alpha1.SchemeGroupVersion.WithResource("managedclusterprofilebindings")

var managedclusterprofilebindingsKind = v1alpha1.SchemeGroupVersion.WithKind("ManagedClusterProfileBinding")

// Get takes name of the managedClusterProfileBinding, and returns the corresponding managedClusterProfileBinding object, and an error if there is any.
func (c *FakeManagedClusterProfileBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managedclusterprofilebindingsResource, c.ns, name), &v1alpha1.ManagedClusterProfileBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterProfileBinding), err
}

// List takes label and field selectors, and returns the list of ManagedClusterProfileBindings that match those selectors.
func (c *FakeManagedClusterProfileBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterProfileBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managedclusterprofilebindingsResource, managedclusterprofilebindingsKind, c.ns, opts), &v1alpha1.ManagedClusterProfileBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagedClusterProfileBindingList{ListMeta: obj.(*v1alpha1.ManagedClusterProfileBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagedClusterProfileBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managedClusterProfileBindings.
func (c *FakeManagedClusterProfileBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managedclusterprofilebindingsResource, c.ns, opts))

}

// Create takes the representation of a managedClusterProfileBinding and creates it.  Returns the server's representation of the managedClusterProfileBinding, and an error, if there is any.
func (c *FakeManagedClusterProfileBindings) Create(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managedclusterprofilebindingsResource, c.ns, managedClusterProfileBinding), &v1alpha1.ManagedClusterProfileBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterProfileBinding), err
}

// Update takes the representation of a managedClusterProfileBinding and updates it. Returns the server's representation of the managedClusterProfileBinding, and an error, if there is any.
func (c *FakeManagedClusterProfileBindings) Update(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managedclusterprofilebindingsResource, c.ns, managedClusterProfileBinding), &v1alpha1.ManagedClusterProfileBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterProfileBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagedClusterProfileBindings) UpdateStatus(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterProfileBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managedclusterprofilebindingsResource, "status", c.ns, managedClusterProfileBinding), &v1alpha1.ManagedClusterProfileBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterProfileBinding), err
}

// Delete takes name of the managedClusterProfileBinding and deletes it. Returns an error if one occurs.
func (c *FakeManagedClusterProfileBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(managedclusterprofilebindingsResource, c.ns, name, opts), &v1alpha1.ManagedClusterProfileBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagedClusterProfileBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managedclusterprofilebindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagedClusterProfileBindingList{})
	return err
}

// Patch applies the patch and returns the patched managedClusterProfileBinding.
func (c *FakeManagedClusterProfileBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managedclusterprofilebindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagedClusterProfileBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterProfileBinding), err
}
