/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/profile/v1alpha1"
)

// FakeManagedClusterSetProfiles implements ManagedClusterSetProfileInterface
type FakeManagedClusterSetProfiles struct {
	Fake *FakeProfileV1alpha1
}

var managedclustersetprofilesResource = v1alpha1.SchemeGroupVersion.WithResource("managedclustersetprofiles")

var managedclustersetprofilesKind = v1alpha1.SchemeGroupVersion.WithKind("ManagedClusterSetProfile")

// Get takes name of the managedClusterSetProfile, and returns the corresponding managedClusterSetProfile object, and an error if there is any.
func (c *FakeManagedClusterSetProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(managedclustersetprofilesResource, name), &v1alpha1.ManagedClusterSetProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterSetProfile), err
}

// List takes label and field selectors, and returns the list of ManagedClusterSetProfiles that match those selectors.
func (c *FakeManagedClusterSetProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterSetProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(managedclustersetprofilesResource, managedclustersetprofilesKind, opts), &v1alpha1.ManagedClusterSetProfileList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagedClusterSetProfileList{ListMeta: obj.(*v1alpha1.ManagedClusterSetProfileList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagedClusterSetProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managedClusterSetProfiles.
func (c *FakeManagedClusterSetProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(managedclustersetprofilesResource, opts))
}

// Create takes the representation of a managedClusterSetProfile and creates it.  Returns the server's representation of the managedClusterSetProfile, and an error, if there is any.
func (c *FakeManagedClusterSetProfiles) Create(ctx context.Context, managedClusterSetProfile *v1alpha1.ManagedClusterSetProfile, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(managedclustersetprofilesResource, managedClusterSetProfile), &v1alpha1.ManagedClusterSetProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterSetProfile), err
}

// Update takes the representation of a managedClusterSetProfile and updates it. Returns the server's representation of the managedClusterSetProfile, and an error, if there is any.
func (c *FakeManagedClusterSetProfiles) Update(ctx context.Context, managedClusterSetProfile *v1alpha1.ManagedClusterSetProfile, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(managedclustersetprofilesResource, managedClusterSetProfile), &v1alpha1.ManagedClusterSetProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterSetProfile), err
}

// Delete takes name of the managedClusterSetProfile and deletes it. Returns an error if one occurs.
func (c *FakeManagedClusterSetProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(managedclustersetprofilesResource, name, opts), &v1alpha1.ManagedClusterSetProfile{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagedClusterSetProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(managedclustersetprofilesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagedClusterSetProfileList{})
	return err
}

// Patch applies the patch and returns the patched managedClusterSetProfile.
func (c *FakeManagedClusterSetProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(managedclustersetprofilesResource, name, pt, data, subresources...), &v1alpha1.ManagedClusterSetProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterSetProfile), err
}
