apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: ElasticsearchInsight
    k8s.io/resource: elasticsearchinsights
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-elasticsearchinsights
spec:
  resource:
    group: ui.kubedb.com
    kind: ElasticsearchInsight
    name: elasticsearchinsights
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-elasticsearchinsight-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f912ec2f42b6383f3319b0e2b17f9c0bb0b0eb8b026d2eade103db5e4a6630bf
    enforceQuota: false
