apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: ElasticsearchNodesStats
    k8s.io/resource: elasticsearchnodesstats
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-elasticsearchnodesstats
spec:
  resource:
    group: ui.kubedb.com
    kind: ElasticsearchNodesStats
    name: elasticsearchnodesstats
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-elasticsearchnodesstats-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a67a0c4700df4c5dc9961d3d42206f397dd4a9480e4f6452330ffa7ebfb24dab
    enforceQuota: false
