apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MariaDBSchemaOverview
    k8s.io/resource: mariadbschemaoverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mariadbschemaoverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: MariaDBSchemaOverview
    name: mariadbschemaoverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mariadbschemaoverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a2fb4d28c1ea30bf2f5a95b767955c8a04f5bf2f9fd13f52016a61c7a9fc79fc
    enforceQuota: false
