apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MariaDBSchemaOverview
    k8s.io/resource: mariadbschemaoverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mariadbschemaoverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: MariaDBSchemaOverview
    name: mariadbschemaoverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mariadbschemaoverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1e4df4fb65022f6a977ad584193f9e6db2ccc353315e2e341d793ec97d18a64c
    enforceQuota: false
