apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MariaDBQueries
    k8s.io/resource: mariadbqueries
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mariadbqueries
spec:
  resource:
    group: ui.kubedb.com
    kind: MariaDBQueries
    name: mariadbqueries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mariadbqueries-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d6ce275609c41afd6e2e8b35d92418671e9972a644dbee41f8dcf912ef2b33eb
    enforceQuota: false
