apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MongoDBSchemaOverview
    k8s.io/resource: mongodbschemaoverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mongodbschemaoverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: MongoDBSchemaOverview
    name: mongodbschemaoverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mongodbschemaoverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a4e1f86ceb5e5740681c460459b7a2045141406f83967ae7be3cb7b6f5aefd0e
    enforceQuota: false
