apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MongoDBSchemaOverview
    k8s.io/resource: mongodbschemaoverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mongodbschemaoverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: MongoDBSchemaOverview
    name: mongodbschemaoverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mongodbschemaoverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f600543fc7f181cda6f838f7f182eec926618e832709a363c46568a1c5149286
    enforceQuota: false
