apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MySQLQueries
    k8s.io/resource: mysqlqueries
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mysqlqueries
spec:
  resource:
    group: ui.kubedb.com
    kind: MySQLQueries
    name: mysqlqueries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mysqlqueries-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0f5f1e5aa8438902b45d2169ffcaf4c2f5a59064eb4bff73825f97fedac7ad96
    enforceQuota: false
