apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MySQLSchemaOverview
    k8s.io/resource: mysqlschemaoverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mysqlschemaoverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: MySQLSchemaOverview
    name: mysqlschemaoverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mysqlschemaoverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1c29e6f6fb6bc3945bc4079054d48ddb183b2f4c4f934b5467456159e9459087
    enforceQuota: false
