apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MySQLSchemaOverview
    k8s.io/resource: mysqlschemaoverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mysqlschemaoverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: MySQLSchemaOverview
    name: mysqlschemaoverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mysqlschemaoverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:50c7c4d15525bc7a9f37e90630cff2e99d79784b62deb1996be676b5a4172f1f
    enforceQuota: false
