apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: MySQLInsight
    k8s.io/resource: mysqlinsights
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-mysqlinsights
spec:
  resource:
    group: ui.kubedb.com
    kind: MySQLInsight
    name: mysqlinsights
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-mysqlinsight-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b7d4594e6902e77424ccf46ab37e29d71c2de3834ef470f4a5390ce75f355e59
    enforceQuota: false
