apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: PgBouncerPools
    k8s.io/resource: pgbouncerpools
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-pgbouncerpools
spec:
  resource:
    group: ui.kubedb.com
    kind: PgBouncerPools
    name: pgbouncerpools
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-pgbouncerpools-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1da567b55c99291dbda0c0b2566029641be19bf6a44d85b4f20b2a30e5029e30
    enforceQuota: false
