apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: PgBouncerPoolOverview
    k8s.io/resource: pgbouncerpooloverviews
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-pgbouncerpooloverviews
spec:
  resource:
    group: ui.kubedb.com
    kind: PgBouncerPoolOverview
    name: pgbouncerpooloverviews
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-pgbouncerpooloverview-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0a7b91912ed7ec6736660c9335866569223261641b330ad3749a4e90fc50e8d7
    enforceQuota: false
