apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: PostgresSettings
    k8s.io/resource: postgressettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-postgressettings
spec:
  resource:
    group: ui.kubedb.com
    kind: PostgresSettings
    name: postgressettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-postgressettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e31a9d29af76abe418055411ff23ed2c9ea618626b42df7c55de28980a4b8e36
    enforceQuota: false
