apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: ProxySQLSettings
    k8s.io/resource: proxysqlsettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-proxysqlsettings
spec:
  resource:
    group: ui.kubedb.com
    kind: ProxySQLSettings
    name: proxysqlsettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-proxysqlsettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:eec7483cd1c499ce5c6b6e473956abe32f6a5282d3b19384f6ca3c0c486f2aa0
    enforceQuota: false
