apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: ProxySQLSettings
    k8s.io/resource: proxysqlsettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-proxysqlsettings
spec:
  resource:
    group: ui.kubedb.com
    kind: ProxySQLSettings
    name: proxysqlsettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-proxysqlsettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ef9033c7826ac22351838a0297c2d911b98e8af605b1b5c84f477fa51b2f48a4
    enforceQuota: false
