apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: ProxySQLSettings
    k8s.io/resource: proxysqlsettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-proxysqlsettings
spec:
  resource:
    group: ui.kubedb.com
    kind: ProxySQLSettings
    name: proxysqlsettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-proxysqlsettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b5efeee75aa41e6af110e809fb342e9c336a57ec7e88e89370f2b4bf43234c8c
    enforceQuota: false
