apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: azure.kubedb.com
    k8s.io/kind: ProviderRegistration
    k8s.io/resource: providerregistrations
    k8s.io/version: v1alpha1
  name: azure.kubedb.com-v1alpha1-providerregistrations
spec:
  resource:
    group: azure.kubedb.com
    kind: ProviderRegistration
    name: providerregistrations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: azurekubedbcom-providerregistration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b622d42d0c0d8e7d4fe30fb468cc07f7075acbf14645cad06c5710eb6fff1380
    enforceQuota: false
