apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: azure.kubedb.com
    k8s.io/kind: ProviderRegistration
    k8s.io/resource: providerregistrations
    k8s.io/version: v1alpha1
  name: azure.kubedb.com-v1alpha1-providerregistrations
spec:
  resource:
    group: azure.kubedb.com
    kind: ProviderRegistration
    name: providerregistrations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: azurekubedbcom-providerregistration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5aa4bbc33a9a8717c54183b99c47cec50152b442dae2444ea4cbaa4d72471010
    enforceQuota: false
