apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: azure.kubedb.com
    k8s.io/kind: ResourceGroup
    k8s.io/resource: resourcegroups
    k8s.io/version: v1alpha1
  name: azure.kubedb.com-v1alpha1-resourcegroups
spec:
  resource:
    group: azure.kubedb.com
    kind: ResourceGroup
    name: resourcegroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: azurekubedbcom-resourcegroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c6bdc7a2333bd9b385e9b6a5af0a664032a599a36692505906df4b23ee1b3d34
    enforceQuota: false
