apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: snapshot.storage.k8s.io
    k8s.io/kind: VolumeSnapshotContent
    k8s.io/resource: volumesnapshotcontents
    k8s.io/version: v1
  name: snapshot.storage.k8s.io-v1-volumesnapshotcontents
spec:
  resource:
    group: snapshot.storage.k8s.io
    kind: VolumeSnapshotContent
    name: volumesnapshotcontents
    scope: Cluster
    version: v1
  ui:
    editor:
      name: snapshotstoragek8sio-volumesnapshotcontent-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:404be26b15e94f72be4f86936927de28a7cf7da3cd52a88e35c1ae468f1623b7
    enforceQuota: false
