apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: flowcontrol.apiserver.k8s.io
    k8s.io/kind: PriorityLevelConfiguration
    k8s.io/resource: prioritylevelconfigurations
    k8s.io/version: v1beta1
  name: flowcontrol.apiserver.k8s.io-v1beta1-prioritylevelconfigurations
spec:
  resource:
    group: flowcontrol.apiserver.k8s.io
    kind: PriorityLevelConfiguration
    name: prioritylevelconfigurations
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: flowcontrolapiserverk8sio-prioritylevelconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:b6ef19930699c78a993509f38ca3ef7c00a225e0d16488968cc0d3a2a9cdde81
    enforceQuota: false
