apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: AuthenticationFilter
    k8s.io/resource: authenticationfilters
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-authenticationfilters
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: AuthenticationFilter
    name: authenticationfilters
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-authenticationfilter-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4688c81f3f33943ff11d93deeb936265583979babd5da1f6a8f8a8dc5729a892
    enforceQuota: false
