apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: AuthenticationFilter
    k8s.io/resource: authenticationfilters
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-authenticationfilters
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: AuthenticationFilter
    name: authenticationfilters
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-authenticationfilter-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:57d4c55b312c10b85ee0dc8afd861cb608281b50cecdc9670c77d37e1477e9a6
    enforceQuota: false
