apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: AuthenticationFilter
    k8s.io/resource: authenticationfilters
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-authenticationfilters
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: AuthenticationFilter
    name: authenticationfilters
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-authenticationfilter-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:a66e3c9e5b29eee0d7e29dde9149c7f0a996ae6930c3590b7c36677db0aea24c
    enforceQuota: false
