apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: BackendTrafficPolicy
    k8s.io/resource: backendtrafficpolicies
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-backendtrafficpolicies
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: BackendTrafficPolicy
    name: backendtrafficpolicies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-backendtrafficpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:dba9e82c7983a15f43b5db94a34a2f00599e9c434fe8539c6c2ab139c11db855
    enforceQuota: false
