apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: EnvoyProxy
    k8s.io/resource: envoyproxies
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-envoyproxies
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoyproxies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-envoyproxy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8f9ee30803fef8b3cc296552ea7cab33e795c97480756e4f38c7526d84d7a848
    enforceQuota: false
