apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: EnvoyExtensionPolicy
    k8s.io/resource: envoyextensionpolicies
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-envoyextensionpolicies
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: EnvoyExtensionPolicy
    name: envoyextensionpolicies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-envoyextensionpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:959b92a0b0cc7aedc11b2816403b6c000bfeb730995d1b76cb9d20b55925a57b
    enforceQuota: false
