apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: HTTPRouteFilter
    k8s.io/resource: httproutefilters
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-httproutefilters
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: HTTPRouteFilter
    name: httproutefilters
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-httproutefilter-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b7b0b9b7c1531c00a8e97f9587c99e7cf2c341ff57156b262baf21c238a0137a
    enforceQuota: false
