apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.envoyproxy.io
    k8s.io/kind: SecurityPolicy
    k8s.io/resource: securitypolicies
    k8s.io/version: v1alpha1
  name: gateway.envoyproxy.io-v1alpha1-securitypolicies
spec:
  resource:
    group: gateway.envoyproxy.io
    kind: SecurityPolicy
    name: securitypolicies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayenvoyproxyio-securitypolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:079c976250ee368370f642f88bd8922288c53a5c8844cd3f56d5c5dce41b4892
    enforceQuota: false
