apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: Gateway
    k8s.io/resource: gateways
    k8s.io/version: v1
  name: gateway.networking.k8s.io-v1-gateways
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateways
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: gatewaynetworkingk8sio-gateway-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5208c861b219ace29fe824fe62f3b2e8e09de8071efed6b0465cf00d62a0957b
    enforceQuota: false
