apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: HTTPRoute
    k8s.io/resource: httproutes
    k8s.io/version: v1
  name: gateway.networking.k8s.io-v1-httproutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httproutes
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: gatewaynetworkingk8sio-httproute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4d0219a18a7f33c04cc72c31ccf38d4a84db46da5aeb0d2bdfb470d34ca7d8d9
    enforceQuota: false
