apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: charts.x-helm.dev
    k8s.io/kind: ClusterChartPreset
    k8s.io/resource: clusterchartpresets
    k8s.io/version: v1alpha1
  name: charts.x-helm.dev-v1alpha1-clusterchartpresets
spec:
  resource:
    group: charts.x-helm.dev
    kind: ClusterChartPreset
    name: clusterchartpresets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: chartsxhelmdev-clusterchartpreset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:009534a1e59ee703322098efc10815a06bebdc93ee75a4682fbf4b70a4563336
    enforceQuota: false
    options:
      name: chartsxhelmdev-clusterchartpreset-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:313ad97fa0d64614a66a3a42e4495b666806be7c3475b1231b671f08dd3c6976
