apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: charts.x-helm.dev
    k8s.io/kind: ClusterChartPreset
    k8s.io/resource: clusterchartpresets
    k8s.io/version: v1alpha1
  name: charts.x-helm.dev-v1alpha1-clusterchartpresets
spec:
  resource:
    group: charts.x-helm.dev
    kind: ClusterChartPreset
    name: clusterchartpresets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: chartsxhelmdev-clusterchartpreset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cd6f4dd36095c18bd925420a1c10b880757d5a139183c99748459d24c6acab92
    enforceQuota: false
    options:
      name: chartsxhelmdev-clusterchartpreset-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ed424c6b9470231443d21be9b44ecedd1c17183dff67783542a4d813d41786e8
