apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: charts.x-helm.dev
    k8s.io/kind: ClusterChartPreset
    k8s.io/resource: clusterchartpresets
    k8s.io/version: v1alpha1
  name: charts.x-helm.dev-v1alpha1-clusterchartpresets
spec:
  resource:
    group: charts.x-helm.dev
    kind: ClusterChartPreset
    name: clusterchartpresets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: chartsxhelmdev-clusterchartpreset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:70c649027c69d8c8b948b3ee0ce327fc6a654b0edc0b882f4ed03ad56121204e
    enforceQuota: false
    options:
      name: chartsxhelmdev-clusterchartpreset-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a1a4e040e45ac95f033212d4a971e26bea081901ecdbf3419626f6b82d83a04a
