apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: Recovery
    k8s.io/resource: recoveries
    k8s.io/version: v1alpha1
  name: stash.appscode.com-v1alpha1-recoveries
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/recoveries.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/recoveries.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: Recovery
    name: recoveries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: stashappscodecom-recovery-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a5e26bdbe6b77d800403eb3158796028c5c3238d690fff0c4ab48cf066a3331c
    enforceQuota: false
