apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: Recovery
    k8s.io/resource: recoveries
    k8s.io/version: v1alpha1
  name: stash.appscode.com-v1alpha1-recoveries
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/recoveries.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/recoveries.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: Recovery
    name: recoveries
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: stashappscodecom-recovery-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:13322c8cf47ae78ccd8f779bdf8b1e4d13192a34c3f72888d24d4906385e0d62
    enforceQuota: false
