apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: Repository
    k8s.io/resource: repositories
    k8s.io/version: v1alpha1
  name: stash.appscode.com-v1alpha1-repositories
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/repositories.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/repositories.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: Repository
    name: repositories
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: stashappscodecom-repository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a617b4492625322c0c325a7011a68dd1b8d4e18a5e27db4fa5c332b9c516aae0
    enforceQuota: false
    options:
      name: stashappscodecom-repository-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5715cfd65433b4c0afda91b57ea7fab997c82f05779c65e5ed295fc0bdead4df
