apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: Repository
    k8s.io/resource: repositories
    k8s.io/version: v1alpha1
  name: stash.appscode.com-v1alpha1-repositories
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/repositories.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/repositories.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: Repository
    name: repositories
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: stashappscodecom-repository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5c7cd7d042c426cde07162c3796b970b569232d1e94d66bc2012c281068a4c4b
    enforceQuota: false
    options:
      name: stashappscodecom-repository-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3185556217cca423504b2e357b90d7b6066879022df8316fcbf72542f3d962d8
