/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	metav1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MenuOutlinesGetter has a method to return a MenuOutlineInterface.
// A group's client should implement this interface.
type MenuOutlinesGetter interface {
	MenuOutlines(namespace string) MenuOutlineInterface
}

// MenuOutlineInterface has methods to work with MenuOutline resources.
type MenuOutlineInterface interface {
	Create(ctx context.Context, menuOutline *metav1alpha1.MenuOutline, opts v1.CreateOptions) (*metav1alpha1.MenuOutline, error)
	Update(ctx context.Context, menuOutline *metav1alpha1.MenuOutline, opts v1.UpdateOptions) (*metav1alpha1.MenuOutline, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*metav1alpha1.MenuOutline, error)
	List(ctx context.Context, opts v1.ListOptions) (*metav1alpha1.MenuOutlineList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *metav1alpha1.MenuOutline, err error)
	MenuOutlineExpansion
}

// menuOutlines implements MenuOutlineInterface
type menuOutlines struct {
	*gentype.ClientWithList[*metav1alpha1.MenuOutline, *metav1alpha1.MenuOutlineList]
}

// newMenuOutlines returns a MenuOutlines
func newMenuOutlines(c *MetaV1alpha1Client, namespace string) *menuOutlines {
	return &menuOutlines{
		gentype.NewClientWithList[*metav1alpha1.MenuOutline, *metav1alpha1.MenuOutlineList](
			"menuoutlines",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *metav1alpha1.MenuOutline { return &metav1alpha1.MenuOutline{} },
			func() *metav1alpha1.MenuOutlineList { return &metav1alpha1.MenuOutlineList{} },
		),
	}
}
