/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	"kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

type MetaV1alpha1Interface interface {
	RESTClient() rest.Interface
	ChartPresetQueriesGetter
	MenuOutlinesGetter
	RendersGetter
	RenderDashboardsGetter
	RenderMenusGetter
	RenderRawGraphsGetter
	ResourceBlockDefinitionsGetter
	ResourceCalculatorsGetter
	ResourceDescriptorsGetter
	ResourceGraphsGetter
	ResourceLayoutsGetter
	ResourceOutlinesGetter
	ResourceQueriesGetter
	ResourceTableDefinitionsGetter
}

// MetaV1alpha1Client is used to interact with features provided by the meta.k8s.appscode.com group.
type MetaV1alpha1Client struct {
	restClient rest.Interface
}

func (c *MetaV1alpha1Client) ChartPresetQueries() ChartPresetQueryInterface {
	return newChartPresetQueries(c)
}

func (c *MetaV1alpha1Client) MenuOutlines(namespace string) MenuOutlineInterface {
	return newMenuOutlines(c, namespace)
}

func (c *MetaV1alpha1Client) Renders() RenderInterface {
	return newRenders(c)
}

func (c *MetaV1alpha1Client) RenderDashboards() RenderDashboardInterface {
	return newRenderDashboards(c)
}

func (c *MetaV1alpha1Client) RenderMenus() RenderMenuInterface {
	return newRenderMenus(c)
}

func (c *MetaV1alpha1Client) RenderRawGraphs() RenderRawGraphInterface {
	return newRenderRawGraphs(c)
}

func (c *MetaV1alpha1Client) ResourceBlockDefinitions() ResourceBlockDefinitionInterface {
	return newResourceBlockDefinitions(c)
}

func (c *MetaV1alpha1Client) ResourceCalculators() ResourceCalculatorInterface {
	return newResourceCalculators(c)
}

func (c *MetaV1alpha1Client) ResourceDescriptors() ResourceDescriptorInterface {
	return newResourceDescriptors(c)
}

func (c *MetaV1alpha1Client) ResourceGraphs() ResourceGraphInterface {
	return newResourceGraphs(c)
}

func (c *MetaV1alpha1Client) ResourceLayouts() ResourceLayoutInterface {
	return newResourceLayouts(c)
}

func (c *MetaV1alpha1Client) ResourceOutlines() ResourceOutlineInterface {
	return newResourceOutlines(c)
}

func (c *MetaV1alpha1Client) ResourceQueries() ResourceQueryInterface {
	return newResourceQueries(c)
}

func (c *MetaV1alpha1Client) ResourceTableDefinitions() ResourceTableDefinitionInterface {
	return newResourceTableDefinitions(c)
}

// NewForConfig creates a new MetaV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*MetaV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new MetaV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*MetaV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &MetaV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new MetaV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MetaV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MetaV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *MetaV1alpha1Client {
	return &MetaV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MetaV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
