/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// RendersGetter has a method to return a RenderInterface.
// A group's client should implement this interface.
type RendersGetter interface {
	Renders() RenderInterface
}

// RenderInterface has methods to work with Render resources.
type RenderInterface interface {
	Create(ctx context.Context, render *v1alpha1.Render, opts v1.CreateOptions) (*v1alpha1.Render, error)
	RenderExpansion
}

// renders implements RenderInterface
type renders struct {
	client rest.Interface
}

// newRenders returns a Renders
func newRenders(c *MetaV1alpha1Client) *renders {
	return &renders{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a render and creates it.  Returns the server's representation of the render, and an error, if there is any.
func (c *renders) Create(ctx context.Context, render *v1alpha1.Render, opts v1.CreateOptions) (result *v1alpha1.Render, err error) {
	result = &v1alpha1.Render{}
	err = c.client.Post().
		Resource("renders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(render).
		Do(ctx).
		Into(result)
	return
}
