/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	metav1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "kmodules.xyz/client-go/gentype"
)

// ResourceGraphsGetter has a method to return a ResourceGraphInterface.
// A group's client should implement this interface.
type ResourceGraphsGetter interface {
	ResourceGraphs() ResourceGraphInterface
}

// ResourceGraphInterface has methods to work with ResourceGraph resources.
type ResourceGraphInterface interface {
	Create(ctx context.Context, resourceGraph *metav1alpha1.ResourceGraph, opts v1.CreateOptions) (*metav1alpha1.ResourceGraph, error)
	ResourceGraphExpansion
}

// resourceGraphs implements ResourceGraphInterface
type resourceGraphs struct {
	*gentype.Client[*metav1alpha1.ResourceGraph]
}

// newResourceGraphs returns a ResourceGraphs
func newResourceGraphs(c *MetaV1alpha1Client) *resourceGraphs {
	return &resourceGraphs{
		gentype.NewClient[*metav1alpha1.ResourceGraph](
			"resourcegraphs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *metav1alpha1.ResourceGraph { return &metav1alpha1.ResourceGraph{} },
		),
	}
}
