/*
Copyright The Kmodules Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceDescriptorsGetter has a method to return a ResourceDescriptorInterface.
// A group's client should implement this interface.
type ResourceDescriptorsGetter interface {
	ResourceDescriptors() ResourceDescriptorInterface
}

// ResourceDescriptorInterface has methods to work with ResourceDescriptor resources.
type ResourceDescriptorInterface interface {
	Create(ctx context.Context, resourceDescriptor *v1alpha1.ResourceDescriptor, opts v1.CreateOptions) (*v1alpha1.ResourceDescriptor, error)
	Update(ctx context.Context, resourceDescriptor *v1alpha1.ResourceDescriptor, opts v1.UpdateOptions) (*v1alpha1.ResourceDescriptor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ResourceDescriptor, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ResourceDescriptorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceDescriptor, err error)
	ResourceDescriptorExpansion
}

// resourceDescriptors implements ResourceDescriptorInterface
type resourceDescriptors struct {
	client rest.Interface
}

// newResourceDescriptors returns a ResourceDescriptors
func newResourceDescriptors(c *MetaV1alpha1Client) *resourceDescriptors {
	return &resourceDescriptors{
		client: c.RESTClient(),
	}
}

// Get takes name of the resourceDescriptor, and returns the corresponding resourceDescriptor object, and an error if there is any.
func (c *resourceDescriptors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceDescriptor, err error) {
	result = &v1alpha1.ResourceDescriptor{}
	err = c.client.Get().
		Resource("resourcedescriptors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceDescriptors that match those selectors.
func (c *resourceDescriptors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ResourceDescriptorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ResourceDescriptorList{}
	err = c.client.Get().
		Resource("resourcedescriptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceDescriptors.
func (c *resourceDescriptors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("resourcedescriptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a resourceDescriptor and creates it.  Returns the server's representation of the resourceDescriptor, and an error, if there is any.
func (c *resourceDescriptors) Create(ctx context.Context, resourceDescriptor *v1alpha1.ResourceDescriptor, opts v1.CreateOptions) (result *v1alpha1.ResourceDescriptor, err error) {
	result = &v1alpha1.ResourceDescriptor{}
	err = c.client.Post().
		Resource("resourcedescriptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceDescriptor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a resourceDescriptor and updates it. Returns the server's representation of the resourceDescriptor, and an error, if there is any.
func (c *resourceDescriptors) Update(ctx context.Context, resourceDescriptor *v1alpha1.ResourceDescriptor, opts v1.UpdateOptions) (result *v1alpha1.ResourceDescriptor, err error) {
	result = &v1alpha1.ResourceDescriptor{}
	err = c.client.Put().
		Resource("resourcedescriptors").
		Name(resourceDescriptor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceDescriptor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the resourceDescriptor and deletes it. Returns an error if one occurs.
func (c *resourceDescriptors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("resourcedescriptors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceDescriptors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("resourcedescriptors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched resourceDescriptor.
func (c *resourceDescriptors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceDescriptor, err error) {
	result = &v1alpha1.ResourceDescriptor{}
	err = c.client.Patch(pt).
		Resource("resourcedescriptors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
