/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	metav1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// ResourceOutlinesGetter has a method to return a ResourceOutlineInterface.
// A group's client should implement this interface.
type ResourceOutlinesGetter interface {
	ResourceOutlines() ResourceOutlineInterface
}

// ResourceOutlineInterface has methods to work with ResourceOutline resources.
type ResourceOutlineInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*metav1alpha1.ResourceOutline, error)
	ResourceOutlineExpansion
}

// resourceOutlines implements ResourceOutlineInterface
type resourceOutlines struct {
	*gentype.Client[*metav1alpha1.ResourceOutline]
}

// newResourceOutlines returns a ResourceOutlines
func newResourceOutlines(c *MetaV1alpha1Client) *resourceOutlines {
	return &resourceOutlines{
		gentype.NewClient[*metav1alpha1.ResourceOutline](
			"resourceoutlines",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *metav1alpha1.ResourceOutline { return &metav1alpha1.ResourceOutline{} },
		),
	}
}
