/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// ResourceCalculatorsGetter has a method to return a ResourceCalculatorInterface.
// A group's client should implement this interface.
type ResourceCalculatorsGetter interface {
	ResourceCalculators() ResourceCalculatorInterface
}

// ResourceCalculatorInterface has methods to work with ResourceCalculator resources.
type ResourceCalculatorInterface interface {
	Create(ctx context.Context, resourceCalculator *v1alpha1.ResourceCalculator, opts v1.CreateOptions) (*v1alpha1.ResourceCalculator, error)
	ResourceCalculatorExpansion
}

// resourceCalculators implements ResourceCalculatorInterface
type resourceCalculators struct {
	client rest.Interface
}

// newResourceCalculators returns a ResourceCalculators
func newResourceCalculators(c *MetaV1alpha1Client) *resourceCalculators {
	return &resourceCalculators{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a resourceCalculator and creates it.  Returns the server's representation of the resourceCalculator, and an error, if there is any.
func (c *resourceCalculators) Create(ctx context.Context, resourceCalculator *v1alpha1.ResourceCalculator, opts v1.CreateOptions) (result *v1alpha1.ResourceCalculator, err error) {
	result = &v1alpha1.ResourceCalculator{}
	err = c.client.Post().
		Resource("resourcecalculators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceCalculator).
		Do(ctx).
		Into(result)
	return
}
