/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	metav1alpha1 "kmodules.xyz/resource-metadata/apis/meta/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// ResourceOutlineFiltersGetter has a method to return a ResourceOutlineFilterInterface.
// A group's client should implement this interface.
type ResourceOutlineFiltersGetter interface {
	ResourceOutlineFilters() ResourceOutlineFilterInterface
}

// ResourceOutlineFilterInterface has methods to work with ResourceOutlineFilter resources.
type ResourceOutlineFilterInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*metav1alpha1.ResourceOutlineFilter, error)
	ResourceOutlineFilterExpansion
}

// resourceOutlineFilters implements ResourceOutlineFilterInterface
type resourceOutlineFilters struct {
	*gentype.Client[*metav1alpha1.ResourceOutlineFilter]
}

// newResourceOutlineFilters returns a ResourceOutlineFilters
func newResourceOutlineFilters(c *MetaV1alpha1Client) *resourceOutlineFilters {
	return &resourceOutlineFilters{
		gentype.NewClient[*metav1alpha1.ResourceOutlineFilter](
			"resourceoutlinefilters",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *metav1alpha1.ResourceOutlineFilter { return &metav1alpha1.ResourceOutlineFilter{} },
		),
	}
}
