apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: controlplane.cluster.x-k8s.io
    k8s.io/kind: ROSAControlPlane
    k8s.io/resource: rosacontrolplanes
    k8s.io/version: v1beta2
  name: controlplane.cluster.x-k8s.io-v1beta2-rosacontrolplanes
spec:
  resource:
    group: controlplane.cluster.x-k8s.io
    kind: ROSAControlPlane
    name: rosacontrolplanes
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: controlplaneclusterxk8sio-rosacontrolplane-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:917ff26980f3c549e4c3a4d8d162b58c3198fb8a0c13bfb5f11bcf5e81f2e027
    enforceQuota: false
