apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: controlplane.cluster.x-k8s.io
    k8s.io/kind: ROSAControlPlane
    k8s.io/resource: rosacontrolplanes
    k8s.io/version: v1beta2
  name: controlplane.cluster.x-k8s.io-v1beta2-rosacontrolplanes
spec:
  resource:
    group: controlplane.cluster.x-k8s.io
    kind: ROSAControlPlane
    name: rosacontrolplanes
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: controlplaneclusterxk8sio-rosacontrolplane-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a04e82c7410e5cdf4a4b1ade089fc45a2d70784445c794fb6c085d7ede33f051
    enforceQuota: false
