apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubevault.com
    k8s.io/kind: VaultServer
    k8s.io/resource: vaultservers
    k8s.io/version: v1alpha2
  name: kubevault.com-v1alpha2-vaultservers
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubevault.com/vaultservers.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubevault.com/vaultservers.png
    type: image/png
  resource:
    group: kubevault.com
    kind: VaultServer
    name: vaultservers
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubevaultcom-vaultserver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d11258850aba982aaedb80f28705ed6ef5e46da0eeeaf011f5d94f4ace119991
    enforceQuota: false
    options:
      name: kubevaultcom-vaultserver-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cbe63cdba172e5f23b16e4be98dbd16924b99a74282f06a3b0fbea9be6252ad6
  variants:
  - name: default
    selector:
      matchLabels:
        charts.x-helm.dev/is-default-preset: "true"
