apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubevault.com
    k8s.io/kind: VaultServer
    k8s.io/resource: vaultservers
    k8s.io/version: v1alpha2
  name: kubevault.com-v1alpha2-vaultservers
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubevault.com/vaultservers.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubevault.com/vaultservers.png
    type: image/png
  resource:
    group: kubevault.com
    kind: VaultServer
    name: vaultservers
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubevaultcom-vaultserver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:287800b678f96af86d7429ebe7c5230c4113184266e95ac1be931518c62719ee
    enforceQuota: false
    options:
      name: kubevaultcom-vaultserver-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5910f206fe8e8e1b5519d6b13fd71612c76c162d4e244432bcab8972e5e8c54a
  variants:
  - name: default
    selector:
      matchLabels:
        charts.x-helm.dev/is-default-preset: "true"
