apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kubevault.com
    k8s.io/kind: VaultServer
    k8s.io/resource: vaultservers
    k8s.io/version: v1alpha2
  name: kubevault.com-v1alpha2-vaultservers
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubevault.com/vaultservers.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/kubevault.com/vaultservers.png
    type: image/png
  resource:
    group: kubevault.com
    kind: VaultServer
    name: vaultservers
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: kubevaultcom-vaultserver-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:12e1b18256e20e09c168bdd99666a0f2d59f5da2d1260abf38e41b38922a150c
    enforceQuota: false
    options:
      name: kubevaultcom-vaultserver-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2abb0a381f6bf30a27c9b8e4227c13a4cb073ac50f1db9b0739af18fe5644526
  variants:
  - name: default
    selector:
      matchLabels:
        charts.x-helm.dev/is-default-preset: "true"
