apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: addons.kubestash.com
    k8s.io/kind: Function
    k8s.io/resource: functions
    k8s.io/version: v1alpha1
  name: addons.kubestash.com-v1alpha1-functions
spec:
  resource:
    group: addons.kubestash.com
    kind: Function
    name: functions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: addonskubestashcom-function-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4f2c8db0a172b199d3e66224d5bdede38a3b8c8129cbea96ea34e1a76b289207
    enforceQuota: false
