apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apps.k8s.appscode.com
    k8s.io/kind: PlacementPolicy
    k8s.io/resource: placementpolicies
    k8s.io/version: v1
  name: apps.k8s.appscode.com-v1-placementpolicies
spec:
  resource:
    group: apps.k8s.appscode.com
    kind: PlacementPolicy
    name: placementpolicies
    scope: Cluster
    version: v1
  ui:
    editor:
      name: appsk8sappscodecom-placementpolicy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9e6aec0d3ffce12bb8291db262d72267668ddb5073a5acd6027ae08cd530d087
    enforceQuota: false
