apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: Cluster
    k8s.io/resource: clusters
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-clusters
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: Cluster
    name: clusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-cluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:80a6940a55d262e196af3d9a8b8e5e5750da05233a367bcd8336a93103e86025
    enforceQuota: false
