apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: Cluster
    k8s.io/resource: clusters
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-clusters
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: Cluster
    name: clusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-cluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:12ec7b92bc469f68325f30d096d03e686a28d4358ff6ce511a7056585b36eff5
    enforceQuota: false
