apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: ClusterParameterGroup
    k8s.io/resource: clusterparametergroups
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-clusterparametergroups
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: ClusterParameterGroup
    name: clusterparametergroups
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-clusterparametergroup-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:58a92961bc90cdb9ec3ca93fca0b06c59da4f8d8cdb649c2ea856dd27fb436ec
    enforceQuota: false
