apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: Cluster
    k8s.io/resource: clusters
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-clusters
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: Cluster
    name: clusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-cluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:64a5e2aecf198f16d4a163c5da9c122f410c5509a5cdf1437bf3820ddeee8d7b
    enforceQuota: false
