apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: ClusterInstance
    k8s.io/resource: clusterinstances
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-clusterinstances
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: ClusterInstance
    name: clusterinstances
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-clusterinstance-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a3bff3df9525906421d699a88fad338bc32e828276054e385a5481bdc0420adb
    enforceQuota: false
