apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: EventSubscription
    k8s.io/resource: eventsubscriptions
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-eventsubscriptions
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: EventSubscription
    name: eventsubscriptions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-eventsubscription-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:5a99e81e9e590a296c08ecc0e6026f5a0540b40701af5acd1fc1d0c437c8ddd8
    enforceQuota: false
