apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: EventSubscription
    k8s.io/resource: eventsubscriptions
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-eventsubscriptions
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: EventSubscription
    name: eventsubscriptions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-eventsubscription-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e28e0d6d8546e7ecc58526f11504ba1e82a91cfa862a1fee2c68fec7188adb51
    enforceQuota: false
