apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: EventSubscription
    k8s.io/resource: eventsubscriptions
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-eventsubscriptions
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: EventSubscription
    name: eventsubscriptions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-eventsubscription-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a1a2e918c5684136f53cb58bcb2546f0c90e8b05796933c0eb2d9f5533dab112
    enforceQuota: false
