apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: docdb.aws.kubedb.com
    k8s.io/kind: GlobalCluster
    k8s.io/resource: globalclusters
    k8s.io/version: v1alpha1
  name: docdb.aws.kubedb.com-v1alpha1-globalclusters
spec:
  resource:
    group: docdb.aws.kubedb.com
    kind: GlobalCluster
    name: globalclusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: docdbawskubedbcom-globalcluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ca976b680498fb4062a5af315b6e9af1d74fbf789e3050705f6d2bc36e59b7ac
    enforceQuota: false
