apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: config.virtual-secrets.dev
    k8s.io/kind: SecretMetadata
    k8s.io/resource: secretmetadatas
    k8s.io/version: v1alpha1
  name: config.virtual-secrets.dev-v1alpha1-secretmetadatas
spec:
  resource:
    group: config.virtual-secrets.dev
    kind: SecretMetadata
    name: secretmetadatas
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: configvirtualsecretsdev-secretmetadata-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8fd10f8eabe301b2288bb00d4b402ff8b9585ae8598cb3af2b0c768dfb7d8de4
    enforceQuota: false
