apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: config.virtual-secrets.dev
    k8s.io/kind: SecretStore
    k8s.io/resource: secretstores
    k8s.io/version: v1alpha1
  name: config.virtual-secrets.dev-v1alpha1-secretstores
spec:
  resource:
    group: config.virtual-secrets.dev
    kind: SecretStore
    name: secretstores
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: configvirtualsecretsdev-secretstore-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1ce1215b50743f31c654193d98380b6a81800a429c965f3bd7d1b996b3566fbf
    enforceQuota: false
