apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: PrivateDNSZoneVirtualNetworkLink
    k8s.io/resource: privatednszonevirtualnetworklinks
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-privatednszonevirtualnetworklinks
spec:
  resource:
    group: network.azure.kubedb.com
    kind: PrivateDNSZoneVirtualNetworkLink
    name: privatednszonevirtualnetworklinks
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-privatednszonevirtualnetworklink-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a19c2c211d3e162f13ecc67024cd7b0e9c3846a2913e078f4b95a695bf3a3f27
    enforceQuota: false
