apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: PrivateDNSZone
    k8s.io/resource: privatednszones
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-privatednszones
spec:
  resource:
    group: network.azure.kubedb.com
    kind: PrivateDNSZone
    name: privatednszones
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-privatednszone-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:69ee38fbb06cea0d5a4fb2f769a28782e80070ea8e7d77f48ad443cec6320f6e
    enforceQuota: false
