apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: PrivateDNSZoneVirtualNetworkLink
    k8s.io/resource: privatednszonevirtualnetworklinks
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-privatednszonevirtualnetworklinks
spec:
  resource:
    group: network.azure.kubedb.com
    kind: PrivateDNSZoneVirtualNetworkLink
    name: privatednszonevirtualnetworklinks
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-privatednszonevirtualnetworklink-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:65a5085d922f0790c1959f3204af194d7aa2d70429252f91b03d8f656cf294d8
    enforceQuota: false
