apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: RouteTable
    k8s.io/resource: routetables
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-routetables
spec:
  resource:
    group: network.azure.kubedb.com
    kind: RouteTable
    name: routetables
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-routetable-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:db6b27f591e728b860bee42fb0f44271acfaf708ffd8a1d7211383cfb90d46d3
    enforceQuota: false
