apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: RouteTable
    k8s.io/resource: routetables
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-routetables
spec:
  resource:
    group: network.azure.kubedb.com
    kind: RouteTable
    name: routetables
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-routetable-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ef2c6d56d9b3880c8f6b74b19f097bd3a920b6821259d81b38497550d196550a
    enforceQuota: false
