apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: SubnetNetworkSecurityGroupAssociation
    k8s.io/resource: subnetnetworksecuritygroupassociations
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-subnetnetworksecuritygroupassociations
spec:
  resource:
    group: network.azure.kubedb.com
    kind: SubnetNetworkSecurityGroupAssociation
    name: subnetnetworksecuritygroupassociations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-subnetnetworksecuritygroupassociation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:2349755386d39c681f68f5e298feb62fd56499a533580d2703cbe56bc22b11c8
    enforceQuota: false
