apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: Subnet
    k8s.io/resource: subnets
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-subnets
spec:
  resource:
    group: network.azure.kubedb.com
    kind: Subnet
    name: subnets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-subnet-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f7434c86bc3fdd9357d3709199a45be6657aefde77aadf7c3d269be5fdf38b17
    enforceQuota: false
