apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: Subnet
    k8s.io/resource: subnets
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-subnets
spec:
  resource:
    group: network.azure.kubedb.com
    kind: Subnet
    name: subnets
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-subnet-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cc2b92e9aa8b93f72301a7c6e922ad71f1a094c7816f963c4e7643310ae3166c
    enforceQuota: false
