apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: SubnetRouteTableAssociation
    k8s.io/resource: subnetroutetableassociations
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-subnetroutetableassociations
spec:
  resource:
    group: network.azure.kubedb.com
    kind: SubnetRouteTableAssociation
    name: subnetroutetableassociations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-subnetroutetableassociation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b5e5e921d821f0868d5e57338253c3e5c9a70fffea21e5f8743a8531ad3b492b
    enforceQuota: false
