apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: VirtualNetwork
    k8s.io/resource: virtualnetworks
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-virtualnetworks
spec:
  resource:
    group: network.azure.kubedb.com
    kind: VirtualNetwork
    name: virtualnetworks
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-virtualnetwork-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:22d04154288d7b403ea574c876b96c6b6275408461bb4ab43617400280d7dec4
    enforceQuota: false
