apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: VirtualNetwork
    k8s.io/resource: virtualnetworks
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-virtualnetworks
spec:
  resource:
    group: network.azure.kubedb.com
    kind: VirtualNetwork
    name: virtualnetworks
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-virtualnetwork-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c1ad3a5cd33242be7330148cb961afc45d2876533a6c2aeb70544ef847848c68
    enforceQuota: false
