apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: network.azure.kubedb.com
    k8s.io/kind: VirtualNetworkPeering
    k8s.io/resource: virtualnetworkpeerings
    k8s.io/version: v1alpha1
  name: network.azure.kubedb.com-v1alpha1-virtualnetworkpeerings
spec:
  resource:
    group: network.azure.kubedb.com
    kind: VirtualNetworkPeering
    name: virtualnetworkpeerings
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: networkazurekubedbcom-virtualnetworkpeering-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:b272b59304ef32f933d77dd26411d02f374915e07e837e6cc4cc95450a9c91e9
    enforceQuota: false
