apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: DocumentDBOpsRequest
    k8s.io/resource: documentdbopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-documentdbopsrequests
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/documentdbopsrequests.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/documentdbopsrequests.png
    type: image/png
  resource:
    group: ops.kubedb.com
    kind: DocumentDBOpsRequest
    name: documentdbopsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubedbcom-documentdbopsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:da4dd853ce194a5b4fb3d1f328074b059bece59f97a53e67dac0b78c684dd2b5
    enforceQuota: false
