apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: HazelcastOpsRequest
    k8s.io/resource: hazelcastopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-hazelcastopsrequests
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/hazelcastopsrequests.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/hazelcastopsrequests.png
    type: image/png
  resource:
    group: ops.kubedb.com
    kind: HazelcastOpsRequest
    name: hazelcastopsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubedbcom-hazelcastopsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8e01955c91697d0e42eb8a98d01c8a4d1e1bef39d06341492181c26e263fbbce
    enforceQuota: false
