apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: KafkaOpsRequest
    k8s.io/resource: kafkaopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-kafkaopsrequests
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/kafkaopsrequests.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/kafkaopsrequests.png
    type: image/png
  resource:
    group: ops.kubedb.com
    kind: KafkaOpsRequest
    name: kafkaopsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubedbcom-kafkaopsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b74b31201e2b4c51bb068f477ea1536241f0983fe09206b67999c8edd296d4c9
    enforceQuota: false
