apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: MSSQLServerOpsRequest
    k8s.io/resource: mssqlserveropsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-mssqlserveropsrequests
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/mssqlserveropsrequests.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/mssqlserveropsrequests.png
    type: image/png
  resource:
    group: ops.kubedb.com
    kind: MSSQLServerOpsRequest
    name: mssqlserveropsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubedbcom-mssqlserveropsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:67416f1807a167885fb8e00cb3ee2a57cb579018790fa0b15c0c475fa90bd4d7
    enforceQuota: false
