apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: Neo4jOpsRequest
    k8s.io/resource: neo4jopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-neo4jopsrequests
spec:
  resource:
    group: ops.kubedb.com
    kind: Neo4jOpsRequest
    name: neo4jopsrequests
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: opskubedbcom-neo4jopsrequest-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c61ae107558e3692bdbeb6b26c406a9dab9cedc5ad8dbd97fbe3b41e0dbeb463
    enforceQuota: false
