apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: expansion.gatekeeper.sh
    k8s.io/kind: ExpansionTemplate
    k8s.io/resource: expansiontemplate
    k8s.io/version: v1alpha1
  name: expansion.gatekeeper.sh-v1alpha1-expansiontemplate
spec:
  resource:
    group: expansion.gatekeeper.sh
    kind: ExpansionTemplate
    name: expansiontemplate
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: expansiongatekeepersh-expansiontemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d712ddb086750fc3e7b614183a276c40fc51577e99ec9d1bee5db43b73b0e966
    enforceQuota: false
