apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupConfiguration
    k8s.io/resource: backupconfigurations
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupConfiguration
    name: backupconfigurations
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f1ce740932110377ba83ceda30c941ebf1473761c2fad321e3de6a4fde6e40cb
    enforceQuota: false
    options:
      name: corekubestashcom-backupconfiguration-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f3ac2b918751dc47fe5aa9caf209bb34292e43d96f68333bb4e0d0a7de8ee565
