apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupConfiguration
    k8s.io/resource: backupconfigurations
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupConfiguration
    name: backupconfigurations
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:d9795879cbd4d3cbf01c78a0cde9cc8a90560aa79e085da6b65658bc93f79676
    enforceQuota: false
    options:
      name: corekubestashcom-backupconfiguration-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:fa1a75a3706768931d8fc2d0d23fcb0bd2a230faf33ecb3246d41efe37952236
