apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupConfiguration
    k8s.io/resource: backupconfigurations
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupConfiguration
    name: backupconfigurations
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:f02be31a3a5855863bcbee67d3cb015bde1a49fc52eca152242f23893c9c54fe
    enforceQuota: false
    options:
      name: corekubestashcom-backupconfiguration-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:29c46099a9ca44a2716a8679495cfe0759236dd1e7d6863bbfe707dec6fde865
