apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupSession
    k8s.io/resource: backupsessions
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupsessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupsessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupsessions.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupSession
    name: backupsessions
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupsession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:fdb048ccc9fcdbc47fa65b5fdde02f10c4cde81f443786e073bb5668558b43e9
    enforceQuota: false
    options:
      name: corekubestashcom-backupsession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1bcd12d29b0f415a2d3bd7282e44e53ccdbf085b183a939ace61a710ca466138
