apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupSession
    k8s.io/resource: backupsessions
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupsessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupsessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupsessions.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupSession
    name: backupsessions
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupsession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:0c70855214a07b7648722b4c00b70a647555ccce0dd6c3a2f445d048b3484427
    enforceQuota: false
    options:
      name: corekubestashcom-backupsession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:ecbbd182a1b43904e68e7851a7d108b6e995fcf5b103d3f673f4caa5408755ef
