apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupSession
    k8s.io/resource: backupsessions
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupsessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupsessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupsessions.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupSession
    name: backupsessions
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupsession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:b4a467f5bd597e340c0fe2908947d5fcc5d1543433159184a08174de812ca4f7
    enforceQuota: false
    options:
      name: corekubestashcom-backupsession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:747ece83afcd1e79bd69307c0b87915786045e669ea20f6973f0ecfd1dc16836
