apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: HookTemplate
    k8s.io/resource: hooktemplates
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-hooktemplates
spec:
  resource:
    group: core.kubestash.com
    kind: HookTemplate
    name: hooktemplates
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-hooktemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:af646f28bad3c05a0ea5b760d8964a6514ab45fdd0d85235035d6bcaddd9f969
    enforceQuota: false
