apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-restoresessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/restoresessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/restoresessions.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-restoresession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1fcbdea4093e04f5c8b437f126812a3bad38b1c87775e07dbae940e7faa46a4f
    enforceQuota: false
    options:
      name: corekubestashcom-restoresession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a726b442dc9b6ab6af60c3a16ef77a5fac4fca7548106c7dfdcf4d83aa05e7ac
