apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-restoresessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/restoresessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/restoresessions.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-restoresession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4993d137cbe11c2b128639c3d26aeb775ed72af94d40f447e1ce9357203268c4
    enforceQuota: false
    options:
      name: corekubestashcom-restoresession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8fa64fd78b6c320abb1ba567c45d4eca3a82931ee0710b59de35f8f8a1abc0c1
