apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-restoresessions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/restoresessions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/restoresessions.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-restoresession-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:970cf7b7910235a3f7367eff0413e1f4be0bb4865dc18dadd283b0044d8456bf
    enforceQuota: false
    options:
      name: corekubestashcom-restoresession-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9011a78d2dba5089c2ceaf190f1333c5787b7f6c18a48735fe869c26836f4669
