apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: node.k8s.appscode.com
    k8s.io/kind: NodeTopology
    k8s.io/resource: nodetopologies
    k8s.io/version: v1alpha1
  name: node.k8s.appscode.com-v1alpha1-nodetopologies
spec:
  resource:
    group: node.k8s.appscode.com
    kind: NodeTopology
    name: nodetopologies
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: nodek8sappscodecom-nodetopology-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:145c62c0059d00d9190d80235ec6b0e07c9d137acfb04e3132233658cb1f967d
    enforceQuota: false
