apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: external-dns.appscode.com
    k8s.io/kind: ExternalDNS
    k8s.io/resource: externaldns
    k8s.io/version: v1alpha1
  name: external-dns.appscode.com-v1alpha1-externaldns
spec:
  resource:
    group: external-dns.appscode.com
    kind: ExternalDNS
    name: externaldns
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: externaldnsappscodecom-externaldns-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:777bf1506e2b24accc6ba609a930fcf4425c3dc8351eb4149b546c31c4e959d5
    enforceQuota: false
