apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: external-dns.appscode.com
    k8s.io/kind: ExternalDNS
    k8s.io/resource: externaldns
    k8s.io/version: v1alpha1
  name: external-dns.appscode.com-v1alpha1-externaldns
spec:
  resource:
    group: external-dns.appscode.com
    kind: ExternalDNS
    name: externaldns
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: externaldnsappscodecom-externaldns-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:3ffb09258a6117a4145e0dc2d85ae76d143daec08bb7531256a46bf27da39ca3
    enforceQuota: false
