apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: MariaDBBinding
    k8s.io/resource: mariadbbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-mariadbbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: MariaDBBinding
    name: mariadbbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-mariadbbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c6c7dade362d6a4726696538c49f78aa5642a5bf02c257b512180980bde94de8
    enforceQuota: false
