apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: MemcachedBinding
    k8s.io/resource: memcachedbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-memcachedbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: MemcachedBinding
    name: memcachedbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-memcachedbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:af27ddaf3cfca921cc3b9c73b03d1784a61686f52aace99c0b801690f753a79d
    enforceQuota: false
