apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: MongoDBBinding
    k8s.io/resource: mongodbbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-mongodbbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: MongoDBBinding
    name: mongodbbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-mongodbbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:315dcc579c4966736e31543e4c6411acf1a3a192b4f75982c49490e73e52364e
    enforceQuota: false
