apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: MongoDBBinding
    k8s.io/resource: mongodbbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-mongodbbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: MongoDBBinding
    name: mongodbbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-mongodbbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:1ec6cd4656d8e6ccaea675545eae625f4e6a38e22aedb5c8bd3214bde6c7e701
    enforceQuota: false
