apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: MongoDBBinding
    k8s.io/resource: mongodbbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-mongodbbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: MongoDBBinding
    name: mongodbbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-mongodbbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7118ff5a3ba3866c4ad25f48d2f23886259b64ee3401552ea058d7e1f9b6fc4d
    enforceQuota: false
