apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: MySQLBinding
    k8s.io/resource: mysqlbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-mysqlbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: MySQLBinding
    name: mysqlbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-mysqlbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:02dbf31e3f8a3bd3d38b823c767030e79cb68e04d97b0ee0b13e6156e0a4c6d0
    enforceQuota: false
