apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: PgBouncerBinding
    k8s.io/resource: pgbouncerbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-pgbouncerbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: PgBouncerBinding
    name: pgbouncerbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-pgbouncerbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:73ac082b6a4f3744674388fc8577b5142e7781140afb3ccc95e5a3f6d96dbef7
    enforceQuota: false
