apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: catalog.kubeware.dev
    k8s.io/kind: ProxySQLBinding
    k8s.io/resource: proxysqlbindings
    k8s.io/version: v1alpha1
  name: catalog.kubeware.dev-v1alpha1-proxysqlbindings
spec:
  resource:
    group: catalog.kubeware.dev
    kind: ProxySQLBinding
    name: proxysqlbindings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: catalogkubewaredev-proxysqlbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:27a9e4181c04fc91ade8bb953e5bd67c534d12c94feb9bf0d55454824dbab047
    enforceQuota: false
