/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	uiv1alpha1 "kmodules.xyz/resource-metadata/apis/ui/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterProfilesGetter has a method to return a ClusterProfileInterface.
// A group's client should implement this interface.
type ClusterProfilesGetter interface {
	ClusterProfiles() ClusterProfileInterface
}

// ClusterProfileInterface has methods to work with ClusterProfile resources.
type ClusterProfileInterface interface {
	Create(ctx context.Context, clusterProfile *uiv1alpha1.ClusterProfile, opts v1.CreateOptions) (*uiv1alpha1.ClusterProfile, error)
	Update(ctx context.Context, clusterProfile *uiv1alpha1.ClusterProfile, opts v1.UpdateOptions) (*uiv1alpha1.ClusterProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*uiv1alpha1.ClusterProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*uiv1alpha1.ClusterProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *uiv1alpha1.ClusterProfile, err error)
	ClusterProfileExpansion
}

// clusterProfiles implements ClusterProfileInterface
type clusterProfiles struct {
	*gentype.ClientWithList[*uiv1alpha1.ClusterProfile, *uiv1alpha1.ClusterProfileList]
}

// newClusterProfiles returns a ClusterProfiles
func newClusterProfiles(c *UiV1alpha1Client) *clusterProfiles {
	return &clusterProfiles{
		gentype.NewClientWithList[*uiv1alpha1.ClusterProfile, *uiv1alpha1.ClusterProfileList](
			"clusterprofiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *uiv1alpha1.ClusterProfile { return &uiv1alpha1.ClusterProfile{} },
			func() *uiv1alpha1.ClusterProfileList { return &uiv1alpha1.ClusterProfileList{} },
		),
	}
}
