/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	uiv1alpha1 "kmodules.xyz/resource-metadata/apis/ui/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FeaturesGetter has a method to return a FeatureInterface.
// A group's client should implement this interface.
type FeaturesGetter interface {
	Features() FeatureInterface
}

// FeatureInterface has methods to work with Feature resources.
type FeatureInterface interface {
	Create(ctx context.Context, feature *uiv1alpha1.Feature, opts v1.CreateOptions) (*uiv1alpha1.Feature, error)
	Update(ctx context.Context, feature *uiv1alpha1.Feature, opts v1.UpdateOptions) (*uiv1alpha1.Feature, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, feature *uiv1alpha1.Feature, opts v1.UpdateOptions) (*uiv1alpha1.Feature, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*uiv1alpha1.Feature, error)
	List(ctx context.Context, opts v1.ListOptions) (*uiv1alpha1.FeatureList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *uiv1alpha1.Feature, err error)
	FeatureExpansion
}

// features implements FeatureInterface
type features struct {
	*gentype.ClientWithList[*uiv1alpha1.Feature, *uiv1alpha1.FeatureList]
}

// newFeatures returns a Features
func newFeatures(c *UiV1alpha1Client) *features {
	return &features{
		gentype.NewClientWithList[*uiv1alpha1.Feature, *uiv1alpha1.FeatureList](
			"features",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *uiv1alpha1.Feature { return &uiv1alpha1.Feature{} },
			func() *uiv1alpha1.FeatureList { return &uiv1alpha1.FeatureList{} },
		),
	}
}
