/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/ui/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// ResourceEditorsGetter has a method to return a ResourceEditorInterface.
// A group's client should implement this interface.
type ResourceEditorsGetter interface {
	ResourceEditors() ResourceEditorInterface
}

// ResourceEditorInterface has methods to work with ResourceEditor resources.
type ResourceEditorInterface interface {
	Create(ctx context.Context, resourceEditor *v1alpha1.ResourceEditor, opts v1.CreateOptions) (*v1alpha1.ResourceEditor, error)
	Update(ctx context.Context, resourceEditor *v1alpha1.ResourceEditor, opts v1.UpdateOptions) (*v1alpha1.ResourceEditor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ResourceEditor, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ResourceEditorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceEditor, err error)
	ResourceEditorExpansion
}

// resourceEditors implements ResourceEditorInterface
type resourceEditors struct {
	client rest.Interface
}

// newResourceEditors returns a ResourceEditors
func newResourceEditors(c *UiV1alpha1Client) *resourceEditors {
	return &resourceEditors{
		client: c.RESTClient(),
	}
}

// Get takes name of the resourceEditor, and returns the corresponding resourceEditor object, and an error if there is any.
func (c *resourceEditors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceEditor, err error) {
	result = &v1alpha1.ResourceEditor{}
	err = c.client.Get().
		Resource("resourceeditors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceEditors that match those selectors.
func (c *resourceEditors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ResourceEditorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ResourceEditorList{}
	err = c.client.Get().
		Resource("resourceeditors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceEditors.
func (c *resourceEditors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("resourceeditors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a resourceEditor and creates it.  Returns the server's representation of the resourceEditor, and an error, if there is any.
func (c *resourceEditors) Create(ctx context.Context, resourceEditor *v1alpha1.ResourceEditor, opts v1.CreateOptions) (result *v1alpha1.ResourceEditor, err error) {
	result = &v1alpha1.ResourceEditor{}
	err = c.client.Post().
		Resource("resourceeditors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceEditor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a resourceEditor and updates it. Returns the server's representation of the resourceEditor, and an error, if there is any.
func (c *resourceEditors) Update(ctx context.Context, resourceEditor *v1alpha1.ResourceEditor, opts v1.UpdateOptions) (result *v1alpha1.ResourceEditor, err error) {
	result = &v1alpha1.ResourceEditor{}
	err = c.client.Put().
		Resource("resourceeditors").
		Name(resourceEditor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceEditor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the resourceEditor and deletes it. Returns an error if one occurs.
func (c *resourceEditors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("resourceeditors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceEditors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("resourceeditors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched resourceEditor.
func (c *resourceEditors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceEditor, err error) {
	result = &v1alpha1.ResourceEditor{}
	err = c.client.Patch(pt).
		Resource("resourceeditors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
