apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: kms.aws.kubedb.com
    k8s.io/kind: Key
    k8s.io/resource: keys
    k8s.io/version: v1alpha1
  name: kms.aws.kubedb.com-v1alpha1-keys
spec:
  resource:
    group: kms.aws.kubedb.com
    kind: Key
    name: keys
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: kmsawskubedbcom-key-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:04652346f0898a99d44ff90ddb712e4b88db72b6153470f2268785b024db30c0
    enforceQuota: false
