/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/profile/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// ManagedClusterProfileBindingsGetter has a method to return a ManagedClusterProfileBindingInterface.
// A group's client should implement this interface.
type ManagedClusterProfileBindingsGetter interface {
	ManagedClusterProfileBindings(namespace string) ManagedClusterProfileBindingInterface
}

// ManagedClusterProfileBindingInterface has methods to work with ManagedClusterProfileBinding resources.
type ManagedClusterProfileBindingInterface interface {
	Create(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.CreateOptions) (*v1alpha1.ManagedClusterProfileBinding, error)
	Update(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterProfileBinding, error)
	UpdateStatus(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterProfileBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ManagedClusterProfileBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ManagedClusterProfileBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterProfileBinding, err error)
	ManagedClusterProfileBindingExpansion
}

// managedClusterProfileBindings implements ManagedClusterProfileBindingInterface
type managedClusterProfileBindings struct {
	client rest.Interface
	ns     string
}

// newManagedClusterProfileBindings returns a ManagedClusterProfileBindings
func newManagedClusterProfileBindings(c *ProfileV1alpha1Client, namespace string) *managedClusterProfileBindings {
	return &managedClusterProfileBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the managedClusterProfileBinding, and returns the corresponding managedClusterProfileBinding object, and an error if there is any.
func (c *managedClusterProfileBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	result = &v1alpha1.ManagedClusterProfileBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagedClusterProfileBindings that match those selectors.
func (c *managedClusterProfileBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterProfileBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ManagedClusterProfileBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managedClusterProfileBindings.
func (c *managedClusterProfileBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a managedClusterProfileBinding and creates it.  Returns the server's representation of the managedClusterProfileBinding, and an error, if there is any.
func (c *managedClusterProfileBindings) Create(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	result = &v1alpha1.ManagedClusterProfileBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterProfileBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a managedClusterProfileBinding and updates it. Returns the server's representation of the managedClusterProfileBinding, and an error, if there is any.
func (c *managedClusterProfileBindings) Update(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	result = &v1alpha1.ManagedClusterProfileBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		Name(managedClusterProfileBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterProfileBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *managedClusterProfileBindings) UpdateStatus(ctx context.Context, managedClusterProfileBinding *v1alpha1.ManagedClusterProfileBinding, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	result = &v1alpha1.ManagedClusterProfileBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		Name(managedClusterProfileBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterProfileBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the managedClusterProfileBinding and deletes it. Returns an error if one occurs.
func (c *managedClusterProfileBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managedClusterProfileBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched managedClusterProfileBinding.
func (c *managedClusterProfileBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterProfileBinding, err error) {
	result = &v1alpha1.ManagedClusterProfileBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("managedclusterprofilebindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
