/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/profile/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"
)

// ManagedClusterSetProfilesGetter has a method to return a ManagedClusterSetProfileInterface.
// A group's client should implement this interface.
type ManagedClusterSetProfilesGetter interface {
	ManagedClusterSetProfiles() ManagedClusterSetProfileInterface
}

// ManagedClusterSetProfileInterface has methods to work with ManagedClusterSetProfile resources.
type ManagedClusterSetProfileInterface interface {
	Create(ctx context.Context, managedClusterSetProfile *v1alpha1.ManagedClusterSetProfile, opts v1.CreateOptions) (*v1alpha1.ManagedClusterSetProfile, error)
	Update(ctx context.Context, managedClusterSetProfile *v1alpha1.ManagedClusterSetProfile, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterSetProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ManagedClusterSetProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ManagedClusterSetProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterSetProfile, err error)
	ManagedClusterSetProfileExpansion
}

// managedClusterSetProfiles implements ManagedClusterSetProfileInterface
type managedClusterSetProfiles struct {
	client rest.Interface
}

// newManagedClusterSetProfiles returns a ManagedClusterSetProfiles
func newManagedClusterSetProfiles(c *ProfileV1alpha1Client) *managedClusterSetProfiles {
	return &managedClusterSetProfiles{
		client: c.RESTClient(),
	}
}

// Get takes name of the managedClusterSetProfile, and returns the corresponding managedClusterSetProfile object, and an error if there is any.
func (c *managedClusterSetProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	result = &v1alpha1.ManagedClusterSetProfile{}
	err = c.client.Get().
		Resource("managedclustersetprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagedClusterSetProfiles that match those selectors.
func (c *managedClusterSetProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterSetProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ManagedClusterSetProfileList{}
	err = c.client.Get().
		Resource("managedclustersetprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managedClusterSetProfiles.
func (c *managedClusterSetProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("managedclustersetprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a managedClusterSetProfile and creates it.  Returns the server's representation of the managedClusterSetProfile, and an error, if there is any.
func (c *managedClusterSetProfiles) Create(ctx context.Context, managedClusterSetProfile *v1alpha1.ManagedClusterSetProfile, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	result = &v1alpha1.ManagedClusterSetProfile{}
	err = c.client.Post().
		Resource("managedclustersetprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterSetProfile).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a managedClusterSetProfile and updates it. Returns the server's representation of the managedClusterSetProfile, and an error, if there is any.
func (c *managedClusterSetProfiles) Update(ctx context.Context, managedClusterSetProfile *v1alpha1.ManagedClusterSetProfile, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	result = &v1alpha1.ManagedClusterSetProfile{}
	err = c.client.Put().
		Resource("managedclustersetprofiles").
		Name(managedClusterSetProfile.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterSetProfile).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the managedClusterSetProfile and deletes it. Returns an error if one occurs.
func (c *managedClusterSetProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("managedclustersetprofiles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managedClusterSetProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("managedclustersetprofiles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched managedClusterSetProfile.
func (c *managedClusterSetProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterSetProfile, err error) {
	result = &v1alpha1.ManagedClusterSetProfile{}
	err = c.client.Patch(pt).
		Resource("managedclustersetprofiles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
