apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: GatewayInfo
    k8s.io/resource: gatewayinfoes
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-gatewayinfoes
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: GatewayInfo
    name: gatewayinfoes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-gatewayinfo-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:76ec346d38688c2d704a45abeaabb964eb591c57c72f0234294521ea874e5e61
    enforceQuota: false
