apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: MenuOutline
    k8s.io/resource: menuoutlines
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-menuoutlines
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: MenuOutline
    name: menuoutlines
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-menuoutline-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:7c718e96e668e74b37800d34cdd118a972f5029363542e6a040b8ea475674296
    enforceQuota: false
