apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: Menu
    k8s.io/resource: menus
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-menus
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: Menu
    name: menus
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-menu-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1bb5c0ef5d16aca7b9b2f8cba2488ab29f6e9ab21a5e4a985b48de3b7f68dba2
    enforceQuota: false
