apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: ResourceTableDefinition
    k8s.io/resource: resourcetabledefinitions
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-resourcetabledefinitions
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: ResourceTableDefinition
    name: resourcetabledefinitions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-resourcetabledefinition-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1a9af95c528b5ffa26773303d0a7c1351da0dea2ee8a3e4fec7768387708e2c7
    enforceQuota: false
