apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: ResourceDescriptor
    k8s.io/resource: resourcedescriptors
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-resourcedescriptors
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: ResourceDescriptor
    name: resourcedescriptors
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-resourcedescriptor-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:153da3e7a399818e6822052770a763312a6d0eeeed5c3f6d9d6863a75b252d70
    enforceQuota: false
