apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: ResourceTableDefinition
    k8s.io/resource: resourcetabledefinitions
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-resourcetabledefinitions
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: ResourceTableDefinition
    name: resourcetabledefinitions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-resourcetabledefinition-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:0428ba3cc84db508902d2b239100bfc8de2ea48f95091361b8ba85e38053f4cc
    enforceQuota: false
