apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: ResourceOutlineFilter
    k8s.io/resource: resourceoutlinefilters
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-resourceoutlinefilters
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: ResourceOutlineFilter
    name: resourceoutlinefilters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-resourceoutlinefilter-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9d84973569478b4fd6c75bd8c6e7b8a5bf3850238609670e8a724591d1623e13
    enforceQuota: false
