apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: ResourceOutlineFilter
    k8s.io/resource: resourceoutlinefilters
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-resourceoutlinefilters
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: ResourceOutlineFilter
    name: resourceoutlinefilters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metak8sappscodecom-resourceoutlinefilter-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:0a2caa8d5c2b97c7601ee4ed779b455424b78adfcf203f18482a8496bbd79f74
    enforceQuota: false
