/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/identity/v1alpha1"
)

// FakeInboxTokenRequests implements InboxTokenRequestInterface
type FakeInboxTokenRequests struct {
	Fake *FakeIdentityV1alpha1
}

var inboxtokenrequestsResource = v1alpha1.SchemeGroupVersion.WithResource("inboxtokenrequests")

var inboxtokenrequestsKind = v1alpha1.SchemeGroupVersion.WithKind("InboxTokenRequest")

// Create takes the representation of a inboxTokenRequest and creates it.  Returns the server's representation of the inboxTokenRequest, and an error, if there is any.
func (c *FakeInboxTokenRequests) Create(ctx context.Context, inboxTokenRequest *v1alpha1.InboxTokenRequest, opts v1.CreateOptions) (result *v1alpha1.InboxTokenRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(inboxtokenrequestsResource, inboxTokenRequest), &v1alpha1.InboxTokenRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InboxTokenRequest), err
}
