apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: repositories.stash.appscode.com
    k8s.io/kind: Snapshot
    k8s.io/resource: snapshots
    k8s.io/version: v1alpha1
  name: repositories.stash.appscode.com-v1alpha1-snapshots
spec:
  resource:
    group: repositories.stash.appscode.com
    kind: Snapshot
    name: snapshots
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: repositoriesstashappscodecom-snapshot-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e0044dfda0a84b14c4bf47b97bf32df9aad4fcf0ed2372e14278e22fb7fe122b
    enforceQuota: false
