apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: repositories.stash.appscode.com
    k8s.io/kind: Snapshot
    k8s.io/resource: snapshots
    k8s.io/version: v1alpha1
  name: repositories.stash.appscode.com-v1alpha1-snapshots
spec:
  resource:
    group: repositories.stash.appscode.com
    kind: Snapshot
    name: snapshots
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: repositoriesstashappscodecom-snapshot-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3f7102835c8a3849801276173dd398f9a8cf517b8ac34c7d6c77d4b069bf278c
    enforceQuota: false
