apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.x-k8s.io
    k8s.io/kind: Cluster
    k8s.io/resource: clusters
    k8s.io/version: v1beta1
  name: cluster.x-k8s.io-v1beta1-clusters
spec:
  resource:
    group: cluster.x-k8s.io
    kind: Cluster
    name: clusters
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: clusterxk8sio-cluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:7cf2783c01d0ceb626ef59833059e8d5b2a9d75de671fde3108a34c140ee5493
    enforceQuota: false
