apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.x-k8s.io
    k8s.io/kind: MachinePool
    k8s.io/resource: machinepools
    k8s.io/version: v1beta1
  name: cluster.x-k8s.io-v1beta1-machinepools
spec:
  resource:
    group: cluster.x-k8s.io
    kind: MachinePool
    name: machinepools
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: clusterxk8sio-machinepool-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c6df97727cf7c168c7ac46e32a7d7660b854df30370173c5bebef06b9479aac9
    enforceQuota: false
