apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.x-k8s.io
    k8s.io/kind: MachineHealthCheck
    k8s.io/resource: machinehealthchecks
    k8s.io/version: v1beta1
  name: cluster.x-k8s.io-v1beta1-machinehealthchecks
spec:
  resource:
    group: cluster.x-k8s.io
    kind: MachineHealthCheck
    name: machinehealthchecks
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: clusterxk8sio-machinehealthcheck-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2edb44b9242bbff23fe6a0441ec370fa7b40dc6f42b6daa66625783029fe47e9
    enforceQuota: false
