apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: Account
    k8s.io/resource: accounts
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-accounts
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: Account
    name: accounts
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-account-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:abd2b152c5bc41cafeadcb923844f6906a67943d3ea5d681c9a76cbd2aa6c81c
    enforceQuota: false
