apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: CassandraCluster
    k8s.io/resource: cassandraclusters
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-cassandraclusters
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: CassandraCluster
    name: cassandraclusters
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-cassandracluster-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:25984c725d3b7366131cbf316e18ff4ae81d085c2d4be3c88be474eb6a8df0e9
    enforceQuota: false
