apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: CassandraKeySpace
    k8s.io/resource: cassandrakeyspaces
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-cassandrakeyspaces
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: CassandraKeySpace
    name: cassandrakeyspaces
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-cassandrakeyspace-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8997c04c86e6dc87e21c42de132ac80ce83287399b0bf430b6ed3471ff18705f
    enforceQuota: false
