apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: CassandraTable
    k8s.io/resource: cassandratables
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-cassandratables
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: CassandraTable
    name: cassandratables
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-cassandratable-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:9210f476bedfb2e26d7daf32641e6b1b8f3e925d891236a44caee0e92ebca928
    enforceQuota: false
