apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: GremlinDatabase
    k8s.io/resource: gremlindatabases
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-gremlindatabases
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: GremlinDatabase
    name: gremlindatabases
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-gremlindatabase-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:614a7a6d0d7a13994f62fc88a286c9279bac83ee43c8e7d8649b7d5137d4bbbc
    enforceQuota: false
