apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: GremlinGraph
    k8s.io/resource: gremlingraphs
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-gremlingraphs
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: GremlinGraph
    name: gremlingraphs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-gremlingraph-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:647025b26c1fb08ced48263867acd8f47ccf2694d79be3bb773ba97dcb731767
    enforceQuota: false
