apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: MongoCollection
    k8s.io/resource: mongocollections
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-mongocollections
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: MongoCollection
    name: mongocollections
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-mongocollection-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:52fe0e7378f5646147b34752eb0766723d744d8ebc146d7b551f58a09006cf20
    enforceQuota: false
