apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: SQLContainer
    k8s.io/resource: sqlcontainers
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-sqlcontainers
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: SQLContainer
    name: sqlcontainers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-sqlcontainer-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:eaec89fb0f596a6c1641273c69e5fd9b2faff321712b63ed7f94b7827c60815e
    enforceQuota: false
