apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: SQLFunction
    k8s.io/resource: sqlfunctions
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-sqlfunctions
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: SQLFunction
    name: sqlfunctions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-sqlfunction-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1917d9fd035ef96e5210d507b1c954128566f2df10ed923beeff6c9eff8c26a6
    enforceQuota: false
