apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: SQLRoleDefinition
    k8s.io/resource: sqlroledefinitions
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-sqlroledefinitions
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: SQLRoleDefinition
    name: sqlroledefinitions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-sqlroledefinition-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:256472c7988c468e648980ed3cb3a4c57071343ccf6c8558a7683a378903bb7c
    enforceQuota: false
