apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: SQLTrigger
    k8s.io/resource: sqltriggers
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-sqltriggers
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: SQLTrigger
    name: sqltriggers
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-sqltrigger-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3b2ab5863b98a7b2de26c3a319fab5bdbb408abbd724c4cf62d70030af4a6e69
    enforceQuota: false
