apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cosmosdb.azure.kubedb.com
    k8s.io/kind: Table
    k8s.io/resource: tables
    k8s.io/version: v1alpha1
  name: cosmosdb.azure.kubedb.com-v1alpha1-tables
spec:
  resource:
    group: cosmosdb.azure.kubedb.com
    kind: Table
    name: tables
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: cosmosdbazurekubedbcom-table-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:0dca81c5c9f1618fc9246375ff5cfbdde8a0ea40b445d2d47b4ce54f35f26361
    enforceQuota: false
