apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: config.gateway.envoyproxy.io
    k8s.io/kind: EnvoyProxy
    k8s.io/resource: envoyproxies
    k8s.io/version: v1alpha1
  name: config.gateway.envoyproxy.io-v1alpha1-envoyproxies
spec:
  resource:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoyproxies
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: configgatewayenvoyproxyio-envoyproxy-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:c1c9b3dd7ab3e5e35a38e73224007ff510ea514d2c271550a6be8672dc73e2b8
    enforceQuota: false
