apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: releases.x-helm.dev
    k8s.io/kind: Bundle
    k8s.io/resource: bundles
    k8s.io/version: v1alpha1
  name: releases.x-helm.dev-v1alpha1-bundles
spec:
  resource:
    group: releases.x-helm.dev
    kind: Bundle
    name: bundles
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: releasesxhelmdev-bundle-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:2f2f195ac20f44bdd5964feb133f7e60862ae318ecee66592b3ce96ac7c0ee9f
    enforceQuota: false
