apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: elasticsearch.aws.kubedb.com
    k8s.io/kind: DomainSAMLOptions
    k8s.io/resource: domainsamloptions
    k8s.io/version: v1alpha1
  name: elasticsearch.aws.kubedb.com-v1alpha1-domainsamloptions
spec:
  resource:
    group: elasticsearch.aws.kubedb.com
    kind: DomainSAMLOptions
    name: domainsamloptions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: elasticsearchawskubedbcom-domainsamloptions-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:b1d8eb2245119a58f33c1d58d0618d85a2abd8360493c48afff0cb8563a52e34
    enforceQuota: false
