/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/editor/v1alpha1"
)

// FakeEditorModels implements EditorModelInterface
type FakeEditorModels struct {
	Fake *FakeEditorV1alpha1
}

var editormodelsResource = v1alpha1.SchemeGroupVersion.WithResource("editormodels")

var editormodelsKind = v1alpha1.SchemeGroupVersion.WithKind("EditorModel")

// Create takes the representation of a editorModel and creates it.  Returns the server's representation of the editorModel, and an error, if there is any.
func (c *FakeEditorModels) Create(ctx context.Context, editorModel *v1alpha1.EditorModel, opts v1.CreateOptions) (result *v1alpha1.EditorModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(editormodelsResource, editorModel), &v1alpha1.EditorModel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EditorModel), err
}
