apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gateway.catalog.appscode.com
    k8s.io/kind: GatewayPreset
    k8s.io/resource: gatewaypresets
    k8s.io/version: v1alpha1
  name: gateway.catalog.appscode.com-v1alpha1-gatewaypresets
spec:
  resource:
    group: gateway.catalog.appscode.com
    kind: GatewayPreset
    name: gatewaypresets
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewaycatalogappscodecom-gatewaypreset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:24e198ddff23f5f7d0dbef45b46a416a881cdf0f8840a299cbe3cbcef21ad560
    enforceQuota: false
