apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: compute.gcp.kubedb.com
    k8s.io/kind: Network
    k8s.io/resource: networks
    k8s.io/version: v1alpha1
  name: compute.gcp.kubedb.com-v1alpha1-networks
spec:
  resource:
    group: compute.gcp.kubedb.com
    kind: Network
    name: networks
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: computegcpkubedbcom-network-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d0bc78ac87c33fe7cd5d1d5cb745e572a66ff0e273f6191a53bca0df230af3ce
    enforceQuota: false
