apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: compute.gcp.kubedb.com
    k8s.io/kind: NetworkPeering
    k8s.io/resource: networkpeerings
    k8s.io/version: v1alpha1
  name: compute.gcp.kubedb.com-v1alpha1-networkpeerings
spec:
  resource:
    group: compute.gcp.kubedb.com
    kind: NetworkPeering
    name: networkpeerings
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: computegcpkubedbcom-networkpeering-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6eb368154eafe9608870a3c13f56a78641f6f4e2c701f09488dac85c9b97ce3e
    enforceQuota: false
