apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: metrics.appscode.com
    k8s.io/kind: MetricsConfiguration
    k8s.io/resource: metricsconfigurations
    k8s.io/version: v1alpha1
  name: metrics.appscode.com-v1alpha1-metricsconfigurations
spec:
  resource:
    group: metrics.appscode.com
    kind: MetricsConfiguration
    name: metricsconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metricsappscodecom-metricsconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:bd9ce9b33176a7a5b568eb7e1852eb4819efd09097f350dcde01501dd1896cb1
    enforceQuota: false
