apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformariadb.azure.kubedb.com
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1alpha1
  name: dbformariadb.azure.kubedb.com-v1alpha1-configurations
spec:
  resource:
    group: dbformariadb.azure.kubedb.com
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformariadbazurekubedbcom-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:40b31f6247322db5d3f6628ebce0c5374eb38923a4f69ce3825f2bac34f63da0
    enforceQuota: false
