apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dbformariadb.azure.kubedb.com
    k8s.io/kind: Database
    k8s.io/resource: databases
    k8s.io/version: v1alpha1
  name: dbformariadb.azure.kubedb.com-v1alpha1-databases
spec:
  resource:
    group: dbformariadb.azure.kubedb.com
    kind: Database
    name: databases
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformariadbazurekubedbcom-database-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d839a811163aba605a546180c203069762f138c9a923ed8a7c43c4a3c42cf39c
    enforceQuota: false
