apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformariadb.azure.kubedb.com
    k8s.io/kind: Database
    k8s.io/resource: databases
    k8s.io/version: v1alpha1
  name: dbformariadb.azure.kubedb.com-v1alpha1-databases
spec:
  resource:
    group: dbformariadb.azure.kubedb.com
    kind: Database
    name: databases
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformariadbazurekubedbcom-database-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:cd5141738971d8bb6ef455927694c63e96f3a8b0b3c904fc2af240a74e7af7ca
    enforceQuota: false
