apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformariadb.azure.kubedb.com
    k8s.io/kind: FirewallRule
    k8s.io/resource: firewallrules
    k8s.io/version: v1alpha1
  name: dbformariadb.azure.kubedb.com-v1alpha1-firewallrules
spec:
  resource:
    group: dbformariadb.azure.kubedb.com
    kind: FirewallRule
    name: firewallrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformariadbazurekubedbcom-firewallrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e830b039882072f8cd67ae40781909b81157d31265a89f70ee5b318e709db71b
    enforceQuota: false
