apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dbformariadb.azure.kubedb.com
    k8s.io/kind: VirtualNetworkRule
    k8s.io/resource: virtualnetworkrules
    k8s.io/version: v1alpha1
  name: dbformariadb.azure.kubedb.com-v1alpha1-virtualnetworkrules
spec:
  resource:
    group: dbformariadb.azure.kubedb.com
    kind: VirtualNetworkRule
    name: virtualnetworkrules
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformariadbazurekubedbcom-virtualnetworkrule-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:70186815e40eca5d89fcd55e275fd3e4b86121d2139305cf59b6d6de2e71e4c3
    enforceQuota: false
