apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: ManagedClusterSet
    k8s.io/resource: managedclustersets
    k8s.io/version: v1beta2
  name: cluster.open-cluster-management.io-v1beta2-managedclustersets
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: ManagedClusterSet
    name: managedclustersets
    scope: Cluster
    version: v1beta2
  ui:
    editor:
      name: clusteropenclustermanagementio-managedclusterset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:2e264a0a58623cad2c80766369f7c05215153dd1cc99b0a74c49f194aa98d266
    enforceQuota: false
