apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: ManagedClusterSetBinding
    k8s.io/resource: managedclustersetbindings
    k8s.io/version: v1beta2
  name: cluster.open-cluster-management.io-v1beta2-managedclustersetbindings
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: ManagedClusterSetBinding
    name: managedclustersetbindings
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: clusteropenclustermanagementio-managedclustersetbinding-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:532cff6a1b33145454b057289d0b44e986ae3bd7e549607cd6fdd19391a13b62
    enforceQuota: false
