apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: ManagedClusterSet
    k8s.io/resource: managedclustersets
    k8s.io/version: v1beta2
  name: cluster.open-cluster-management.io-v1beta2-managedclustersets
spec:
  resource:
    group: cluster.open-cluster-management.io
    kind: ManagedClusterSet
    name: managedclustersets
    scope: Cluster
    version: v1beta2
  ui:
    editor:
      name: clusteropenclustermanagementio-managedclusterset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:e4c1e082a889e7114f6837e7cc00759b542e019d46158c12d1d563bf8f2c4420
    enforceQuota: false
