/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kmodules.xyz/resource-metadata/apis/core/v1alpha1"
)

// FakePodViews implements PodViewInterface
type FakePodViews struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var podviewsResource = v1alpha1.SchemeGroupVersion.WithResource("podviews")

var podviewsKind = v1alpha1.SchemeGroupVersion.WithKind("PodView")

// Get takes name of the podView, and returns the corresponding podView object, and an error if there is any.
func (c *FakePodViews) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PodView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podviewsResource, c.ns, name), &v1alpha1.PodView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodView), err
}

// List takes label and field selectors, and returns the list of PodViews that match those selectors.
func (c *FakePodViews) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PodViewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podviewsResource, podviewsKind, c.ns, opts), &v1alpha1.PodViewList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PodViewList{ListMeta: obj.(*v1alpha1.PodViewList).ListMeta}
	for _, item := range obj.(*v1alpha1.PodViewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}
