apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: karpenter.sh
    k8s.io/kind: NodeClaim
    k8s.io/resource: nodeclaims
    k8s.io/version: v1beta1
  name: karpenter.sh-v1beta1-nodeclaims
spec:
  resource:
    group: karpenter.sh
    kind: NodeClaim
    name: nodeclaims
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: karpentersh-nodeclaim-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2931593484b17fdfa64d5e15937051a82b5276a7d44a8a2661e95020707337b8
    enforceQuota: false
