/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "kmodules.xyz/resource-metadata/apis/core/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// PodViewsGetter has a method to return a PodViewInterface.
// A group's client should implement this interface.
type PodViewsGetter interface {
	PodViews(namespace string) PodViewInterface
}

// PodViewInterface has methods to work with PodView resources.
type PodViewInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.PodView, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.PodViewList, error)
	PodViewExpansion
}

// podViews implements PodViewInterface
type podViews struct {
	*gentype.ClientWithList[*corev1alpha1.PodView, *corev1alpha1.PodViewList]
}

// newPodViews returns a PodViews
func newPodViews(c *CoreV1alpha1Client, namespace string) *podViews {
	return &podViews{
		gentype.NewClientWithList[*corev1alpha1.PodView, *corev1alpha1.PodViewList](
			"podviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.PodView { return &corev1alpha1.PodView{} },
			func() *corev1alpha1.PodViewList { return &corev1alpha1.PodViewList{} },
		),
	}
}
