/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "kmodules.xyz/resource-metadata/apis/core/v1alpha1"
	scheme "kmodules.xyz/resource-metadata/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// ResourceSummariesGetter has a method to return a ResourceSummaryInterface.
// A group's client should implement this interface.
type ResourceSummariesGetter interface {
	ResourceSummaries(namespace string) ResourceSummaryInterface
}

// ResourceSummaryInterface has methods to work with ResourceSummary resources.
type ResourceSummaryInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.ResourceSummary, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.ResourceSummaryList, error)
	ResourceSummaryExpansion
}

// resourceSummaries implements ResourceSummaryInterface
type resourceSummaries struct {
	*gentype.ClientWithList[*corev1alpha1.ResourceSummary, *corev1alpha1.ResourceSummaryList]
}

// newResourceSummaries returns a ResourceSummaries
func newResourceSummaries(c *CoreV1alpha1Client, namespace string) *resourceSummaries {
	return &resourceSummaries{
		gentype.NewClientWithList[*corev1alpha1.ResourceSummary, *corev1alpha1.ResourceSummaryList](
			"resourcesummaries",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.ResourceSummary { return &corev1alpha1.ResourceSummary{} },
			func() *corev1alpha1.ResourceSummaryList { return &corev1alpha1.ResourceSummaryList{} },
		),
	}
}
