apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: networking.k8s.io
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1
  name: networking.k8s.io-v1-ingresses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/networking.k8s.io/ingresses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/networking.k8s.io/ingresses.png
    type: image/png
  resource:
    group: networking.k8s.io
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: networkingk8sio-ingress-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:51b50f590f3a326d4fc724b24c2b62fff2b4d7560d5a5128269d38ef708a8e41
    enforceQuota: false
