apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImageRepository
    k8s.io/resource: imagerepositories
    k8s.io/version: v1beta1
  name: image.toolkit.fluxcd.io-v1beta1-imagerepositories
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImageRepository
    name: imagerepositories
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: imagetoolkitfluxcdio-imagerepository-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8a2e42f1d25c34234987de3164e1ae9f8a3b7897cd6dc7c5b6afa11016b090fd
    enforceQuota: false
