apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: virtual-secrets.dev
    k8s.io/kind: Secret
    k8s.io/resource: secrets
    k8s.io/version: v1alpha1
  name: virtual-secrets.dev-v1alpha1-secrets
spec:
  resource:
    group: virtual-secrets.dev
    kind: Secret
    name: secrets
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: virtualsecretsdev-secret-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e5f6b349d4270ea9e538e4603fb15fa19231b30e9363c6a0e68ba5725f4d1cad
    enforceQuota: false
