apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: virtual-secrets.dev
    k8s.io/kind: Secret
    k8s.io/resource: secrets
    k8s.io/version: v1alpha1
  name: virtual-secrets.dev-v1alpha1-secrets
spec:
  resource:
    group: virtual-secrets.dev
    kind: Secret
    name: secrets
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: virtualsecretsdev-secret-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-wizards-oci
      version: sha256:954fb4bcb4e176e843e2006c608d51512b3869473d49e4b5026b15a349ec57eb
    enforceQuota: false
