apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: virtual-secrets.dev
    k8s.io/kind: SecretMount
    k8s.io/resource: secretmounts
    k8s.io/version: v1alpha1
  name: virtual-secrets.dev-v1alpha1-secretmounts
spec:
  resource:
    group: virtual-secrets.dev
    kind: SecretMount
    name: secretmounts
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: virtualsecretsdev-secretmount-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:32113167785dea8aaec83454fec316d81d5c6aed8cf5a6e5a2f2fdd5f1095c43
    enforceQuota: false
