apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apps
    k8s.io/kind: ReplicaSet
    k8s.io/resource: replicasets
    k8s.io/version: v1
  name: apps-v1-replicasets
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/apps/replicasets.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/apps/replicasets.png
    type: image/png
  resource:
    group: apps
    kind: ReplicaSet
    name: replicasets
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: apps-replicaset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a0999ab70588c7d5fc23bd397cc14a8be3af95b904b48b5ed31118edf25f2aed
    enforceQuota: false
