apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apps
    k8s.io/kind: StatefulSet
    k8s.io/resource: statefulsets
    k8s.io/version: v1
  name: apps-v1-statefulsets
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/apps/statefulsets.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/apps/statefulsets.png
    type: image/png
  resource:
    group: apps
    kind: StatefulSet
    name: statefulsets
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: apps-statefulset-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:6bd21ea090f90a3bcf985ab4213d2a7f4b943dc2473975a440f44598ac4484e7
    enforceQuota: false
